/* Generated by scripts/build-mobile.mjs — do not edit. */
const VERSION = '5c0b3a2f1d7a';
const CACHE = 'codeling-' + VERSION;

/* Every file of this build: the app, the exercise library, the Python
   interpreter, the typefaces, the icons. 29 files, 1.23 MB. */
const ASSETS = [
  "./",
  "assets/index-BBzG-9QH.js",
  "assets/index-D1S6OB4V.css",
  "favicon.png",
  "fonts/instrument-serif-400-italic.woff2",
  "fonts/instrument-serif-400.woff2",
  "fonts/inter-400.woff2",
  "fonts/inter-500.woff2",
  "fonts/inter-600.woff2",
  "fonts/jetbrains-mono-400.woff2",
  "fonts/jetbrains-mono-700.woff2",
  "icon.png",
  "index.html",
  "manifest.webmanifest",
  "pwa/apple-touch-icon.png",
  "pwa/icon-192.png",
  "pwa/icon-512.png",
  "pwa/icon-maskable-512.png",
  "pwa/splash/splash-1125x2436.png",
  "pwa/splash/splash-1170x2532.png",
  "pwa/splash/splash-1179x2556.png",
  "pwa/splash/splash-1206x2622.png",
  "pwa/splash/splash-1242x2208.png",
  "pwa/splash/splash-1242x2688.png",
  "pwa/splash/splash-1284x2778.png",
  "pwa/splash/splash-1290x2796.png",
  "pwa/splash/splash-1320x2868.png",
  "pwa/splash/splash-640x1136.png",
  "pwa/splash/splash-750x1334.png",
  "pwa/splash/splash-828x1792.png"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

// A reminder, when the platform is willing to wake us for one. Chrome grants
// this to installed apps it sees you using; everything else falls back to the
// in-page timer, and neither is allowed to nag you on a day you have practised.
self.addEventListener('periodicsync', (event) => {
  if (event.tag !== 'codeling-reminder') return;
  event.waitUntil(
    self.registration.showNotification('Your streak is waiting', {
      body: 'One short lesson keeps it alive.',
      icon: './pwa/icon-192.png',
      badge: './pwa/icon-192.png',
      tag: 'codeling-reminder',
    }),
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      const open = clients.find((client) => 'focus' in client);
      if (open) return open.focus();
      return self.clients.openWindow('./');
    }),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  // Navigations always resolve to the app shell. There is no server here to
  // ask, and every route the app has is inside that one document.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches
        .match('./index.html', { ignoreSearch: true })
        .then((cached) => cached || fetch(request))
        .catch(() => caches.match('./index.html')),
    );
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            void caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => cached);
    }),
  );
});
