import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'cpp.first',
    title: 'Compile and run',
    blurb: 'main, includes, streams, and the semicolons that matter.',
    concepts: ['cpp.main', 'cpp.iostream', 'cpp.syntax'],
    requires: [],
    level: 'intro',
    tags: ['systems', 'games'],
    unit: 'Getting started',
  },
  {
    id: 'cpp.types',
    title: 'Types and variables',
    blurb: 'Fixed sizes, auto, const, and integer division.',
    concepts: ['cpp.types', 'cpp.auto', 'cpp.const'],
    requires: ['cpp.first'],
    level: 'core',
    tags: ['systems'],
    unit: 'Getting started',
  },
  {
    id: 'cpp.control',
    title: 'Control flow',
    blurb: 'if, switch, loops, and the range-based for.',
    concepts: ['cpp.if', 'cpp.loops', 'cpp.rangefor'],
    requires: ['cpp.types'],
    level: 'core',
    tags: ['systems', 'interviews'],
    unit: 'Control flow',
  },
  {
    id: 'cpp.functions',
    title: 'Functions and references',
    blurb: 'Pass by value, by reference, by const reference — and why it matters here.',
    concepts: ['cpp.functions', 'cpp.references', 'cpp.overload'],
    requires: ['cpp.control'],
    level: 'core',
    tags: ['systems', 'games'],
    unit: 'Structure',
  },
  {
    id: 'cpp.memory',
    title: 'Pointers and memory',
    blurb: 'Addresses, the stack and heap, and never writing delete again.',
    concepts: ['cpp.pointers', 'cpp.stackheap', 'cpp.smartptr'],
    requires: ['cpp.functions'],
    level: 'advanced',
    tags: ['systems'],
    unit: 'Memory',
  },
  {
    id: 'cpp.stl',
    title: 'The standard library',
    blurb: 'vector, string, map, and the algorithms that come with them.',
    concepts: ['cpp.vector', 'cpp.string', 'cpp.map'],
    requires: ['cpp.functions'],
    level: 'applied',
    tags: ['systems', 'interviews'],
    unit: 'Standard library',
  },
];

export const cppTrack: Track = {
  id: 'cpp',
  name: 'C++',
  kind: 'language',
  tagline: 'Where the frame budget is yours to spend',
  blurb:
    'The language behind game engines, browsers and trading systems. Steeper than most, and the one that teaches you what the machine is actually doing.',
  lang: 'cpp',
  runLang: 'cpp',
  mark: 'C+',
  tags: ['systems', 'games', 'interviews'],
  goals: ['systems', 'games', 'interviews'],
  slope: 5,
  transfersFrom: ['csharp', 'rust', 'go'],
  skills,
};

export const cppExercises = forTrack('cpp', [
  /* ----------------------------------------------------------- cpp.first */
  {
    id: 'cpp.main.1',
    concepts: ['cpp.main'],
    difficulty: 2,
    kind: 'order',
    prompt: 'Order the smallest complete C++ program.',
    lines: ['#include <iostream>', '', 'int main() {', '    std::cout << "Hi\\n";', '    return 0;', '}'],
    explain: 'Execution starts at main, and returning 0 tells the operating system everything went fine.',
  },
  {
    id: 'cpp.main.2',
    concepts: ['cpp.main'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'What must main return?',
    options: ['void', 'int', 'bool', 'nothing at all'],
    answer: [1],
    explain: 'int, and the value becomes the process exit code. Non-zero means failure.',
  },
  {
    id: 'cpp.io.1',
    concepts: ['cpp.iostream'],
    difficulty: 2,
    kind: 'blank',
    prompt: 'Print name followed by a newline.',
    template: 'std::cout {{0}} name {{1}} "\\n";',
    blanks: [
      { accept: ['<<'], width: 4 },
      { accept: ['<<'], width: 4 },
    ],
    explain: 'The << operator chains: each one sends the next thing into the stream.',
  },
  {
    id: 'cpp.io.2',
    concepts: ['cpp.iostream'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What is the difference between "\\n" and std::endl?',
    options: [
      'None',
      'endl also flushes the buffer, which is slower in a loop',
      'endl works only on Windows',
      '"\\n" does not end the line',
    ],
    answer: [1],
    explain: 'Prefer "\\n". Flushing thousands of times is a real and commonly-missed cost.',
  },
  {
    id: 'cpp.syn.1',
    concepts: ['cpp.syntax'],
    difficulty: 2,
    kind: 'bug',
    prompt: 'This will not compile. Which line?',
    code: '#include <iostream>\nint main() {\n    std::cout << "hi"\n    return 0;\n}',
    buggyLine: 3,
    why: {
      options: ['Missing semicolon', 'cout is misspelled', 'main should return void'],
      answer: 0,
    },
    explain: 'Every statement ends in a semicolon. The compiler reports the error on the following line.',
  },
  {
    id: 'cpp.syn.2',
    concepts: ['cpp.syntax', 'cpp.iostream'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Print "Hello, C++!" followed by a newline.',
    runLang: 'cpp',
    starter: '#include <iostream>\n\nint main() {\n    \n    return 0;\n}',
    solution: '#include <iostream>\n\nint main() {\n    std::cout << "Hello, C++!\\n";\n    return 0;\n}',
    tests: [{ name: 'greets', expect: 'Hello, C++!' }],
    explain: 'Without <iostream> the compiler has never heard of std::cout.',
  },

  /* ----------------------------------------------------------- cpp.types */
  {
    id: 'cpp.type.1',
    concepts: ['cpp.types'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each type to what it holds.',
    pairs: [
      ['int', 'a whole number, usually 32 bits'],
      ['double', 'a number with a fractional part'],
      ['char', 'a single character'],
      ['bool', 'true or false'],
    ],
    explain: 'Unlike Python, the type is fixed when you declare it and never changes.',
  },
  {
    id: 'cpp.type.2',
    concepts: ['cpp.types'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'int a = 7, b = 2;\nstd::cout << a / b;',
    options: ['3.5', '3', '4', '3.0'],
    answer: 1,
    explain: 'Two ints divide to an int, truncating. Cast one to double first to get 3.5.',
  },
  {
    id: 'cpp.auto.1',
    concepts: ['cpp.auto'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does auto do?',
    options: [
      'Makes the variable dynamic',
      'Asks the compiler to work the type out from the initialiser',
      'Allocates on the heap',
      'Makes it global',
    ],
    answer: [1],
    explain: 'The type is still fixed and checked — you just did not have to type std::vector<int>::iterator.',
  },
  {
    id: 'cpp.const.1',
    concepts: ['cpp.const'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Make this value impossible to change.',
    template: '{{0}} int maxHealth = 100;',
    blanks: [{ accept: ['const'], width: 6 }],
    explain: 'const is checked at compile time. Reach for it by default and relax it only when you must.',
  },
  {
    id: 'cpp.const.2',
    concepts: ['cpp.const', 'cpp.types'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'Which line will the compiler reject?',
    code: 'const int limit = 10;\nint count = 0;\nlimit = 20;\ncount = 5;',
    buggyLine: 3,
    why: {
      options: ['You cannot assign to a const', 'limit is not initialised', 'count is unused'],
      answer: 0,
    },
    explain: 'That is the point of const: the mistake is a compile error rather than a runtime surprise.',
  },

  /* --------------------------------------------------------- cpp.control */
  {
    id: 'cpp.if.1',
    concepts: ['cpp.if'],
    difficulty: 2,
    kind: 'assemble',
    prompt: 'Build the header of an if that checks hp is above zero.',
    answer: ['if', '(', 'hp', '>', '0', ')', '{'],
    distractors: ['then', ':', 'elif'],
    explain: 'The condition always goes in round brackets — that is not optional as it is in some languages.',
  },
  {
    id: 'cpp.loop.1',
    concepts: ['cpp.loops'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'How many times does the body run?',
    code: 'for (int i = 0; i < 4; ++i) {\n    std::cout << i;\n}',
    options: ['3', '4', '5', '0'],
    answer: 1,
    explain: 'i takes 0, 1, 2, 3. Prefer ++i over i++ out of habit — for heavy types it avoids a copy.',
  },
  {
    id: 'cpp.loop.2',
    concepts: ['cpp.loops'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This prints one item too few. Which line?',
    code: 'std::vector<int> xs = {1, 2, 3};\nfor (int i = 0; i < xs.size() - 1; ++i) {\n    std::cout << xs[i];\n}',
    buggyLine: 2,
    why: {
      options: ['The condition should be i < xs.size()', 'i should start at 1', 'size() returns a signed value'],
      answer: 0,
    },
    explain: 'size() is already the count. Subtracting one also underflows badly on an empty vector.',
  },
  {
    id: 'cpp.rangefor.1',
    concepts: ['cpp.rangefor'],
    difficulty: 4,
    kind: 'blank',
    prompt: 'Loop over every element without copying it.',
    template: 'for ({{0}} auto& x : items) {\n    std::cout << x;\n}',
    blanks: [{ accept: ['const'], width: 6 }],
    explain: 'const auto& reads each element in place. Plain auto would copy every one.',
  },
  {
    id: 'cpp.rangefor.2',
    concepts: ['cpp.rangefor', 'cpp.loops'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Print the sum of the numbers in the vector.',
    runLang: 'cpp',
    starter: '#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> xs = {4, 8, 15, 16, 23, 42};\n    \n    return 0;\n}',
    solution:
      '#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> xs = {4, 8, 15, 16, 23, 42};\n    int total = 0;\n    for (int x : xs) total += x;\n    std::cout << total << "\\n";\n    return 0;\n}',
    tests: [{ name: 'sums to 108', expect: '108' }],
    explain: 'The range-based for reads the elements directly, with no index to get wrong.',
  },

  /* ------------------------------------------------------- cpp.functions */
  {
    id: 'cpp.fn.1',
    concepts: ['cpp.functions'],
    difficulty: 3,
    kind: 'order',
    prompt: 'Order a function definition and its call.',
    lines: ['int square(int n) {', '    return n * n;', '}', '', 'int main() {', '    std::cout << square(5);', '}'],
    explain: 'A function must be declared before it is used, which is why headers exist.',
  },
  {
    id: 'cpp.ref.1',
    concepts: ['cpp.references'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'void bump(int n) { n++; }\nint main() {\n    int x = 1;\n    bump(x);\n    std::cout << x;\n}',
    options: ['1', '2', '0', 'undefined'],
    answer: 0,
    explain: 'bump got a copy. Change the parameter to int& and it would print 2.',
  },
  {
    id: 'cpp.ref.2',
    concepts: ['cpp.references'],
    difficulty: 5,
    kind: 'match',
    prompt: 'Match each parameter form to when you would use it.',
    pairs: [
      ['int n', 'small values you only read'],
      ['const std::string& s', 'large values you only read'],
      ['std::string& s', 'when the function must modify the caller value'],
    ],
    explain: 'Passing a big object by value copies the whole thing. const& is the default for anything non-trivial.',
  },
  {
    id: 'cpp.over.1',
    concepts: ['cpp.overload'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What makes two functions with the same name legal?',
    options: [
      'Different return types',
      'Different parameter lists',
      'Different names for the parameters',
      'It is never legal',
    ],
    answer: [1],
    explain: 'Overloads are chosen by the arguments, so the return type alone cannot tell them apart.',
  },
  {
    id: 'cpp.fn.write.1',
    concepts: ['cpp.functions', 'cpp.references'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Write swap_values(a, b) that swaps two ints through references, then print them after swapping 3 and 9.',
    runLang: 'cpp',
    starter:
      '#include <iostream>\n\nvoid swap_values(int& a, int& b) {\n    \n}\n\nint main() {\n    int x = 3, y = 9;\n    swap_values(x, y);\n    std::cout << x << " " << y << "\\n";\n}',
    solution:
      '#include <iostream>\n\nvoid swap_values(int& a, int& b) {\n    int tmp = a;\n    a = b;\n    b = tmp;\n}\n\nint main() {\n    int x = 3, y = 9;\n    swap_values(x, y);\n    std::cout << x << " " << y << "\\n";\n}',
    tests: [{ name: 'swaps', expect: '9 3' }],
    explain: 'References alias the caller variables, so assigning through them changes x and y themselves.',
  },

  /* --------------------------------------------------------- cpp.memory */
  {
    id: 'cpp.ptr.1',
    concepts: ['cpp.pointers'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each symbol to what it does.',
    pairs: [
      ['&x', 'the address of x'],
      ['*p', 'the value p points at'],
      ['int* p', 'a pointer to an int'],
      ['nullptr', 'a pointer to nothing'],
    ],
    explain: '& takes an address, * follows one. They undo each other.',
  },
  {
    id: 'cpp.ptr.2',
    concepts: ['cpp.pointers'],
    difficulty: 5,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'int x = 5;\nint* p = &x;\n*p = 9;\nstd::cout << x;',
    options: ['5', '9', 'an address', '0'],
    answer: 1,
    explain: 'Writing through the pointer writes to x itself, because that is where it points.',
  },
  {
    id: 'cpp.mem.1',
    concepts: ['cpp.stackheap'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What happens to a local variable when its function returns?',
    options: [
      'It stays alive until the program ends',
      'Its stack space is reclaimed, so a pointer to it dangles',
      'It moves to the heap',
      'It is garbage collected',
    ],
    answer: [1],
    explain: 'Returning the address of a local is undefined behaviour, and often appears to work until it does not.',
  },
  {
    id: 'cpp.smart.1',
    concepts: ['cpp.smartptr'],
    difficulty: 5,
    kind: 'match',
    prompt: 'Match each smart pointer to its ownership rule.',
    pairs: [
      ['std::unique_ptr', 'exactly one owner, freed when it goes out of scope'],
      ['std::shared_ptr', 'several owners, freed when the last one goes'],
      ['std::weak_ptr', 'observes without owning, to break cycles'],
    ],
    explain: 'Modern C++ almost never writes new and delete by hand. Let the destructor do the freeing.',
  },
  {
    id: 'cpp.smart.2',
    concepts: ['cpp.smartptr', 'cpp.stackheap'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'This leaks memory. Which line is the problem?',
    code: 'void run() {\n    int* data = new int[100];\n    if (failed()) return;\n    delete[] data;\n}',
    buggyLine: 3,
    why: {
      options: [
        'The early return skips the delete',
        'new int[100] is the wrong size',
        'delete[] should be delete',
      ],
      answer: 0,
    },
    explain: 'Every path out has to free. std::vector or unique_ptr makes that automatic and impossible to forget.',
  },

  /* ------------------------------------------------------------ cpp.stl */
  {
    id: 'cpp.vec.1',
    concepts: ['cpp.vector'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Declare a growable list of ints called scores.',
    template: 'std::{{0}}<int> scores;',
    blanks: [{ accept: ['vector'], width: 8 }],
    explain: 'vector is the default container in C++. Reach for something else only with a reason.',
  },
  {
    id: 'cpp.vec.2',
    concepts: ['cpp.vector'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each vector call to what it does.',
    pairs: [
      ['push_back(x)', 'add x to the end'],
      ['size()', 'how many elements there are'],
      ['at(i)', 'element i, with bounds checking'],
      ['clear()', 'remove everything'],
    ],
    explain: 'operator[] is faster but unchecked; at() throws if you go out of range.',
  },
  {
    id: 'cpp.str.1',
    concepts: ['cpp.string'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'std::string s = "abc";\nstd::cout << s.size() << s[0];',
    options: ['3a', '4a', '3b', 'ab'],
    answer: 0,
    explain: 'std::string knows its own length; unlike a C string there is no terminator to count.',
  },
  {
    id: 'cpp.map.1',
    concepts: ['cpp.map'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What is the difference between std::map and std::unordered_map?',
    options: [
      'map keeps keys sorted; unordered_map hashes them and is faster on average',
      'unordered_map cannot hold strings',
      'map is deprecated',
      'They are the same',
    ],
    answer: [0],
    explain: 'Need iteration in key order? map. Just need fast lookup? unordered_map.',
  },
  {
    id: 'cpp.map.2',
    concepts: ['cpp.map', 'cpp.vector'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Count how many times each word appears in the vector and print "word count" in alphabetical order.',
    runLang: 'cpp',
    starter:
      '#include <iostream>\n#include <map>\n#include <string>\n#include <vector>\n\nint main() {\n    std::vector<std::string> words = {"b", "a", "b"};\n    \n    return 0;\n}',
    solution:
      '#include <iostream>\n#include <map>\n#include <string>\n#include <vector>\n\nint main() {\n    std::vector<std::string> words = {"b", "a", "b"};\n    std::map<std::string, int> counts;\n    for (const auto& w : words) counts[w]++;\n    for (const auto& pair : counts) std::cout << pair.first << " " << pair.second << "\\n";\n    return 0;\n}',
    tests: [{ name: 'counts in order', expect: 'a 1\nb 2' }],
    explain: 'counts[w]++ works on a missing key because map default-constructs the value as 0 first.',
  },
]);
