import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const cppExtraSkills: Skill[] = [
  {
    id: 'cpp.classes',
    title: 'Classes and RAII',
    blurb: 'Constructors, destructors, and the idea the whole language is built on.',
    concepts: ['cpp.classes', 'cpp.raii', 'cpp.rule5'],
    requires: ['cpp.memory'],
    level: 'advanced',
    tags: ['systems'],
    unit: 'Your own types',
  },
  {
    id: 'cpp.build',
    title: 'Building and headers',
    blurb: 'What the compiler sees, what the linker sees, and why the error is at the bottom.',
    concepts: ['cpp.headers', 'cpp.linker', 'cpp.cmake'],
    requires: ['cpp.functions'],
    level: 'applied',
    tags: ['systems'],
    unit: 'Toolchain',
  },
];

export const cppExtra = forTrack('cpp', [
  {
    id: 'cpp.main.x1',
    concepts: ['cpp.main'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which signature does a C++ program start from?',
    options: ['int main()', 'void start()', 'function main()', 'public static void main()'],
    answer: [0],
    explain: 'main returns int, and returning 0 means success. Leave the return out and 0 is assumed.',
  },
  {
    id: 'cpp.io.x1',
    concepts: ['cpp.iostream'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Print hello and a newline.',
    template: '#include <iostream>\nint main() {\n    std::{{0}} << "hello" << std::endl;\n}',
    blanks: [{ accept: ['cout'], width: 5 }],
    explain: 'cout is character output. The << operator chains, which is why you can keep adding to the line.',
  },
  {
    id: 'cpp.io.x2',
    concepts: ['cpp.iostream'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'std::cout << 1 << 2 << "\\n";',
    options: ['12', '1 2', '3', 'an error'],
    answer: 0,
    explain: 'Each << appends. Nothing is inserted between the values unless you ask for it.',
  },
  {
    id: 'cpp.syn.x1',
    concepts: ['cpp.syntax'],
    difficulty: 2,
    level: 2,
    kind: 'bug',
    prompt: 'Which line stops this compiling?',
    code: '#include <iostream>\nint main() {\n    std::cout << "hi"\n    return 0;\n}',
    buggyLine: 3,
    why: {
      options: ['The statement is missing its semicolon', 'cout needs a namespace', 'main cannot return', 'The include is wrong'],
      answer: 0,
    },
    explain: 'The compiler reports the error on the next line, because that is where it noticed.',
  },
  {
    id: 'cpp.type.x1',
    concepts: ['cpp.types'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: '#include <iostream>\nint main() { std::cout << 7 / 2 << " " << 7 / 2.0; }',
    options: ['3 3.5', '3.5 3.5', '3 3', '3.5 3'],
    answer: 0,
    explain: 'Two ints divide as ints. One double on either side is enough to make the whole expression floating point.',
  },
  {
    id: 'cpp.auto.x1',
    concepts: ['cpp.auto'],
    difficulty: 2,
    level: 3,
    kind: 'choice',
    prompt: 'Where does auto earn its keep most clearly?',
    options: [
      'auto it = names.begin(); — the iterator type is unspeakable in practice',
      'auto x = 1; instead of int x = 1;',
      'Function parameters in a plain function',
      'Anywhere the type is already written on the same line',
    ],
    answer: [0],
    explain: 'std::vector<std::string>::const_iterator is the type you are not writing. Where the type is already obvious, auto only hides it.',
  },
  {
    id: 'cpp.const.x1',
    concepts: ['cpp.const'],
    difficulty: 3,
    level: 3,
    kind: 'predict',
    prompt: 'Which line fails to compile?',
    code: 'const int limit = 5;\nint other = limit;\nlimit = 6;',
    options: ['Line 3', 'Line 2', 'Line 1', 'None'],
    answer: 0,
    explain: 'const means this name will never be assigned again. Reading it is always fine.',
  },
  {
    id: 'cpp.if.x1',
    concepts: ['cpp.if'],
    difficulty: 2,
    level: 2,
    kind: 'order',
    prompt: 'Put this branch in order.',
    lines: ['int score = 10;', 'if (score > 5) {', '    std::cout << "pass";', '} else {', '    std::cout << "fail";', '}'],
    explain: 'Condition in brackets, body in braces. Assignment inside an if is a classic typo the compiler may allow.',
  },
  {
    id: 'cpp.loop.x1',
    concepts: ['cpp.loops'],
    difficulty: 2,
    level: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for (int i = 0; i < 3; ++i) std::cout << i;',
    options: ['012', '123', '0 1 2', '3'],
    answer: 0,
    explain: 'Pre-increment on the loop variable is the convention here; for ints it makes no difference.',
  },
  {
    id: 'cpp.rf.x1',
    concepts: ['cpp.rangefor'],
    difficulty: 3,
    level: 4,
    kind: 'blank',
    prompt: 'Walk the vector without copying each element.',
    template: 'for (const auto{{0}} value : values) {\n    std::cout << value;\n}',
    blanks: [{ accept: ['&'], width: 2 }],
    explain: 'const auto& binds a reference: no copy per element, and no accidental modification.',
  },

  /* ---------------------------------------------------------- cpp.classes */
  {
    id: 'cpp.cls.1',
    concepts: ['cpp.classes'],
    difficulty: 3,
    level: 5,
    kind: 'order',
    prompt: 'Write a small class with a constructor.',
    lines: ['class Counter {', 'public:', '    Counter() : n_(0) {}', '    void bump() { ++n_; }', 'private:', '    int n_;', '};'],
    explain: 'Members are private by default in a class; the initialiser list runs before the body.',
  },
  {
    id: 'cpp.cls.2',
    concepts: ['cpp.raii'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What does RAII actually mean in practice?',
    options: [
      'A resource is owned by an object, acquired in its constructor and released in its destructor',
      'Memory is garbage collected',
      'All allocation happens on the stack',
      'Objects are reference counted',
    ],
    answer: [0],
    explain: 'Scope exit is the cleanup mechanism. It is why C++ needs no finally.',
  },
  {
    id: 'cpp.cls.3',
    concepts: ['cpp.raii'],
    difficulty: 4,
    level: 6,
    kind: 'bug',
    prompt: 'This leaks whenever process throws. Which line is the problem?',
    code: 'void run() {\n    Buffer* b = new Buffer(1024);\n    process(b);\n    delete b;\n}',
    buggyLine: 2,
    why: {
      options: [
        'Raw new means the delete is skipped if an exception unwinds the stack',
        'The buffer is too large',
        'delete should be delete[]',
        'process should take a reference',
      ],
      answer: 0,
    },
    explain: 'std::unique_ptr<Buffer> frees on the way out however the function leaves.',
  },
  {
    id: 'cpp.cls.4',
    concepts: ['cpp.rule5'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'If your class needs a custom destructor, what does the rule of five say?',
    options: [
      'It probably also needs copy/move constructors and copy/move assignment — or to delete them',
      'It should be final',
      'It cannot be copied',
      'It must be allocated on the heap',
    ],
    answer: [0],
    explain: 'A custom destructor means you own something. Copying that ownership silently is the bug it prevents.',
  },
  {
    id: 'cpp.cls.5',
    concepts: ['cpp.classes'],
    difficulty: 4,
    level: 7,
    kind: 'write',
    prompt: 'Write a struct Point with x and y, and a function that prints their sum.',
    runLang: 'cpp',
    starter:
      '#include <iostream>\n\n// define Point and total here\n\nint main() {\n    Point p{3, 4};\n    std::cout << total(p) << "\\n";\n}\n',
    solution:
      '#include <iostream>\n\nstruct Point {\n    int x;\n    int y;\n};\n\nint total(const Point& p) {\n    return p.x + p.y;\n}\n\nint main() {\n    Point p{3, 4};\n    std::cout << total(p) << "\\n";\n}\n',
    tests: [{ name: 'adds the members', expect: '7' }],
    mustContain: [{ pattern: 'struct', label: 'define a struct' }],
    explain: 'Braced initialisation fills the members in order. Taking the struct by const reference avoids a copy.',
  },

  /* ------------------------------------------------------------ cpp.build */
  {
    id: 'cpp.build.1',
    concepts: ['cpp.headers'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'What goes in a header file?',
    options: [
      'Declarations: what exists and what its type is',
      'The whole implementation, always',
      'Only macros',
      'Nothing — headers are optional',
    ],
    answer: [0],
    explain: 'Definitions go in the .cpp, so that changing one line does not rebuild the world.',
  },
  {
    id: 'cpp.build.2',
    concepts: ['cpp.headers'],
    difficulty: 4,
    level: 6,
    kind: 'blank',
    prompt: 'Stop this header being included twice in one translation unit.',
    template: '#{{0}} once\n\nvoid render();',
    blanks: [{ accept: ['pragma'], width: 7 }],
    explain: 'The older spelling is an include guard with #ifndef. Both solve the same double-definition problem.',
  },
  {
    id: 'cpp.build.3',
    concepts: ['cpp.linker'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'You get "undefined reference to render()". What is wrong?',
    options: [
      'The declaration was found but no definition was compiled or linked in',
      'The header is missing',
      'A syntax error in render',
      'The function is private',
    ],
    answer: [0],
    explain: 'Compiler errors are about one file. Linker errors are about the set of files you handed it.',
  },
  {
    id: 'cpp.build.4',
    concepts: ['cpp.cmake'],
    difficulty: 4,
    level: 7,
    kind: 'match',
    prompt: 'Match each CMake command to what it does.',
    pairs: [
      ['add_executable', 'Declares a program and its sources'],
      ['target_link_libraries', 'Says what to link against'],
      ['find_package', 'Locates a dependency'],
      ['target_include_directories', 'Adds header search paths'],
    ],
    explain: 'Modern CMake is per-target. Global commands like include_directories are the old, leaky way.',
  },
  {
    id: 'cpp.build.5',
    concepts: ['cpp.linker'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'Why does a header-only library not need linking?',
    options: [
      'Its definitions are compiled into each translation unit that includes it',
      'It is loaded at runtime',
      'The linker special-cases it',
      'It has no functions',
    ],
    answer: [0],
    explain: 'That is also why they slow compilation: every file that includes it compiles it again.',
  },
]);
