import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'cs.first',
    title: 'First program',
    blurb: 'Console output, statements, and the shape of a C# file.',
    concepts: ['cs.console', 'cs.syntax'],
    requires: [],
    level: 'intro',
    tags: ['apps', 'games'],
    unit: 'Getting started',
  },
  {
    id: 'cs.types',
    title: 'Types and variables',
    blurb: 'Value types, reference types, var, and string interpolation.',
    concepts: ['cs.types', 'cs.var', 'cs.interpolation'],
    requires: ['cs.first'],
    level: 'core',
    tags: ['apps'],
    unit: 'Getting started',
  },
  {
    id: 'cs.control',
    title: 'Control flow',
    blurb: 'if, switch expressions, foreach and while.',
    concepts: ['cs.if', 'cs.switch', 'cs.loops'],
    requires: ['cs.types'],
    level: 'core',
    tags: ['apps', 'games'],
    unit: 'Control flow',
  },
  {
    id: 'cs.methods',
    title: 'Methods',
    blurb: 'Parameters, returns, optional arguments and expression bodies.',
    concepts: ['cs.methods', 'cs.params', 'cs.expressionbody'],
    requires: ['cs.control'],
    level: 'core',
    tags: ['apps'],
    unit: 'Structure',
  },
  {
    id: 'cs.oop',
    title: 'Classes and objects',
    blurb: 'Fields, properties, constructors, and interfaces.',
    concepts: ['cs.classes', 'cs.properties', 'cs.interfaces'],
    requires: ['cs.methods'],
    level: 'applied',
    tags: ['apps', 'games'],
    unit: 'Objects',
  },
  {
    id: 'cs.collections',
    title: 'Collections and LINQ',
    blurb: 'List, Dictionary, and queries that read like sentences.',
    concepts: ['cs.list', 'cs.dictionary', 'cs.linq'],
    requires: ['cs.methods'],
    level: 'applied',
    tags: ['apps', 'data'],
    unit: 'Data',
  },
];

export const csharpTrack: Track = {
  id: 'csharp',
  name: 'C#',
  kind: 'language',
  tagline: 'Unity, Windows apps, and very good tooling',
  blurb:
    'A tidy, modern, statically typed language. The language of Unity, of .NET services, and of most native Windows software written this decade.',
  lang: 'csharp',
  runLang: 'csharp',
  mark: 'C#',
  tags: ['apps', 'games', 'interviews'],
  goals: ['apps', 'games', 'interviews'],
  slope: 3,
  transfersFrom: ['java', 'cpp', 'typescript'],
  skills,
};

export const csharpExercises = forTrack('csharp', [
  /* ------------------------------------------------------------ cs.first */
  {
    id: 'cs.con.1',
    concepts: ['cs.console'],
    difficulty: 1,
    kind: 'assemble',
    prompt: 'Build the line that writes Hello on its own line.',
    answer: ['Console', '.', 'WriteLine', '(', '"Hello"', ')', ';'],
    distractors: ['print', 'Write', 'console'],
    explain: 'WriteLine adds the newline; Write does not. Both live on the static Console class.',
  },
  {
    id: 'cs.con.2',
    concepts: ['cs.console'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'What does Console.ReadLine() return?',
    options: ['int', 'string (or null at end of input)', 'char', 'object'],
    answer: [1],
    explain: 'Always text. Convert with int.Parse, or int.TryParse when the input might be rubbish.',
  },
  {
    id: 'cs.syn.1',
    concepts: ['cs.syntax'],
    difficulty: 2,
    kind: 'bug',
    prompt: 'Which line will not compile?',
    code: 'int total = 0;\ntotal = total + 5\nConsole.WriteLine(total);',
    buggyLine: 2,
    why: {
      options: ['Missing semicolon', 'total is not declared', 'WriteLine is misspelled'],
      answer: 0,
    },
    explain: 'C# statements end with a semicolon. The compiler reports it at the next token it cannot make sense of.',
  },
  {
    id: 'cs.syn.2',
    concepts: ['cs.syntax', 'cs.console'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What are top-level statements?',
    options: [
      'Code written straight in Program.cs, without an explicit class and Main',
      'Statements outside any file',
      'A kind of comment',
      'Statements that must come first alphabetically',
    ],
    answer: [0],
    explain: 'Since C# 9 a program can be a few lines with no ceremony. The compiler writes the Main for you.',
  },

  /* ------------------------------------------------------------ cs.types */
  {
    id: 'cs.type.1',
    concepts: ['cs.types'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each type to what it is for.',
    pairs: [
      ['int', 'whole numbers'],
      ['double', 'numbers with decimals'],
      ['bool', 'true or false'],
      ['string', 'text'],
    ],
    explain: 'decimal also exists, and is what you use for money — double loses cents to rounding.',
  },
  {
    id: 'cs.type.2',
    concepts: ['cs.types'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is the difference between a struct and a class in C#?',
    options: [
      'A struct is a value type, copied on assignment; a class is a reference type',
      'Structs cannot have methods',
      'Classes are faster',
      'There is none',
    ],
    answer: [0],
    explain: 'Assigning a struct copies it. Assigning a class copies the reference, so both names see the same object.',
  },
  {
    id: 'cs.var.1',
    concepts: ['cs.var'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does `var` do?',
    options: [
      'Makes the variable dynamically typed',
      'Infers the static type from the initialiser',
      'Makes it nullable',
      'Declares a global',
    ],
    answer: [1],
    explain: 'The type is still fixed at compile time. `dynamic` is the one that defers checks to runtime.',
  },
  {
    id: 'cs.interp.1',
    concepts: ['cs.interpolation'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Complete the interpolated string.',
    template: 'Console.WriteLine({{0}}"Score: {score}");',
    blanks: [{ accept: ['$'], width: 2 }],
    explain: 'The $ prefix turns {score} into its value. Without it you get the literal braces.',
  },
  {
    id: 'cs.interp.2',
    concepts: ['cs.interpolation', 'cs.types'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Print "3 + 4 = 7" using string interpolation.',
    runLang: 'csharp',
    starter: 'int a = 3;\nint b = 4;\n',
    solution: 'int a = 3;\nint b = 4;\nConsole.WriteLine($"{a} + {b} = {a + b}");',
    tests: [{ name: 'adds', expect: '3 + 4 = 7' }],
    mustContain: [{ pattern: '$"', label: 'use an interpolated string' }],
    explain: 'Expressions work inside the braces, so the arithmetic can happen right there.',
  },

  /* ---------------------------------------------------------- cs.control */
  {
    id: 'cs.if.1',
    concepts: ['cs.if'],
    difficulty: 2,
    kind: 'order',
    prompt: 'Order this check.',
    lines: ['if (hp <= 0)', '{', '    Console.WriteLine("Game over");', '}'],
    explain: 'C# puts the opening brace on its own line by convention, though the compiler does not care.',
  },
  {
    id: 'cs.switch.1',
    concepts: ['cs.switch'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this return for "b"?',
    code: 'string Describe(string k) => k switch\n{\n    "a" => "first",\n    "b" => "second",\n    _ => "unknown"\n};',
    options: ['first', 'second', 'unknown', 'null'],
    answer: 1,
    explain: 'A switch expression returns a value, and _ is the catch-all. Missing it can be a compile error.',
  },
  {
    id: 'cs.switch.2',
    concepts: ['cs.switch'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why does a classic C# switch statement need break?',
    options: [
      'To stop execution falling into the next case',
      'To return the value',
      'It does not',
      'To exit the method',
    ],
    answer: [0],
    explain: 'C# actually forbids implicit fall-through, so it is a compile error rather than a silent bug.',
  },
  {
    id: 'cs.loop.1',
    concepts: ['cs.loops'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Loop over every name in the list.',
    template: '{{0}} (string name in names)\n{\n    Console.WriteLine(name);\n}',
    blanks: [{ accept: ['foreach'], width: 9 }],
    explain: 'foreach walks the values; a plain for is only worth it when you genuinely need the index.',
  },
  {
    id: 'cs.loop.2',
    concepts: ['cs.loops'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Print the numbers 1 to 5, one per line.',
    runLang: 'csharp',
    starter: '',
    solution: 'for (int i = 1; i <= 5; i++)\n{\n    Console.WriteLine(i);\n}',
    tests: [{ name: 'counts', expect: '1\n2\n3\n4\n5' }],
    explain: 'i <= 5 rather than i < 5, because this one is counting from 1.',
  },

  /* ---------------------------------------------------------- cs.methods */
  {
    id: 'cs.meth.1',
    concepts: ['cs.methods'],
    difficulty: 3,
    kind: 'assemble',
    prompt: 'Build the signature of a method that takes an int and returns an int.',
    answer: ['int', 'Double', '(', 'int', 'n', ')'],
    distractors: ['function', 'void', 'def'],
    explain: 'Return type first, then the name, then the typed parameters.',
  },
  {
    id: 'cs.meth.2',
    concepts: ['cs.methods'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does a return type of void mean?',
    options: ['It returns null', 'It returns nothing', 'It returns zero', 'It never finishes'],
    answer: [1],
    explain: 'A void method can still use a bare `return;` to leave early.',
  },
  {
    id: 'cs.params.1',
    concepts: ['cs.params'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does Greet() print?',
    code: 'void Greet(string name = "friend")\n{\n    Console.WriteLine($"Hi {name}");\n}',
    options: ['Hi friend', 'Hi null', 'Hi name', 'A compile error'],
    answer: 0,
    explain: 'Optional parameters take their default when the argument is left out. They must come last.',
  },
  {
    id: 'cs.expr.1',
    concepts: ['cs.expressionbody'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each expression-bodied member to its longhand.',
    pairs: [
      ['int Square(int n) => n * n;', 'a method with a single return'],
      ['public string Name => _name;', 'a read-only property'],
      ['public int Count { get; set; }', 'an auto-property with a setter'],
    ],
    explain: '=> as a member body means "this is the whole thing". It is not a lambda.',
  },
  {
    id: 'cs.meth.write.1',
    concepts: ['cs.methods', 'cs.params'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Write IsEven(n) returning a bool, and print IsEven(10).',
    runLang: 'csharp',
    starter: 'bool IsEven(int n)\n{\n    \n}\n\nConsole.WriteLine(IsEven(10));',
    solution: 'bool IsEven(int n)\n{\n    return n % 2 == 0;\n}\n\nConsole.WriteLine(IsEven(10));',
    tests: [{ name: '10 is even', expect: 'True' }],
    explain: 'C# prints booleans capitalised: True and False, unlike JavaScript or Python.',
  },

  /* -------------------------------------------------------------- cs.oop */
  {
    id: 'cs.cls.1',
    concepts: ['cs.classes'],
    difficulty: 4,
    kind: 'order',
    prompt: 'Order a small class with a constructor.',
    lines: [
      'class Player',
      '{',
      '    public string Name;',
      '    public Player(string name)',
      '    {',
      '        Name = name;',
      '    }',
      '}',
    ],
    explain: 'The constructor shares the class name exactly and declares no return type.',
  },
  {
    id: 'cs.prop.1',
    concepts: ['cs.properties'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why prefer a property over a public field?',
    options: [
      'Properties are faster',
      'You can add validation or change the implementation later without breaking callers',
      'Fields cannot be public',
      'Properties use less memory',
    ],
    answer: [1],
    explain: 'public int Hp { get; private set; } lets everyone read it and only the class change it.',
  },
  {
    id: 'cs.prop.2',
    concepts: ['cs.properties'],
    difficulty: 4,
    kind: 'blank',
    prompt: 'Declare a property readable everywhere but writable only inside the class.',
    template: 'public int Health { get; {{0}} set; }',
    blanks: [{ accept: ['private'], width: 8 }],
    explain: 'Asymmetric accessors are the cheapest encapsulation C# offers.',
  },
  {
    id: 'cs.iface.1',
    concepts: ['cs.interfaces'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What does an interface give you?',
    options: [
      'A contract of members a type promises to provide, with no implementation',
      'A base class with default code',
      'A way to store data',
      'A namespace',
    ],
    answer: [0],
    explain: 'A class can implement many interfaces but inherit only one base class.',
  },
  {
    id: 'cs.iface.2',
    concepts: ['cs.interfaces', 'cs.classes'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'This will not compile. Which line?',
    code: 'interface IDamageable\n{\n    void TakeDamage(int amount);\n}\n\nclass Crate : IDamageable\n{\n}',
    buggyLine: 7,
    why: {
      options: [
        'Crate never implements TakeDamage',
        'The interface needs a body',
        'Crate needs a constructor',
      ],
      answer: 0,
    },
    explain: 'Claiming an interface is a promise the compiler holds you to.',
  },

  /* ------------------------------------------------------ cs.collections */
  {
    id: 'cs.list.1',
    concepts: ['cs.list'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Declare a growable list of strings.',
    template: '{{0}}<string> names = new();',
    blanks: [{ accept: ['List'], width: 6 }],
    explain: 'Arrays are fixed length; List<T> grows. `new()` infers the type from the left.',
  },
  {
    id: 'cs.dict.1',
    concepts: ['cs.dictionary'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What happens on the last line?',
    code: 'var ages = new Dictionary<string, int>();\nages["ada"] = 36;\nConsole.WriteLine(ages["alan"]);',
    options: ['0', 'null', 'A KeyNotFoundException', 'An empty string'],
    answer: 2,
    explain: 'Use TryGetValue, or ContainsKey first, when the key might genuinely be missing.',
  },
  {
    id: 'cs.linq.1',
    concepts: ['cs.linq'],
    difficulty: 5,
    kind: 'match',
    prompt: 'Match each LINQ method to what it does.',
    pairs: [
      ['Where', 'keeps items matching a condition'],
      ['Select', 'transforms each item'],
      ['OrderBy', 'sorts by a key'],
      ['Any', 'true if at least one matches'],
    ],
    explain: 'Where filters, Select maps. Mixing those two up is the most common LINQ slip.',
  },
  {
    id: 'cs.linq.2',
    concepts: ['cs.linq', 'cs.list'],
    difficulty: 5,
    kind: 'assemble',
    prompt: 'Build a query for the even numbers in xs, in order.',
    answer: ['xs', '.', 'Where', '(', 'n => n % 2 == 0', ')', '.', 'OrderBy', '(', 'n => n', ')'],
    distractors: ['Select', 'Sum', 'GroupBy'],
    explain: 'LINQ is lazy: nothing runs until you enumerate it, with ToList() or a foreach.',
  },
  {
    id: 'cs.linq.3',
    concepts: ['cs.linq'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What does deferred execution mean for a LINQ query?',
    options: [
      'The query runs when you iterate it, not when you define it',
      'It runs on a background thread',
      'It caches its results forever',
      'It runs twice',
    ],
    answer: [0],
    explain: 'Change the source between defining and iterating and you get the new data — surprising until you know.',
  },
]);
