import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const csharpExtraSkills: Skill[] = [
  {
    id: 'cs.errors',
    title: 'Exceptions and null',
    blurb: 'Fail loudly, clean up reliably, and stop NullReferenceException before it starts.',
    concepts: ['cs.exceptions', 'cs.nullable', 'cs.using'],
    requires: ['cs.methods'],
    level: 'applied',
    tags: ['apps'],
    unit: 'Real programs',
  },
  {
    id: 'cs.async',
    title: 'Async and tasks',
    blurb: 'await without blocking, and the mistakes that deadlock a UI.',
    concepts: ['cs.async', 'cs.tasks'],
    requires: ['cs.errors'],
    level: 'advanced',
    tags: ['apps'],
    unit: 'Real programs',
  },
];

export const csharpExtra = forTrack('csharp', [
  {
    id: 'cs.con.x1',
    concepts: ['cs.console'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which line writes a line to the console?',
    options: ['Console.WriteLine("hi");', 'print("hi");', 'System.out.println("hi");', 'echo "hi";'],
    answer: [0],
    explain: 'WriteLine adds the newline; Write does not. The others belong to Python and Java.',
  },
  {
    id: 'cs.con.x2',
    concepts: ['cs.console'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Print the value of name.',
    template: 'string name = "Sam";\nConsole.{{0}}(name);',
    blanks: [{ accept: ['WriteLine', 'Write'], width: 10 }],
    explain: 'C# is case sensitive and its library is PascalCase, so writeline is not a thing.',
  },
  {
    id: 'cs.syn.x1',
    concepts: ['cs.syntax'],
    difficulty: 1,
    level: 1,
    kind: 'bug',
    prompt: 'Which line will not compile?',
    code: 'int total = 3;\nConsole.WriteLine(total)\nConsole.WriteLine("done");',
    buggyLine: 2,
    why: {
      options: ['The statement is missing its semicolon', 'total is the wrong type', 'WriteLine takes no arguments', 'Nothing is wrong'],
      answer: 0,
    },
    explain: 'Every statement ends in a semicolon. The compiler points at the next line, which is a lifelong annoyance.',
  },
  {
    id: 'cs.type.x1',
    concepts: ['cs.types'],
    difficulty: 2,
    level: 2,
    kind: 'match',
    prompt: 'Match each type to a value it can hold.',
    pairs: [
      ['int', '42'],
      ['double', '3.5'],
      ['bool', 'true'],
      ['string', '"hi"'],
    ],
    explain: 'C# is statically typed: the type is part of the declaration and cannot change later.',
  },
  {
    id: 'cs.var.x1',
    concepts: ['cs.var'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What type does count have?',
    code: 'var count = 5;',
    options: ['int', 'object', 'dynamic', 'var'],
    answer: 0,
    explain: 'var is inference, not dynamic typing. The type is fixed at compile time — it just is not spelled out.',
  },
  {
    id: 'cs.interp.x1',
    concepts: ['cs.interpolation'],
    difficulty: 2,
    level: 2,
    kind: 'blank',
    prompt: 'Interpolate the name into the greeting.',
    template: 'Console.WriteLine({{0}}"Hi, {name}!");',
    blanks: [{ accept: ['$'], width: 2 }],
    explain: 'The $ turns the braces into holes. Without it you print the braces literally.',
  },
  {
    id: 'cs.if.x1',
    concepts: ['cs.if'],
    difficulty: 2,
    level: 2,
    kind: 'order',
    prompt: 'Put this check in order.',
    lines: ['int temp = 30;', 'if (temp > 25)', '{', '    Console.WriteLine("hot");', '}'],
    explain: 'Braces are optional for a single statement, and leaving them out is how bugs sneak in later.',
  },
  {
    id: 'cs.loop.x1',
    concepts: ['cs.loops'],
    difficulty: 2,
    level: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for (int i = 0; i < 3; i++) Console.Write(i);',
    options: ['012', '123', '0 1 2', '3'],
    answer: 0,
    explain: 'Write does not add newlines, so the digits run together.',
  },
  {
    id: 'cs.loop.x2',
    concepts: ['cs.loops'],
    difficulty: 3,
    level: 3,
    kind: 'blank',
    prompt: 'Count from 0 to 4, using the index.',
    template: '{{0}} (int i = 0; i {{1}} 5; i++)\n{\n    Console.WriteLine(i);\n}',
    blanks: [{ accept: ['for'], width: 4 }, { accept: ['<'], width: 2 }],
    explain: 'A plain for earns its keep when you need the number itself; reach for foreach when you only need the values.',
  },
  {
    id: 'cs.switch.x1',
    concepts: ['cs.switch'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'What does a switch expression give you that a switch statement does not?',
    options: [
      'It produces a value, so you can assign the result directly',
      'It runs faster',
      'It allows fall-through',
      'It works on strings',
    ],
    answer: [0],
    explain: 'var label = n switch { 0 => "none", _ => "some" }; — one expression, no break in sight.',
  },

  /* ------------------------------------------------------------ cs.errors */
  {
    id: 'cs.err.1',
    concepts: ['cs.exceptions'],
    difficulty: 3,
    level: 5,
    kind: 'order',
    prompt: 'Handle a parse failure without crashing.',
    lines: ['try', '{', '    var n = int.Parse(text);', '}', 'catch (FormatException ex)', '{', '    Console.WriteLine(ex.Message);', '}'],
    explain: 'Catch the specific exception. catch (Exception) swallows bugs you needed to see.',
  },
  {
    id: 'cs.err.2',
    concepts: ['cs.exceptions'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'Which is better when the input might not be a number at all?',
    options: [
      'int.TryParse(text, out var n) — no exception, just a bool',
      'int.Parse inside a try/catch',
      'Convert.ToInt32 with a null check',
      'Casting with (int)',
    ],
    answer: [0],
    explain: 'Exceptions are for the exceptional. Bad user input is expected, so it should not cost a stack unwind.',
  },
  {
    id: 'cs.err.3',
    concepts: ['cs.nullable'],
    difficulty: 4,
    level: 6,
    kind: 'match',
    prompt: 'Match each null operator to what it does.',
    pairs: [
      ['?.', 'Call only if not null, else null'],
      ['??', 'Use the right side when the left is null'],
      ['??=', 'Assign only if currently null'],
      ['!', 'Tell the compiler you know it is not null'],
    ],
    explain: 'The last one silences the compiler rather than fixing anything, so use it sparingly.',
  },
  {
    id: 'cs.err.4',
    concepts: ['cs.nullable'],
    difficulty: 4,
    level: 7,
    kind: 'predict',
    prompt: 'With nullable reference types on, which line warns?',
    code: 'string a = null;\nstring? b = null;\nConsole.WriteLine(b?.Length);',
    options: ['Line 1', 'Line 2', 'Line 3', 'None of them'],
    answer: 0,
    explain: 'A plain string is non-nullable under NRT. The ? is what admits null into the type.',
  },
  {
    id: 'cs.err.5',
    concepts: ['cs.using'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What does `using var file = File.OpenText(path);` guarantee?',
    options: [
      'Dispose is called when the enclosing scope ends, however it ends',
      'The file is read into memory',
      'The file cannot be modified',
      'Nothing — it is only an import',
    ],
    answer: [0],
    explain: 'Deterministic cleanup. The garbage collector will not close your file handles for you in time.',
  },

  /* ------------------------------------------------------------- cs.async */
  {
    id: 'cs.async.1',
    concepts: ['cs.async'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What does await actually do?',
    options: [
      'Returns the thread to its caller and resumes the rest of the method when the task finishes',
      'Blocks the thread until the task finishes',
      'Starts a new thread',
      'Runs the task on the GPU',
    ],
    answer: [0],
    explain: 'Async is about not holding a thread hostage. It is concurrency, not parallelism.',
  },
  {
    id: 'cs.async.2',
    concepts: ['cs.tasks'],
    difficulty: 5,
    level: 8,
    kind: 'bug',
    prompt: 'This can deadlock in a UI app. Which line?',
    code: 'var task = LoadAsync();\nvar data = task.Result;\nShow(data);',
    buggyLine: 2,
    why: {
      options: [
        'Blocking on .Result waits on a thread the continuation needs to run on',
        'LoadAsync must be static',
        'Result is not defined on Task',
        'Show cannot take data',
      ],
      answer: 0,
    },
    explain: 'await it. Blocking on async code is the single most common cause of a frozen app.',
  },
  {
    id: 'cs.async.3',
    concepts: ['cs.tasks'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'How do you run two independent async calls at the same time?',
    options: [
      'Start both, then await Task.WhenAll(a, b)',
      'await each one in turn',
      'Wrap them in Task.Run and block',
      'Use a foreach with await inside',
    ],
    answer: [0],
    explain: 'Awaiting in turn makes them sequential. WhenAll is the difference between 200ms and 400ms.',
  },
  {
    id: 'cs.async.4',
    concepts: ['cs.async'],
    difficulty: 5,
    level: 9,
    kind: 'choice',
    prompt: 'Why is `async void` almost always wrong?',
    options: [
      'Nobody can await it, and an exception inside it cannot be caught by the caller',
      'It is slower',
      'It does not compile outside event handlers',
      'It allocates more',
    ],
    answer: [0],
    explain: 'Return Task instead. async void exists for event handlers, and for nothing else.',
  },
  {
    id: 'cs.async.5',
    concepts: ['cs.async', 'cs.methods'],
    difficulty: 4,
    level: 7,
    kind: 'blank',
    prompt: 'Mark this method as asynchronous and give it the right return type.',
    template: '{{0}} {{1}}<string> LoadAsync()\n{\n    await Task.Delay(10);\n    return "done";\n}',
    blanks: [{ accept: ['async'], width: 6 }, { accept: ['Task'], width: 5 }],
    explain: 'async unlocks await; Task<string> is what the caller receives while the work is still running.',
  },
]);
