import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'git.shell',
    title: 'Getting around a terminal',
    blurb: 'Where am I, what is here, and how do I move.',
    concepts: ['git.paths', 'git.files'],
    requires: [],
    level: 'intro',
    tags: ['automation'],
    unit: 'The command line',
  },
  {
    id: 'git.basics',
    title: 'Commits',
    blurb: 'The three places a change can live, and how to move it between them.',
    concepts: ['git.init', 'git.stage', 'git.commit'],
    requires: ['git.shell'],
    level: 'core',
    tags: ['automation', 'apps'],
    unit: 'Everyday Git',
  },
  {
    id: 'git.history',
    title: 'History',
    blurb: 'Reading the log, seeing a diff, and undoing things safely.',
    concepts: ['git.log', 'git.diff', 'git.undo'],
    requires: ['git.basics'],
    level: 'core',
    tags: ['automation'],
    unit: 'Everyday Git',
  },
  {
    id: 'git.branches',
    title: 'Branches and merging',
    blurb: 'Work in parallel, then bring it back together.',
    concepts: ['git.branch', 'git.merge', 'git.conflict'],
    requires: ['git.history'],
    level: 'applied',
    tags: ['automation', 'apps'],
    unit: 'Working with others',
  },
  {
    id: 'git.remote',
    title: 'Remotes',
    blurb: 'Clone, push, pull, and what to do when they disagree.',
    concepts: ['git.clone', 'git.push', 'git.pull'],
    requires: ['git.branches'],
    level: 'applied',
    tags: ['automation', 'apps'],
    unit: 'Working with others',
  },
];

export const gitTrack: Track = {
  id: 'git',
  name: 'Git & the terminal',
  kind: 'tool',
  tagline: 'The safety net under everything else you write',
  blurb:
    'Version control and a command line. Not a language, but the two tools that make every other one survivable — and the thing most self-taught developers skip.',
  lang: 'bash',
  mark: 'Gt',
  tags: ['automation', 'apps', 'web'],
  goals: ['automation', 'apps', 'web', 'curious'],
  slope: 2,
  transfersFrom: [],
  skills,
};

export const gitExercises = forTrack('git', [
  /* ---------------------------------------------------------- git.shell */
  {
    id: 'git.path.1',
    concepts: ['git.paths'],
    difficulty: 1,
    kind: 'terminal',
    prompt: 'Print the directory you are currently in.',
    intro: ['You have just opened a terminal.'],
    cwd: '~',
    accept: ['pwd', 'cd'],
    output: ['/home/you'],
    explain: 'pwd is "print working directory". On Windows PowerShell, pwd works too.',
  },
  {
    id: 'git.path.2',
    concepts: ['git.paths'],
    difficulty: 2,
    kind: 'terminal',
    prompt: 'Move up one directory.',
    cwd: '~/projects/site',
    accept: ['cd ..'],
    output: [],
    explain: 'One dot is here, two dots is the parent. cd with no argument goes home.',
  },
  {
    id: 'git.files.1',
    concepts: ['git.files'],
    difficulty: 1,
    kind: 'terminal',
    prompt: 'List the files in this directory, including hidden ones.',
    cwd: '~/projects/site',
    accept: ['ls -a', 'ls -la', 'ls -al', 'ls --all'],
    output: ['.  ..  .git  index.html  style.css'],
    explain: 'Files starting with a dot are hidden by default — including .git and .gitignore.',
  },
  {
    id: 'git.files.2',
    concepts: ['git.files'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each command to what it does.',
    lang: 'bash',
    pairs: [
      ['mkdir', 'create a directory'],
      ['cat', 'print a file to the screen'],
      ['mv', 'move or rename'],
      ['rm', 'delete, with no recycle bin'],
    ],
    explain: 'rm does not ask twice and there is no undo. rm -rf on the wrong path is a career story.',
  },
  {
    id: 'git.files.3',
    concepts: ['git.files', 'git.paths'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does the tab key do in a terminal?',
    options: [
      'Completes the file or command name you have started typing',
      'Inserts a tab character',
      'Cancels the command',
      'Nothing',
    ],
    answer: [0],
    explain: 'Tab completion is the single biggest speed-up available, and it prevents typos in paths.',
  },

  /* --------------------------------------------------------- git.basics */
  {
    id: 'git.init.1',
    concepts: ['git.init'],
    difficulty: 2,
    kind: 'terminal',
    prompt: 'Turn the current folder into a Git repository.',
    cwd: '~/projects/site',
    accept: ['git init'],
    output: ['Initialized empty Git repository in ~/projects/site/.git/'],
    explain: 'Everything Git knows lives in the .git folder. Delete it and the folder is ordinary again.',
  },
  {
    id: 'git.stage.1',
    concepts: ['git.stage'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each place a change can live to what it means.',
    pairs: [
      ['Working directory', 'the files as they are on disk right now'],
      ['Staging area', 'the changes you have chosen for the next commit'],
      ['Repository', 'the commits already recorded'],
    ],
    explain: 'The staging area is why you can commit half your changes and leave the rest for later.',
  },
  {
    id: 'git.stage.2',
    concepts: ['git.stage'],
    difficulty: 2,
    kind: 'terminal',
    prompt: 'Stage every changed file for the next commit.',
    cwd: '~/projects/site',
    intro: ['modified: index.html', 'modified: style.css'],
    accept: ['git add .', 'git add -A', 'git add --all'],
    output: [],
    explain: 'git add . stages everything under the current directory. Check git status first, always.',
  },
  {
    id: 'git.stage.3',
    concepts: ['git.stage'],
    difficulty: 2,
    kind: 'terminal',
    prompt: 'See which files have changed and which are staged.',
    cwd: '~/projects/site',
    accept: ['git status', 'git status -s', 'git status --short'],
    output: ['On branch main', 'Changes not staged for commit:', '  modified: index.html'],
    explain: 'git status is the command to run when you are unsure. It also tells you how to undo things.',
  },
  {
    id: 'git.commit.1',
    concepts: ['git.commit'],
    difficulty: 3,
    kind: 'terminal',
    prompt: 'Commit the staged changes with the message "Add contact page".',
    cwd: '~/projects/site',
    accept: ['git commit -m "Add contact page"', "git commit -m 'Add contact page'"],
    output: ['[main 4f2a1c9] Add contact page'],
    explain: 'Write the message in the imperative: "Add contact page", not "Added" or "Adding".',
  },
  {
    id: 'git.commit.2',
    concepts: ['git.commit'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What makes a good commit message?',
    options: [
      'A short imperative summary, and a body explaining why if it is not obvious',
      'The list of files changed',
      '"fix"',
      'The date and your name',
    ],
    answer: [0],
    explain: 'Git already records what changed and who by. The message is the only place "why" can live.',
  },

  /* -------------------------------------------------------- git.history */
  {
    id: 'git.log.1',
    concepts: ['git.log'],
    difficulty: 2,
    kind: 'terminal',
    prompt: 'Show the commit history one line per commit.',
    cwd: '~/projects/site',
    accept: ['git log --oneline', 'git log --oneline --graph'],
    output: ['4f2a1c9 Add contact page', '8b3e7d1 Initial commit'],
    explain: 'Add --graph --all to see how branches diverged. It is the fastest way to picture a repository.',
  },
  {
    id: 'git.diff.1',
    concepts: ['git.diff'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each diff command to what it shows.',
    lang: 'bash',
    pairs: [
      ['git diff', 'changes not yet staged'],
      ['git diff --staged', 'changes staged for the next commit'],
      ['git diff HEAD', 'everything since the last commit'],
    ],
    explain: 'Reading your own diff before committing catches most of the mistakes you would otherwise push.',
  },
  {
    id: 'git.undo.1',
    concepts: ['git.undo'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each undo to what it does.',
    lang: 'bash',
    pairs: [
      ['git restore FILE', 'throw away unstaged changes to a file'],
      ['git restore --staged FILE', 'unstage it but keep the changes'],
      ['git commit --amend', 'rewrite the most recent commit'],
      ['git revert COMMIT', 'add a new commit that undoes an old one'],
    ],
    explain: 'revert is safe on shared branches; amend and reset rewrite history and need care once pushed.',
  },
  {
    id: 'git.undo.2',
    concepts: ['git.undo'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'You committed a password by mistake and pushed it. What is the honest first step?',
    options: [
      'Rotate the credential — it must be treated as compromised — then clean the history',
      'Delete the commit and hope',
      'Force-push over it and say nothing',
      'Rename the file',
    ],
    answer: [0],
    explain: 'Anything pushed has been fetched, mirrored and logged. History rewriting alone does not un-leak it.',
  },
  {
    id: 'git.undo.3',
    concepts: ['git.undo', 'git.log'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What does git reflog give you?',
    options: [
      'A log of everywhere HEAD has been, including commits no branch points at any more',
      'The remote history',
      'A list of conflicts',
      'File-level history',
    ],
    answer: [0],
    explain: 'It is the undo button for the undo button. A "lost" commit after a bad reset is almost always in there.',
  },

  /* ------------------------------------------------------- git.branches */
  {
    id: 'git.br.1',
    concepts: ['git.branch'],
    difficulty: 3,
    kind: 'terminal',
    prompt: 'Create a branch called feature/login and switch to it.',
    cwd: '~/projects/site',
    accept: ['git switch -c feature/login', 'git checkout -b feature/login'],
    output: ["Switched to a new branch 'feature/login'"],
    explain: 'switch is the newer, clearer command; checkout still works and does several unrelated jobs.',
  },
  {
    id: 'git.br.2',
    concepts: ['git.branch'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What is a branch, technically?',
    options: [
      'A movable pointer to a commit',
      'A copy of the whole project',
      'A separate folder',
      'A remote server',
    ],
    answer: [0],
    explain: 'Branches are almost free, which is why the workflow encourages making one for every change.',
  },
  {
    id: 'git.merge.1',
    concepts: ['git.merge'],
    difficulty: 4,
    kind: 'order',
    prompt: 'Order the steps to merge a finished feature into main.',
    lang: 'bash',
    lines: ['git switch main', 'git pull', 'git merge feature/login', 'git push'],
    explain: 'Pull before merging, or you will merge into a stale main and have to do it twice.',
  },
  {
    id: 'git.conf.1',
    concepts: ['git.conflict'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What do <<<<<<<, ======= and >>>>>>> mean in a file?',
    options: [
      'A conflict: your version, a separator, and theirs — you must choose and delete the markers',
      'A syntax error',
      'A comment',
      'Git corrupted the file',
    ],
    answer: [0],
    explain: 'Committing the markers by accident is common. Search for <<<<<<< before you commit a merge.',
  },
  {
    id: 'git.conf.2',
    concepts: ['git.conflict', 'git.merge'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'How do you make conflicts rarer?',
    options: [
      'Small branches, merged often, from an up-to-date base',
      'One large branch per release',
      'Avoid branches',
      'Commit less often',
    ],
    answer: [0],
    explain: 'A conflict is proportional to how long two people worked apart. Time is the real variable.',
  },

  /* --------------------------------------------------------- git.remote */
  {
    id: 'git.clone.1',
    concepts: ['git.clone'],
    difficulty: 2,
    kind: 'terminal',
    prompt: 'Copy the repository at https://github.com/you/site.git onto this machine.',
    cwd: '~/projects',
    accept: ['git clone https://github.com/you/site.git'],
    output: ["Cloning into 'site'...", 'done.'],
    explain: 'A clone comes with the full history, so log, diff and branch all work with no network.',
  },
  {
    id: 'git.push.1',
    concepts: ['git.push'],
    difficulty: 3,
    kind: 'terminal',
    prompt: 'Push the current branch and set it to track the remote.',
    cwd: '~/projects/site',
    accept: ['git push -u origin feature/login', 'git push --set-upstream origin feature/login'],
    output: ["branch 'feature/login' set up to track 'origin/feature/login'."],
    explain: 'The -u only matters the first time. After that, plain git push and git pull know where to go.',
  },
  {
    id: 'git.pull.1',
    concepts: ['git.pull'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is the difference between fetch and pull?',
    options: [
      'fetch downloads without changing your files; pull is fetch plus merge',
      'pull is read-only',
      'fetch works only on the first clone',
      'They are the same',
    ],
    answer: [0],
    explain: 'git fetch then git log HEAD..origin/main lets you see what is coming before you take it.',
  },
  {
    id: 'git.pull.2',
    concepts: ['git.pull', 'git.push'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Your push is rejected as non-fast-forward. What happened?',
    options: [
      'The remote has commits you do not have; pull first, then push',
      'Your branch is protected',
      'The file is too large',
      'You are offline',
    ],
    answer: [0],
    explain: 'Force-pushing here would delete somebody else s work. Pull, resolve, push.',
  },
  {
    id: 'git.remote.1',
    concepts: ['git.push', 'git.clone'],
    difficulty: 3,
    kind: 'terminal',
    prompt: 'Show the remote URLs this repository is connected to.',
    cwd: '~/projects/site',
    accept: ['git remote -v', 'git remote --verbose'],
    output: ['origin  https://github.com/you/site.git (fetch)', 'origin  https://github.com/you/site.git (push)'],
    explain: 'origin is just a nickname for a URL. A repository can have as many remotes as you like.',
  },
]);
