import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const gitExtraSkills: Skill[] = [
  {
    id: 'git.rewrite',
    title: 'Rebase, stash and tags',
    blurb: 'Tidying history without losing work, and marking the versions that matter.',
    concepts: ['git.rebase', 'git.stash', 'git.tags'],
    requires: ['git.branches'],
    level: 'advanced',
    tags: ['automation'],
    unit: 'Working with others',
  },
  {
    id: 'git.team',
    title: 'Pull requests and review',
    blurb: 'How work actually reaches a shared branch, and what a good review looks at.',
    concepts: ['git.pr', 'git.review', 'git.hooks'],
    requires: ['git.remote'],
    level: 'applied',
    tags: ['automation'],
    unit: 'Working with others',
  },
];

export const gitExtra = forTrack('git', [
  {
    id: 'git.path.x1',
    concepts: ['git.paths'],
    difficulty: 1,
    level: 1,
    kind: 'terminal',
    prompt: 'Show which directory you are in.',
    intro: ['~/projects $'],
    cwd: '~/projects',
    accept: ['pwd'],
    output: ['/home/you/projects'],
    explain: 'pwd — print working directory. The first command to reach for when you are lost.',
  },
  {
    id: 'git.path.x2',
    concepts: ['git.paths'],
    difficulty: 1,
    level: 1,
    kind: 'match',
    prompt: 'Match each path to what it means.',
    pairs: [
      ['.', 'Here'],
      ['..', 'One level up'],
      ['~', 'Your home directory'],
      ['/', 'The root of the filesystem'],
    ],
    explain: 'cd .. climbs, cd ~ goes home, cd - goes back to where you just were.',
  },
  {
    id: 'git.file.x1',
    concepts: ['git.files'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which command lists the hidden files as well as the visible ones?',
    options: ['ls -a', 'ls', 'ls -l', 'dir'],
    answer: [0],
    explain: 'Anything starting with a dot is hidden — which is where .git and your config live.',
  },
  {
    id: 'git.init.x1',
    concepts: ['git.init'],
    difficulty: 1,
    level: 1,
    kind: 'terminal',
    prompt: 'Start tracking this folder with Git.',
    intro: ['~/app $ ls', 'index.html'],
    cwd: '~/app',
    accept: ['git init'],
    output: ['Initialized empty Git repository in ~/app/.git/'],
    explain: 'Everything Git knows lives in that .git folder. Delete it and the history is gone.',
  },
  {
    id: 'git.stage.x1',
    concepts: ['git.stage'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What does the staging area let you do?',
    options: [
      'Commit some of your changes and leave the rest for the next commit',
      'Undo a commit',
      'Store files on the remote',
      'Compress the repository',
    ],
    answer: [0],
    explain: 'git add -p stages hunks rather than whole files, which is how you keep commits small.',
  },
  {
    id: 'git.stage.x2',
    concepts: ['git.stage'],
    difficulty: 2,
    level: 2,
    kind: 'assemble',
    prompt: 'Build the command that stages just one file.',
    answer: ['git', 'add', 'style.css'],
    distractors: ['commit', '-m'],
    explain: 'git add . stages this folder down; naming the file stages only that one.',
  },
  {
    id: 'git.commit.x1',
    concepts: ['git.commit'],
    difficulty: 2,
    level: 2,
    kind: 'terminal',
    prompt: 'Commit the staged changes with the message "Add stylesheet".',
    intro: ['~/app $ git status --short', 'A  style.css'],
    cwd: '~/app',
    accept: ['git commit -m "Add stylesheet"', "git commit -m 'Add stylesheet'"],
    output: ['[main 4f2a1c9] Add stylesheet', ' 1 file changed, 12 insertions(+)'],
    explain: 'Write the message in the imperative: it finishes the sentence "this commit will…".',
  },
  {
    id: 'git.commit.x2',
    concepts: ['git.commit'],
    difficulty: 3,
    level: 3,
    kind: 'choice',
    prompt: 'What makes a good commit message subject line?',
    options: [
      'One short imperative line saying what changes, with the why in the body',
      'The list of files touched',
      'The ticket number alone',
      '"fixes"',
    ],
    answer: [0],
    explain: 'The diff already says what changed. The message is for the reasoning that the diff cannot show.',
  },
  {
    id: 'git.log.x1',
    concepts: ['git.log'],
    difficulty: 2,
    level: 3,
    kind: 'terminal',
    prompt: 'Show the history as one line per commit.',
    intro: ['~/app $'],
    cwd: '~/app',
    accept: ['git log --oneline'],
    output: ['4f2a1c9 Add stylesheet', '9c1b204 First commit'],
    explain: '--oneline --graph --all is the one worth an alias; it draws the branch structure.',
  },
  {
    id: 'git.diff.x1',
    concepts: ['git.diff'],
    difficulty: 3,
    level: 3,
    kind: 'match',
    prompt: 'Match each command to what it shows.',
    pairs: [
      ['git diff', 'Unstaged changes'],
      ['git diff --staged', 'What is about to be committed'],
      ['git diff HEAD', 'Everything since the last commit'],
      ['git diff main', 'How this branch differs from main'],
    ],
    explain: 'Bare git diff showing nothing after git add is the usual "why is it empty" moment.',
  },

  /* --------------------------------------------------------- git.rewrite */
  {
    id: 'git.rw.1',
    concepts: ['git.stash'],
    difficulty: 3,
    level: 5,
    kind: 'terminal',
    prompt: 'Put your half-finished work aside so you can switch branch.',
    intro: ['~/app $ git status --short', ' M src/app.ts'],
    cwd: '~/app',
    accept: ['git stash', 'git stash push', 'git stash save'],
    output: ['Saved working directory and index state WIP on main: 4f2a1c9 Add stylesheet'],
    explain: 'git stash pop brings it back. Stashes are a stack, and forgetting them is a rite of passage.',
  },
  {
    id: 'git.rw.2',
    concepts: ['git.rebase'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What does rebasing your branch onto main do?',
    options: [
      'Replays your commits on top of main, giving new commit ids',
      'Merges main into your branch',
      'Deletes main',
      'Squashes your branch into one commit',
    ],
    answer: [0],
    explain: 'New ids are why rebasing a branch other people have pulled is antisocial.',
  },
  {
    id: 'git.rw.3',
    concepts: ['git.rebase'],
    difficulty: 5,
    level: 7,
    kind: 'choice',
    prompt: 'When is force-pushing acceptable?',
    options: [
      'On your own branch, with --force-with-lease so you cannot clobber someone else’s push',
      'Never',
      'On any branch, as long as CI passes',
      'On main, to tidy history',
    ],
    answer: [0],
    explain: '--force-with-lease refuses if the remote moved since you last fetched. Plain --force does not ask.',
  },
  {
    id: 'git.rw.4',
    concepts: ['git.tags'],
    difficulty: 3,
    level: 5,
    kind: 'terminal',
    estSeconds: 40,
    prompt: 'Mark this commit as version 1.0.0 with an annotated tag.',
    intro: ['~/app $'],
    cwd: '~/app',
    accept: ['git tag -a v1.0.0 -m "v1.0.0"', 'git tag -a v1.0.0 -m "1.0.0"'],
    output: ['~/app $'],
    explain: 'Annotated tags carry an author, date and message. Lightweight tags are just a pointer.',
  },

  /* ------------------------------------------------------------ git.team */
  {
    id: 'git.team.1',
    concepts: ['git.pr'],
    difficulty: 3,
    level: 5,
    kind: 'order',
    prompt: 'Put the usual pull request flow in order.',
    lines: [
      'git switch -c fix/typo',
      'git commit -m "Fix the typo"',
      'git push -u origin fix/typo',
      'Open a pull request',
      'Address review comments',
      'Merge',
    ],
    explain: 'Branch, commit, push, propose. The branch is cheap; the conversation is the valuable part.',
  },
  {
    id: 'git.team.2',
    concepts: ['git.review'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What should a reviewer look at first?',
    options: [
      'Whether the change does what it claims, and what it might break',
      'Formatting',
      'Variable names',
      'The number of lines changed',
    ],
    answer: [0],
    explain: 'Style is a linter’s job. A human should spend their attention on behaviour and risk.',
  },
  {
    id: 'git.team.3',
    concepts: ['git.pr'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'Your branch cannot merge: someone else changed the same lines. What do you do?',
    options: [
      'Bring main into your branch, resolve the conflict, and push',
      'Force push over main',
      'Delete and recreate the branch',
      'Ask them to revert',
    ],
    answer: [0],
    explain: 'Merge or rebase, both fine. What matters is that the resolution happens on your branch, not theirs.',
  },
  {
    id: 'git.team.4',
    concepts: ['git.hooks'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What is a pre-commit hook good for?',
    options: [
      'Fast local checks — formatting, lint — that keep noise out of review',
      'Running the whole test suite',
      'Deploying',
      'Signing commits automatically',
    ],
    answer: [0],
    explain: 'Keep hooks fast. A hook that takes thirty seconds is a hook people learn to skip with --no-verify.',
  },
  {
    id: 'git.team.5',
    concepts: ['git.review', 'git.undo'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'A bad commit is already on main. What is the safest fix?',
    options: [
      'git revert it — a new commit that undoes it, leaving history intact',
      'git reset --hard and force push',
      'Delete the branch',
      'Amend the commit',
    ],
    answer: [0],
    explain: 'Never rewrite a shared branch. Revert is public, reversible and does not break anyone’s clone.',
  },
]);
