import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const goExtraSkills: Skill[] = [
  {
    id: 'go.types2',
    title: 'Structs, methods and interfaces',
    blurb: 'Your own types, and the quietest interface system in any mainstream language.',
    concepts: ['go.structs', 'go.methods', 'go.interfaces'],
    requires: ['go.funcs'],
    level: 'applied',
    tags: ['systems', 'apps'],
    unit: 'Your own types',
  },
  {
    id: 'go.tooling',
    title: 'Modules and testing',
    blurb: 'go mod, go test, and the tooling that ships in the box.',
    concepts: ['go.modules', 'go.test'],
    requires: ['go.first'],
    level: 'applied',
    tags: ['systems'],
    unit: 'Toolchain',
  },
];

export const goExtra = forTrack('go', [
  {
    id: 'go.main.x1',
    concepts: ['go.main'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which package must an executable Go program declare?',
    options: ['package main', 'package app', 'package run', 'No package line is needed'],
    answer: [0],
    explain: 'package main plus func main() is what makes a binary rather than a library.',
  },
  {
    id: 'go.fmt.x1',
    concepts: ['go.fmt'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Print hello with a newline.',
    template: 'fmt.{{0}}("hello")',
    blanks: [{ accept: ['Println'], width: 8 }],
    explain: 'Println adds the newline; Printf takes a format string; Print adds nothing.',
  },
  {
    id: 'go.fmt.x2',
    concepts: ['go.fmt'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'fmt.Printf("%d-%s\\n", 3, "x")',
    options: ['3-x', '%d-%s', '3 x', 'an error'],
    answer: 0,
    explain: '%d for integers, %s for strings, %v when you just want something sensible.',
  },
  {
    id: 'go.syn.x1',
    concepts: ['go.syntax'],
    difficulty: 2,
    level: 2,
    kind: 'bug',
    prompt: 'Which line will not compile?',
    code: 'package main\n\nimport "fmt"\nimport "os"\n\nfunc main() {\n    fmt.Println("hi")\n}',
    buggyLine: 4,
    why: {
      options: [
        'os is imported but never used, which Go treats as an error',
        'Two imports are not allowed',
        'os does not exist',
        'main must take arguments',
      ],
      answer: 0,
    },
    explain: 'Unused imports and unused local variables are compile errors. It keeps files honest.',
  },
  {
    id: 'go.vars.x1',
    concepts: ['go.vars'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What does `count := 0` do?',
    options: [
      'Declares count and infers its type from the value',
      'Assigns to an existing count',
      'Declares a constant',
      'Declares a package-level variable',
    ],
    answer: [0],
    explain: 'The short form only works inside a function. At package level you need var.',
  },
  {
    id: 'go.zero.x1',
    concepts: ['go.zero'],
    difficulty: 2,
    level: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'var s []int\nfmt.Println(s == nil, len(s))',
    options: ['true 0', 'false 0', 'true 1', 'a panic'],
    answer: 0,
    explain: 'A nil slice is not a broken one: len, range and append all work on it, which is why you rarely need make() up front.',
  },
  {
    id: 'go.if.x1',
    concepts: ['go.if'],
    difficulty: 2,
    level: 3,
    kind: 'order',
    prompt: 'Check an error the idiomatic way.',
    lines: ['data, err := load()', 'if err != nil {', '    return err', '}', 'use(data)'],
    explain: 'Handle the error and return early. Nested happy paths are what this style avoids.',
  },
  {
    id: 'go.for.x1',
    concepts: ['go.for'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for i := 0; i < 3; i++ {\n    fmt.Print(i)\n}',
    options: ['012', '123', '0 1 2', '3'],
    answer: 0,
    explain: 'Go has exactly one loop keyword. while, do-while and foreach are all spelled for.',
  },
  {
    id: 'go.range.x1',
    concepts: ['go.range'],
    difficulty: 3,
    level: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'xs := []string{"a", "b"}\nfor i, v := range xs {\n    fmt.Print(i, v)\n}',
    options: ['0a1b', 'ab', '01', 'a0b1'],
    answer: 0,
    explain: 'range gives index first, value second. Ignore the index with an underscore.',
  },
  {
    id: 'go.slice.x1',
    concepts: ['go.slices'],
    difficulty: 3,
    level: 4,
    kind: 'blank',
    prompt: 'Add an item to the slice.',
    template: 'items = {{0}}(items, "new")',
    blanks: [{ accept: ['append'], width: 7 }],
    explain: 'append may return a different slice header, so you must assign the result back.',
  },

  /* ---------------------------------------------------------- go.types2 */
  {
    id: 'go.st.1',
    concepts: ['go.structs'],
    difficulty: 3,
    level: 5,
    kind: 'order',
    prompt: 'Declare a struct and make one.',
    lines: ['type Point struct {', '    X int', '    Y int', '}', '', 'p := Point{X: 1, Y: 2}'],
    explain: 'Capitalised field names are exported. Lowercase ones are private to the package.',
  },
  {
    id: 'go.st.2',
    concepts: ['go.methods'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'When should a method take a pointer receiver?',
    options: [
      'When it modifies the value, or the struct is large',
      'Always',
      'Only for interfaces',
      'Never — Go copies are free',
    ],
    answer: [0],
    explain: 'A value receiver gets a copy, so mutations are lost. Keep one style per type.',
  },
  {
    id: 'go.st.3',
    concepts: ['go.interfaces'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'How does a type implement an interface in Go?',
    options: [
      'By having the methods — there is nothing to declare',
      'With an implements keyword',
      'By embedding the interface',
      'By registering it at init time',
    ],
    answer: [0],
    explain: 'Structural, not nominal. Interfaces belong to the consumer, which is why they are usually tiny.',
  },
  {
    id: 'go.st.4',
    concepts: ['go.interfaces'],
    difficulty: 5,
    level: 8,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'var w io.Writer\nfmt.Println(w == nil)',
    options: ['true', 'false', 'an error', 'nil'],
    answer: 0,
    explain: 'An interface holding a nil *pointer* is not nil — but this one holds nothing at all, so it is.',
  },
  {
    id: 'go.st.5',
    concepts: ['go.structs', 'go.methods'],
    difficulty: 4,
    level: 7,
    kind: 'write',
    prompt: 'Define a Rect with Width and Height and a method Area, then print the area of a 3x4 rectangle.',
    runLang: 'go',
    starter:
      'package main\n\nimport "fmt"\n\n// define Rect and Area here\n\nfunc main() {\n\tr := Rect{Width: 3, Height: 4}\n\tfmt.Println(r.Area())\n}\n',
    solution:
      'package main\n\nimport "fmt"\n\ntype Rect struct {\n\tWidth  int\n\tHeight int\n}\n\nfunc (r Rect) Area() int {\n\treturn r.Width * r.Height\n}\n\nfunc main() {\n\tr := Rect{Width: 3, Height: 4}\n\tfmt.Println(r.Area())\n}\n',
    tests: [{ name: 'area of 3x4', expect: '12' }],
    mustContain: [{ pattern: 'func (', label: 'define a method' }],
    explain: 'The receiver goes before the method name. A value receiver is right here — Area changes nothing.',
  },

  /* --------------------------------------------------------- go.tooling */
  {
    id: 'go.tool.1',
    concepts: ['go.modules'],
    difficulty: 3,
    level: 5,
    kind: 'terminal',
    prompt: 'Start a module for a project hosted at example.com/app.',
    intro: ['~/app $ ls', 'main.go'],
    cwd: '~/app',
    accept: ['go mod init example.com/app'],
    output: ['go: creating new go.mod: module example.com/app'],
    explain: 'The module path is also the import path, which is why it looks like a URL.',
  },
  {
    id: 'go.tool.2',
    concepts: ['go.modules'],
    difficulty: 4,
    level: 6,
    kind: 'match',
    prompt: 'Match each file or command to what it does.',
    pairs: [
      ['go.mod', 'Module path and dependency versions'],
      ['go.sum', 'Checksums for what was downloaded'],
      ['go mod tidy', 'Add what is used, drop what is not'],
      ['go vet', 'Report suspicious constructs'],
    ],
    explain: 'go mod tidy before committing is the Go equivalent of tidying your imports.',
  },
  {
    id: 'go.tool.3',
    concepts: ['go.test'],
    difficulty: 4,
    level: 6,
    kind: 'order',
    prompt: 'Write a test the toolchain will find.',
    lines: ['func TestAdd(t *testing.T) {', '    got := Add(2, 2)', '    if got != 4 {', '        t.Errorf("got %d, want 4", got)', '    }', '}'],
    explain: 'The name must start with Test and take *testing.T. There is no assertion library in the box.',
  },
  {
    id: 'go.tool.4',
    concepts: ['go.test'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What is a table-driven test?',
    options: [
      'One test function looping over a slice of cases, each with a name',
      'A test that reads a CSV file',
      'A test generated by the compiler',
      'A benchmark',
    ],
    answer: [0],
    explain: 'It is the house style: adding a case is one line, and t.Run gives each its own name.',
  },
  {
    id: 'go.tool.5',
    concepts: ['go.modules'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'Why does Go require a major version suffix in the import path, like /v2?',
    options: [
      'So two incompatible major versions can coexist in one build',
      'To make the path unique',
      'For documentation only',
      'Because tags cannot be reused',
    ],
    answer: [0],
    explain: 'Import compatibility is a rule, not a convention: v1 and v2 are different packages.',
  },
]);
