import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'go.first',
    title: 'First program',
    blurb: 'package main, imports, and a compiler that refuses unused variables.',
    concepts: ['go.main', 'go.fmt', 'go.syntax'],
    requires: [],
    level: 'intro',
    tags: ['systems', 'web'],
    unit: 'Getting started',
  },
  {
    id: 'go.values',
    title: 'Values and types',
    blurb: 'Declarations, zero values, and the short form you will use everywhere.',
    concepts: ['go.vars', 'go.types', 'go.zero'],
    requires: ['go.first'],
    level: 'core',
    tags: ['systems'],
    unit: 'Getting started',
  },
  {
    id: 'go.control',
    title: 'Control flow',
    blurb: 'One loop keyword, if with an init statement, and switch without break.',
    concepts: ['go.if', 'go.for', 'go.switch'],
    requires: ['go.values'],
    level: 'core',
    tags: ['systems', 'interviews'],
    unit: 'Control flow',
  },
  {
    id: 'go.collections',
    title: 'Slices and maps',
    blurb: 'The two containers you need, and the append that surprises people.',
    concepts: ['go.slices', 'go.maps', 'go.range'],
    requires: ['go.control'],
    level: 'core',
    tags: ['systems', 'data'],
    unit: 'Data',
  },
  {
    id: 'go.funcs',
    title: 'Functions and errors',
    blurb: 'Multiple returns, the error value, and defer.',
    concepts: ['go.funcs', 'go.errors', 'go.defer'],
    requires: ['go.control'],
    level: 'applied',
    tags: ['systems', 'web'],
    unit: 'Structure',
  },
  {
    id: 'go.concurrency',
    title: 'Goroutines and channels',
    blurb: 'Cheap concurrency, and communicating instead of sharing.',
    concepts: ['go.goroutines', 'go.channels'],
    requires: ['go.funcs'],
    level: 'advanced',
    tags: ['systems'],
    unit: 'Concurrency',
  },
];

export const goTrack: Track = {
  id: 'go',
  name: 'Go',
  kind: 'language',
  tagline: 'Small language, fast builds, boring in the best way',
  blurb:
    'Deliberately few features, compiled to a single binary, and built for servers and command-line tools. You can hold the whole language in your head.',
  lang: 'go',
  runLang: 'go',
  mark: 'Go',
  tags: ['systems', 'web', 'apps'],
  goals: ['systems', 'web', 'apps'],
  slope: 3,
  transfersFrom: ['cpp', 'rust', 'python'],
  skills,
};

export const goExercises = forTrack('go', [
  /* ------------------------------------------------------------ go.first */
  {
    id: 'go.main.1',
    concepts: ['go.main', 'go.fmt'],
    difficulty: 2,
    kind: 'order',
    prompt: 'Order the smallest Go program.',
    lines: ['package main', '', 'import "fmt"', '', 'func main() {', '\tfmt.Println("Hello, Go!")', '}'],
    explain: 'Every file starts with its package. An executable needs package main and a func main.',
  },
  {
    id: 'go.fmt.1',
    concepts: ['go.fmt'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each fmt function to what it does.',
    pairs: [
      ['Println', 'prints its arguments and a newline'],
      ['Printf', 'prints using a format string'],
      ['Sprintf', 'returns the formatted string instead of printing'],
    ],
    explain: 'The S prefix means "give me the string". The same pattern runs through the standard library.',
  },
  {
    id: 'go.syn.1',
    concepts: ['go.syntax'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does the compiler say?',
    code: 'func main() {\n\tcount := 5\n\tfmt.Println("hi")\n}',
    options: ['Prints hi', 'count declared and not used', 'Prints 5', 'Nothing at all'],
    answer: 1,
    explain: 'An unused variable is a compile error in Go, not a warning. Same for an unused import.',
  },
  {
    id: 'go.syn.2',
    concepts: ['go.syntax'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'Why does Go put the opening brace on the same line?',
    options: [
      'Style preference',
      'Automatic semicolon insertion breaks the code if you put it on the next line',
      'The compiler is faster',
      'It does not matter',
    ],
    answer: [1],
    explain: 'The lexer inserts a semicolon at the end of the line, so a lone brace on the next line is a syntax error.',
  },
  {
    id: 'go.first.write.1',
    concepts: ['go.main', 'go.fmt'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Print "Hello from Go".',
    runLang: 'go',
    starter: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t\n}',
    solution: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello from Go")\n}',
    tests: [{ name: 'greets', expect: 'Hello from Go' }],
    explain: 'fmt has to be imported, and Go will refuse to build if you import it and never use it.',
  },

  /* ----------------------------------------------------------- go.values */
  {
    id: 'go.var.1',
    concepts: ['go.vars'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Declare and initialise count in the short form.',
    template: 'count {{0}} 0',
    blanks: [{ accept: [':='], width: 3 }],
    explain: ':= declares and assigns in one step, inferring the type. It only works inside a function.',
  },
  {
    id: 'go.var.2',
    concepts: ['go.vars', 'go.types'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'When must you use `var` rather than `:=`?',
    options: [
      'At package level, or when you want the zero value without assigning',
      'Never',
      'For integers only',
      'Inside loops',
    ],
    answer: [0],
    explain: '`var buf []byte` gives you a nil slice ready to append to, with nothing to initialise.',
  },
  {
    id: 'go.zero.1',
    concepts: ['go.zero'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each type to its zero value.',
    pairs: [
      ['int', '0'],
      ['string', '"" (empty)'],
      ['bool', 'false'],
      ['a slice or map', 'nil'],
    ],
    explain: 'Nothing in Go is ever uninitialised, which removes an entire family of bugs.',
  },
  {
    id: 'go.type.1',
    concepts: ['go.types'],
    difficulty: 3,
    kind: 'bug',
    prompt: 'Which line does the compiler reject?',
    code: 'var a int = 5\nvar b float64 = 2.0\nfmt.Println(a * b)',
    buggyLine: 3,
    why: {
      options: [
        'Go never converts numeric types implicitly',
        'b should be a float32',
        'Println takes only one argument',
      ],
      answer: 0,
    },
    explain: 'You must write float64(a) * b. Go would rather be verbose than silently lose precision.',
  },

  /* ---------------------------------------------------------- go.control */
  {
    id: 'go.if.1',
    concepts: ['go.if'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What is the scope of err here?',
    code: 'if err := doWork(); err != nil {\n\treturn err\n}',
    options: [
      'The whole function',
      'Only the if and its else branches',
      'The package',
      'It is not valid Go',
    ],
    answer: 1,
    explain: 'The init statement keeps short-lived values out of the surrounding scope. It is the idiomatic error check.',
  },
  {
    id: 'go.for.1',
    concepts: ['go.for'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'How many looping keywords does Go have?',
    options: ['One: for', 'Two: for and while', 'Three', 'Four'],
    answer: [0],
    explain: '`for cond {}` is a while loop, and `for {}` loops forever. One keyword covers all of it.',
  },
  {
    id: 'go.for.2',
    concepts: ['go.for'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Loop from 0 up to 4.',
    template: 'for i := 0; i {{0}} 5; i++ {\n\tfmt.Println(i)\n}',
    blanks: [{ accept: ['<'], width: 3 }],
    explain: 'No brackets round the clause, and braces are always required even for one line.',
  },
  {
    id: 'go.switch.1',
    concepts: ['go.switch'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is different about Go switch compared to C?',
    options: [
      'Cases do not fall through, so break is unnecessary',
      'It only works on integers',
      'It requires a default',
      'It cannot have multiple values per case',
    ],
    answer: [0],
    explain: 'Use the fallthrough keyword when you genuinely want the C behaviour, which is rare.',
  },
  {
    id: 'go.control.write.1',
    concepts: ['go.for', 'go.if'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Print the numbers 1 to 10 that are divisible by 3, one per line.',
    runLang: 'go',
    starter: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t\n}',
    solution:
      'package main\n\nimport "fmt"\n\nfunc main() {\n\tfor i := 1; i <= 10; i++ {\n\t\tif i%3 == 0 {\n\t\t\tfmt.Println(i)\n\t\t}\n\t}\n}',
    tests: [{ name: 'multiples of three', expect: '3\n6\n9' }],
    explain: 'Go has no ternary and no while. One for, one if, and that is the whole toolbox.',
  },

  /* ------------------------------------------------------ go.collections */
  {
    id: 'go.slice.1',
    concepts: ['go.slices'],
    difficulty: 4,
    kind: 'assemble',
    prompt: 'Build the line that adds 4 to the slice xs.',
    answer: ['xs', '=', 'append', '(', 'xs', ',', '4', ')'],
    distractors: ['push', 'xs.append', 'add'],
    explain: 'append may return a new backing array, so you must assign the result back. Forgetting is the classic Go bug.',
  },
  {
    id: 'go.slice.2',
    concepts: ['go.slices'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is the difference between an array and a slice?',
    options: [
      'An array has a fixed length that is part of its type; a slice is a view that can grow',
      'Slices can only hold strings',
      'Arrays are faster to append to',
      'Nothing',
    ],
    answer: [0],
    explain: '[3]int and [4]int are different types. You will use slices for essentially everything.',
  },
  {
    id: 'go.map.1',
    concepts: ['go.maps'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'ages := map[string]int{"ada": 36}\nv, ok := ages["alan"]\nfmt.Println(v, ok)',
    options: ['0 false', 'nil false', 'panic', '0 true'],
    answer: 0,
    explain: 'Reading a missing key gives the zero value. The second return tells you whether it was really there.',
  },
  {
    id: 'go.map.2',
    concepts: ['go.maps'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This panics at runtime. Which line?',
    code: 'var counts map[string]int\ncounts["a"] = 1\nfmt.Println(counts)',
    buggyLine: 2,
    why: {
      options: [
        'A nil map can be read but not written; it needs make(map[string]int)',
        'The key should be a rune',
        'counts must be a pointer',
      ],
      answer: 0,
    },
    explain: 'Declaring a map gives you nil. make() or a literal gives you one you can write to.',
  },
  {
    id: 'go.range.1',
    concepts: ['go.range'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What are i and v here?',
    code: 'for i, v := range []string{"a", "b"} {\n\tfmt.Println(i, v)\n}',
    options: ['index and value', 'value and index', 'both values', 'key and error'],
    answer: 0,
    explain: 'Over a map it is key and value instead. Use _ to discard whichever half you do not need.',
  },

  /* ------------------------------------------------------------ go.funcs */
  {
    id: 'go.fn.1',
    concepts: ['go.funcs'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Declare a function taking an int and returning an int.',
    template: '{{0}} double(n int) int {\n\treturn n * 2\n}',
    blanks: [{ accept: ['func'], width: 5 }],
    explain: 'Types come after names in Go, which reads oddly for a day and then reads better than the alternative.',
  },
  {
    id: 'go.err.1',
    concepts: ['go.errors'],
    difficulty: 4,
    kind: 'order',
    prompt: 'Order the idiomatic error check.',
    lines: ['data, err := load()', 'if err != nil {', '\treturn err', '}', 'fmt.Println(data)'],
    explain: 'Handle the error immediately and return early. The happy path stays at the left margin.',
  },
  {
    id: 'go.err.2',
    concepts: ['go.errors', 'go.funcs'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why does Go return errors instead of throwing exceptions?',
    options: [
      'Every call site has to acknowledge failure, so nothing fails invisibly',
      'It is faster',
      'Exceptions are impossible to implement',
      'For backwards compatibility',
    ],
    answer: [0],
    explain: 'It is verbose on purpose. panic exists, but is for programmer error, not for expected failure.',
  },
  {
    id: 'go.defer.1',
    concepts: ['go.defer'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'In what order does this print?',
    code: 'func main() {\n\tdefer fmt.Println("last")\n\tfmt.Println("first")\n}',
    options: ['last\nfirst', 'first\nlast', 'only first', 'only last'],
    answer: 1,
    explain: 'defer runs when the function returns, however it returns. It is how files and locks get closed.',
  },
  {
    id: 'go.defer.2',
    concepts: ['go.defer'],
    difficulty: 5,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for i := 0; i < 3; i++ {\n\tdefer fmt.Print(i)\n}',
    options: ['012', '210', '000', '222'],
    answer: 1,
    explain: 'Deferred calls stack up and run in reverse order, with their arguments captured at defer time.',
  },

  /* ------------------------------------------------------ go.concurrency */
  {
    id: 'go.gor.1',
    concepts: ['go.goroutines'],
    difficulty: 5,
    kind: 'blank',
    prompt: 'Start work() concurrently.',
    template: '{{0}} work()',
    blanks: [{ accept: ['go'], width: 3 }],
    explain: 'One keyword starts a goroutine. They cost a couple of kilobytes, so thousands is normal.',
  },
  {
    id: 'go.gor.2',
    concepts: ['go.goroutines'],
    difficulty: 5,
    kind: 'predict',
    prompt: 'What usually happens here?',
    code: 'func main() {\n\tgo fmt.Println("hi")\n}',
    options: [
      'Prints hi',
      'Often prints nothing, because main exits before the goroutine runs',
      'Deadlocks',
      'Compile error',
    ],
    answer: 1,
    explain: 'When main returns the program ends, goroutines and all. You need a channel or WaitGroup to wait.',
  },
  {
    id: 'go.chan.1',
    concepts: ['go.channels'],
    difficulty: 5,
    kind: 'match',
    prompt: 'Match each channel operation to what it does.',
    pairs: [
      ['ch <- v', 'send v into the channel'],
      ['v := <-ch', 'receive a value from the channel'],
      ['close(ch)', 'signal that no more values are coming'],
    ],
    explain: 'The arrow always points in the direction the data travels.',
  },
  {
    id: 'go.chan.2',
    concepts: ['go.channels'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What does an unbuffered channel send do?',
    options: [
      'Blocks until another goroutine receives',
      'Returns immediately',
      'Drops the value if nobody is listening',
      'Panics',
    ],
    answer: [0],
    explain: 'That blocking *is* the synchronisation. "Do not communicate by sharing memory; share memory by communicating."',
  },
]);
