import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'gd.nodes',
    title: 'Nodes and scenes',
    blurb: 'Everything is a node; every scene is a tree of them.',
    concepts: ['gd.nodes', 'gd.scenes', 'gd.tree'],
    requires: [],
    level: 'intro',
    tags: ['games'],
    unit: 'The engine',
  },
  {
    id: 'gd.script',
    title: 'GDScript',
    blurb: 'Python-flavoured syntax, typed when you want it.',
    concepts: ['gd.syntax', 'gd.vars', 'gd.functions'],
    requires: ['gd.nodes'],
    level: 'core',
    tags: ['games'],
    unit: 'Scripting',
  },
  {
    id: 'gd.lifecycle',
    title: 'Ready, process, input',
    blurb: 'The callbacks the engine calls, and which one to put things in.',
    concepts: ['gd.ready', 'gd.process', 'gd.input'],
    requires: ['gd.script'],
    level: 'core',
    tags: ['games'],
    unit: 'Scripting',
  },
  {
    id: 'gd.signals',
    title: 'Signals',
    blurb: 'Godot s answer to coupling: shout upwards, call downwards.',
    concepts: ['gd.signals', 'gd.connect'],
    requires: ['gd.lifecycle'],
    level: 'applied',
    tags: ['games'],
    unit: 'Architecture',
  },
  {
    id: 'gd.gameplay',
    title: 'Movement and collision',
    blurb: 'CharacterBody2D, physics bodies, areas, and instancing scenes.',
    concepts: ['gd.movement', 'gd.collision', 'gd.instancing'],
    requires: ['gd.lifecycle'],
    level: 'applied',
    tags: ['games'],
    unit: 'Gameplay',
  },
];

export const godotTrack: Track = {
  id: 'godot',
  name: 'Godot',
  kind: 'engine',
  tagline: 'Small, free, and gets out of your way',
  blurb:
    'An open-source engine with a scene tree that clicks quickly and a scripting language that reads like Python. Excellent for 2D and increasingly good at 3D.',
  lang: 'gdscript',
  mark: 'Gd',
  tags: ['games', 'graphics'],
  goals: ['games', 'curious'],
  slope: 2,
  transfersFrom: ['python', 'unity'],
  skills,
};

export const godotExercises = forTrack('godot', [
  /* ----------------------------------------------------------- gd.nodes */
  {
    id: 'gd.node.1',
    concepts: ['gd.nodes'],
    difficulty: 1,
    kind: 'choice',
    prompt: 'What is a Node in Godot?',
    options: [
      'The basic building block: one job each, arranged in a tree',
      'A script file',
      'A texture',
      'A build target',
    ],
    answer: [0],
    explain: 'Sprite2D draws, CollisionShape2D collides, AudioStreamPlayer plays. Combine them rather than subclassing.',
  },
  {
    id: 'gd.node.2',
    concepts: ['gd.nodes'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each node to what it does.',
    pairs: [
      ['Sprite2D', 'draws a texture'],
      ['CharacterBody2D', 'a body you move with code, with collision'],
      ['Area2D', 'detects overlaps without blocking'],
      ['Timer', 'emits a signal after a delay'],
    ],
    explain: 'The node name tells you the job. If you cannot name the node you need, you may need two.',
  },
  {
    id: 'gd.scene.1',
    concepts: ['gd.scenes'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'What is a Scene in Godot?',
    options: [
      'A saved tree of nodes that can be instanced inside other scenes',
      'A level, and only a level',
      'A script',
      'A camera view',
    ],
    answer: [0],
    explain: 'A player, a bullet and a whole level are all scenes. There is no separate prefab concept — scenes are prefabs.',
  },
  {
    id: 'gd.tree.1',
    concepts: ['gd.tree'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Get a reference to a child node named Sprite2D.',
    lang: 'gdscript',
    template: '@onready var sprite = ${{0}}',
    blanks: [{ accept: ['Sprite2D', '"Sprite2D"'], width: 12 }],
    explain: 'The $ shorthand is get_node(). @onready waits until the node is actually in the tree.',
  },
  {
    id: 'gd.tree.2',
    concepts: ['gd.tree'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'Why is @onready needed for a $Node reference?',
    options: [
      'Variables initialise before the node enters the tree, so the child does not exist yet',
      'It makes it faster',
      'It exports the value',
      'It is optional styling',
    ],
    answer: [0],
    explain: 'Without it you get a null reference on the very first line that touches the child.',
  },

  /* ---------------------------------------------------------- gd.script */
  {
    id: 'gd.syn.1',
    concepts: ['gd.syntax'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'How does GDScript mark a block?',
    options: ['Curly braces', 'Indentation, like Python', 'begin and end', 'Parentheses'],
    answer: [1],
    explain: 'Indentation with a colon on the header line. If you know Python you already read GDScript.',
  },
  {
    id: 'gd.var.1',
    concepts: ['gd.vars'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Make speed adjustable from the Inspector.',
    lang: 'gdscript',
    template: '@{{0}} var speed: float = 300.0',
    blanks: [{ accept: ['export'], width: 8 }],
    explain: '@export puts the variable in the Inspector so a designer can tune it without touching code.',
  },
  {
    id: 'gd.var.2',
    concepts: ['gd.vars'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does the `: float` do in `var speed: float = 300.0`?',
    options: [
      'Declares a static type, which is checked and makes the code faster',
      'Nothing, it is a comment',
      'Rounds the value',
      'Makes it constant',
    ],
    answer: [0],
    explain: 'Typing is optional in GDScript, but typed code is checked at compile time and runs faster.',
  },
  {
    id: 'gd.fn.1',
    concepts: ['gd.functions'],
    difficulty: 3,
    kind: 'assemble',
    prompt: 'Build the header of a function that takes an amount and returns nothing.',
    lang: 'gdscript',
    answer: ['func', 'take_damage', '(', 'amount: int', ')', '->', 'void', ':'],
    distractors: ['def', 'function', '{'],
    explain: 'func rather than def, and the return type goes after an arrow.',
  },
  {
    id: 'gd.fn.2',
    concepts: ['gd.functions', 'gd.syntax'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This script will not run. Which line?',
    lang: 'gdscript',
    code: 'extends Node\n\nfunc _ready()\n\tprint("hello")',
    buggyLine: 3,
    why: {
      options: ['The colon after the function header is missing', 'print is not a function', '_ready needs arguments'],
      answer: 0,
    },
    explain: 'Every block header ends with a colon, exactly as in Python.',
  },

  /* ------------------------------------------------------- gd.lifecycle */
  {
    id: 'gd.ready.1',
    concepts: ['gd.ready'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each callback to when Godot calls it.',
    pairs: [
      ['_ready()', 'once, when the node and its children enter the tree'],
      ['_process(delta)', 'every frame'],
      ['_physics_process(delta)', 'on the fixed physics step'],
      ['_input(event)', 'when an input event arrives'],
    ],
    explain: 'Children are ready before their parent, so a parent can safely touch its children in _ready.',
  },
  {
    id: 'gd.proc.1',
    concepts: ['gd.process'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does delta hold?',
    lang: 'gdscript',
    code: 'func _process(delta):\n\tposition.x += 100 * delta',
    options: [
      'The frame number',
      'Seconds since the previous frame, making this 100 pixels per second',
      'Milliseconds since start',
      'Always 1',
    ],
    answer: 1,
    explain: 'Multiplying by delta is what keeps movement identical at 30 and 144 frames per second.',
  },
  {
    id: 'gd.proc.2',
    concepts: ['gd.process'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Where should physics-body movement go?',
    options: ['_physics_process', '_process', '_ready', '_input'],
    answer: [0],
    explain: 'It runs at a fixed rate, so collisions stay stable no matter how the frame rate wanders.',
  },
  {
    id: 'gd.input.1',
    concepts: ['gd.input'],
    difficulty: 4,
    kind: 'blank',
    prompt: 'Read the horizontal movement from the input map.',
    lang: 'gdscript',
    template: 'var dir = Input.{{0}}("ui_left", "ui_right")',
    blanks: [{ accept: ['get_axis'], width: 10 }],
    explain: 'get_axis returns -1 to 1 in one call, and respects whatever keys the player has bound.',
  },
  {
    id: 'gd.input.2',
    concepts: ['gd.input'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why use Input actions rather than checking a specific key?',
    options: [
      'Actions can be rebound and support gamepads without changing any code',
      'They are faster',
      'Key codes do not work',
      'It is required by the engine',
    ],
    answer: [0],
    explain: 'Define "jump" once in Project Settings, and keyboard, gamepad and remapping all come free.',
  },

  /* -------------------------------------------------------- gd.signals */
  {
    id: 'gd.sig.1',
    concepts: ['gd.signals'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is a signal?',
    options: [
      'An announcement a node emits that others can subscribe to',
      'A global variable',
      'A network message',
      'A kind of node',
    ],
    answer: [0],
    explain: 'The emitter never knows who is listening, which is exactly what keeps scenes reusable.',
  },
  {
    id: 'gd.sig.2',
    concepts: ['gd.signals'],
    difficulty: 4,
    kind: 'blank',
    prompt: 'Declare a signal that carries the new health value.',
    lang: 'gdscript',
    template: '{{0}} health_changed(new_value)',
    blanks: [{ accept: ['signal'], width: 8 }],
    explain: 'Emit it with health_changed.emit(hp) whenever the value moves.',
  },
  {
    id: 'gd.conn.1',
    concepts: ['gd.connect'],
    difficulty: 5,
    kind: 'assemble',
    prompt: 'Connect the player s health_changed signal to _on_health_changed.',
    lang: 'gdscript',
    answer: ['player', '.', 'health_changed', '.', 'connect', '(', '_on_health_changed', ')'],
    distractors: ['emit', 'signal', 'bind'],
    explain: 'Pass the function itself, without brackets — brackets would call it immediately.',
  },
  {
    id: 'gd.conn.2',
    concepts: ['gd.connect', 'gd.signals'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What is the "call down, signal up" rule?',
    options: [
      'A parent may call methods on its children; a child announces things with signals instead of reaching upward',
      'Always use signals',
      'Never use signals',
      'Signals only travel downward',
    ],
    answer: [0],
    explain: 'A child that calls get_parent().do_thing() can never be reused anywhere else.',
  },

  /* ------------------------------------------------------- gd.gameplay */
  {
    id: 'gd.move.1',
    concepts: ['gd.movement'],
    difficulty: 4,
    kind: 'order',
    prompt: 'Order a simple CharacterBody2D movement step.',
    lang: 'gdscript',
    lines: [
      'func _physics_process(delta):',
      '\tvar dir = Input.get_axis("ui_left", "ui_right")',
      '\tvelocity.x = dir * speed',
      '\tmove_and_slide()',
    ],
    explain: 'Set velocity, then call move_and_slide(). It reads velocity itself, so it takes no arguments.',
  },
  {
    id: 'gd.move.2',
    concepts: ['gd.movement'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What does move_and_slide() do that setting position does not?',
    options: [
      'Resolves collisions and slides along surfaces instead of passing through them',
      'Draws the sprite',
      'Applies gravity automatically',
      'Nothing different',
    ],
    answer: [0],
    explain: 'Gravity is still yours to add: velocity.y += gravity * delta before you call it.',
  },
  {
    id: 'gd.coll.1',
    concepts: ['gd.collision'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each body type to what it is for.',
    pairs: [
      ['StaticBody2D', 'walls and floors that never move'],
      ['RigidBody2D', 'objects the physics engine pushes around'],
      ['CharacterBody2D', 'a body you move yourself, with collision'],
      ['Area2D', 'detecting overlaps without blocking anything'],
    ],
    explain: 'Pick-ups and hitboxes are Area2D. Reaching for RigidBody2D for a player usually ends in tears.',
  },
  {
    id: 'gd.coll.2',
    concepts: ['gd.collision'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'A body falls straight through the floor. What is the most likely cause?',
    options: [
      'It has no CollisionShape2D, or the shape has no size',
      'The sprite is too small',
      'Gravity is too high',
      'The floor needs a script',
    ],
    answer: [0],
    explain: 'A physics body without a shape has nothing to collide with. Godot warns about this in the scene dock.',
  },
  {
    id: 'gd.inst.1',
    concepts: ['gd.instancing'],
    difficulty: 5,
    kind: 'order',
    prompt: 'Order the lines that spawn a bullet scene.',
    lang: 'gdscript',
    lines: [
      'var bullet = bullet_scene.instantiate()',
      'bullet.position = muzzle.global_position',
      'get_tree().current_scene.add_child(bullet)',
    ],
    explain: 'Instancing alone does not put it in the world — it has to be added to the tree before it exists.',
  },
]);
