import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const godotExtraSkills: Skill[] = [
  {
    id: 'gd.arch',
    title: 'Groups and autoloads',
    blurb: 'Talking to many nodes at once, and the state that outlives a scene.',
    concepts: ['gd.groups', 'gd.autoload'],
    requires: ['gd.signals'],
    level: 'applied',
    tags: ['games'],
    unit: 'Architecture',
  },
  {
    id: 'gd.ui',
    title: 'Control nodes and UI',
    blurb: 'Anchors, containers and themes for menus that survive a resize.',
    concepts: ['gd.control', 'gd.containers', 'gd.themes'],
    requires: ['gd.script'],
    level: 'applied',
    tags: ['games'],
    unit: 'Presentation',
  },
];

export const godotExtra = forTrack('godot', [
  {
    id: 'gd.node.x1',
    concepts: ['gd.nodes'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'You need a coin that is drawn, spins, and knows when the player touches it. How is that built in Godot?',
    options: [
      'One node per job — Sprite2D, AnimationPlayer, Area2D — parented together',
      'One Coin node with every feature built into it',
      'Three separate scenes that talk over signals',
      'A script with no nodes at all',
    ],
    answer: [0],
    explain: 'Composition is the whole idea: each node does one job, and the tree is how they add up to a coin.',
  },
  {
    id: 'gd.scene.x1',
    concepts: ['gd.scenes'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What is a scene?',
    options: [
      'A saved tree of nodes that can be instanced anywhere, including inside another scene',
      'A level, and only a level',
      'A script with a class',
      'A folder of assets',
    ],
    answer: [0],
    explain: 'A player, a bullet and a whole level are all scenes. That uniformity is the engine’s best idea.',
  },
  {
    id: 'gd.tree.x1',
    concepts: ['gd.tree'],
    difficulty: 2,
    level: 2,
    kind: 'blank',
    prompt: 'Get a child node called Sprite2D from a script.',
    template: '@onready var sprite = ${{0}}',
    blanks: [{ accept: ['Sprite2D'], width: 10 }],
    explain: '$Name is shorthand for get_node("Name"). @onready waits until the node is in the tree.',
  },
  {
    id: 'gd.syn.x1',
    concepts: ['gd.syntax'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'var n = 7\nprint(n / 2)\nprint(n % 2)',
    options: ['3.5\n1', '3\n1', '3.5\n0', '3\n0'],
    answer: 0,
    explain: 'GDScript division of ints gives a float; use floor() or int() when you want the whole number.',
  },
  {
    id: 'gd.var.x1',
    concepts: ['gd.vars'],
    difficulty: 2,
    level: 2,
    kind: 'blank',
    prompt: 'Expose speed in the Inspector.',
    template: '@{{0}} var speed: float = 200.0',
    blanks: [{ accept: ['export'], width: 7 }],
    explain: 'Exported variables become editable per instance, which is how one script serves ten enemies.',
  },
  {
    id: 'gd.fn.x1',
    concepts: ['gd.functions'],
    difficulty: 2,
    level: 3,
    kind: 'order',
    prompt: 'Write a small function.',
    lines: ['func damage(amount: int) -> void:', '\thealth -= amount', '\tif health <= 0:', '\t\tqueue_free()'],
    explain: 'Tabs matter: GDScript is indentation-scoped like Python. queue_free deletes the node safely.',
  },
  {
    id: 'gd.ready.x1',
    concepts: ['gd.ready'],
    difficulty: 3,
    level: 3,
    kind: 'match',
    prompt: 'Match each callback to when it runs.',
    pairs: [
      ['_ready()', 'Once, when the node enters the tree'],
      ['_process(delta)', 'Every rendered frame'],
      ['_physics_process(delta)', 'Every physics tick, at a fixed rate'],
      ['_input(event)', 'When an input event arrives'],
    ],
    explain: 'Move bodies in _physics_process. Doing it in _process ties your game to the framerate.',
  },
  {
    id: 'gd.proc.x1',
    concepts: ['gd.process'],
    difficulty: 3,
    level: 4,
    kind: 'bug',
    prompt: 'The character moves faster on a 144Hz monitor. Which line is the cause?',
    code: 'func _process(delta):\n\tposition.x += speed',
    buggyLine: 2,
    why: {
      options: [
        'speed is not multiplied by delta, so movement is per frame rather than per second',
        'position is read-only',
        '_process should be _ready',
        'speed must be an int',
      ],
      answer: 0,
    },
    explain: 'delta is the seconds since the last frame. Multiplying by it is what makes speed mean units per second.',
  },
  {
    id: 'gd.input.x1',
    concepts: ['gd.input'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'Why use Input.is_action_pressed("move_left") rather than checking the A key?',
    options: [
      'Actions are remappable and can be bound to a gamepad as well',
      'It is faster',
      'Key codes are deprecated',
      'It works in _ready',
    ],
    answer: [0],
    explain: 'Define actions in the Input Map once, and rebinding controls costs nothing later.',
  },

  /* ------------------------------------------------------- gd.signals */
  {
    id: 'gd.sigx.1',
    concepts: ['gd.signals'],
    difficulty: 3,
    level: 5,
    kind: 'order',
    prompt: 'Declare a signal and send it.',
    lines: ['signal died', '', 'func take_damage(amount):', '\thealth -= amount', '\tif health <= 0:', '\t\tdied.emit()'],
    explain: 'The node that knows announces; whoever cares connects. The emitter never learns who listened.',
  },
  {
    id: 'gd.sigx.2',
    concepts: ['gd.signals'],
    difficulty: 4,
    level: 6,
    kind: 'blank',
    prompt: 'Listen for that signal from another script.',
    template: 'enemy.died.{{0}}(_on_enemy_died)',
    blanks: [{ accept: ['connect'], width: 8 }],
    explain: 'Connecting in code keeps the wiring greppable; the editor’s Node panel does the same thing visually.',
  },
  {
    id: 'gd.sigx.3',
    concepts: ['gd.groups'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What are groups for?',
    options: [
      'Tagging nodes so you can call a method on all of them at once',
      'Rendering order',
      'Physics layers',
      'Grouping files in the editor',
    ],
    answer: [0],
    explain: 'get_tree().call_group("enemies", "flee") is one line instead of a manual list you have to maintain.',
  },
  {
    id: 'gd.sigx.4',
    concepts: ['gd.autoload'],
    difficulty: 5,
    level: 7,
    kind: 'choice',
    prompt: 'What is an autoload (singleton) good for?',
    options: [
      'State that outlives scenes — score, settings, a music player',
      'Anything you use twice',
      'Replacing signals',
      'Speeding up loading',
    ],
    answer: [0],
    explain: 'Useful and easy to overuse: every autoload is a global, and globals are how scenes get tangled together.',
  },

  {
    id: 'gd.arch.1',
    concepts: ['gd.groups'],
    difficulty: 4,
    level: 6,
    kind: 'blank',
    prompt: 'Add this node to the "enemies" group from code.',
    template: 'func _ready():\n\tadd_to_{{0}}("enemies")',
    blanks: [{ accept: ['group'], width: 6 }],
    explain: 'Groups are tags on nodes. is_in_group asks, call_group broadcasts.',
  },
  {
    id: 'gd.arch.2',
    concepts: ['gd.groups'],
    difficulty: 4,
    level: 7,
    kind: 'predict',
    prompt: 'Six nodes are in the "enemies" group. What does this do?',
    code: 'get_tree().call_group("enemies", "flee")',
    options: [
      'Calls flee() on all six, skipping any that do not have it',
      'Calls flee() on the first one only',
      'Throws if one is missing flee()',
      'Nothing until the next frame',
    ],
    answer: 0,
    explain: 'Missing methods are skipped rather than raising, which makes groups forgiving and a little loose.',
  },
  {
    id: 'gd.arch.3',
    concepts: ['gd.autoload'],
    difficulty: 5,
    level: 8,
    kind: 'bug',
    prompt: 'The score resets whenever a level loads. Where does it belong instead?',
    code: 'Level.gd:\n\tvar score = 0\n\nfunc add_point():\n\tscore += 1',
    buggyLine: 2,
    why: {
      options: [
        'It lives on a node that is freed with the scene; it belongs on an autoload',
        'score must be exported',
        'add_point should be _process',
        'Integers cannot persist',
      ],
      answer: 0,
    },
    explain: 'Changing scenes frees the old tree. Anything that must survive has to live outside it.',
  },

  /* ------------------------------------------------------------ gd.ui */
  {
    id: 'gd.ui.1',
    concepts: ['gd.control'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'Which node type should a menu be built from?',
    options: ['Control nodes', 'Node2D', 'Node3D', 'RigidBody2D'],
    answer: [0],
    explain: 'Controls understand anchors, margins and focus. Node2D knows only a transform.',
  },
  {
    id: 'gd.ui.2',
    concepts: ['gd.containers'],
    difficulty: 4,
    level: 6,
    kind: 'match',
    prompt: 'Match each container to what it does with its children.',
    pairs: [
      ['VBoxContainer', 'Stacks them vertically'],
      ['HBoxContainer', 'Lays them out in a row'],
      ['MarginContainer', 'Adds padding around them'],
      ['CenterContainer', 'Centres a single child'],
    ],
    explain: 'A container owns its children’s size and position, so setting those by hand inside one does nothing.',
  },
  {
    id: 'gd.ui.3',
    concepts: ['gd.themes'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What is a Theme resource for?',
    options: [
      'Styling every control of a type at once, instead of overriding each node',
      'Post-processing',
      'Localisation',
      'Input mapping',
    ],
    answer: [0],
    explain: 'Set the theme on the root Control and it cascades, exactly like a stylesheet.',
  },
  {
    id: 'gd.ui.4',
    concepts: ['gd.control'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'The UI is fine on your monitor and cropped on a smaller one. What is the fix?',
    options: [
      'Set the stretch mode and aspect in Project Settings, and anchor controls to the edges they belong to',
      'Scale the root node down',
      'Use a fixed window size',
      'Move the UI into a subviewport',
    ],
    answer: [0],
    explain: 'canvas_items stretch plus sensible anchors handles nearly every resolution without extra code.',
  },
]);
