import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'js.first',
    title: 'First lines',
    blurb: 'Log something, comment something, and meet the semicolon question.',
    concepts: ['js.log', 'js.comments'],
    requires: [],
    level: 'intro',
    tags: ['web'],
    unit: 'Getting started',
  },
  {
    id: 'js.vars',
    title: 'Values and names',
    blurb: 'let, const, the types you will actually meet, and template literals.',
    concepts: ['js.variables', 'js.types', 'js.template'],
    requires: ['js.first'],
    level: 'intro',
    tags: ['web'],
    unit: 'Getting started',
  },
  {
    id: 'js.logic',
    title: 'Decisions',
    blurb: 'Comparisons, truthiness, and why === exists.',
    concepts: ['js.comparison', 'js.truthy', 'js.if'],
    requires: ['js.vars'],
    level: 'core',
    tags: ['web', 'interviews'],
    unit: 'Control flow',
  },
  {
    id: 'js.loops',
    title: 'Loops',
    blurb: 'Classic for, for...of, while, and knowing which to reach for.',
    concepts: ['js.for', 'js.forof', 'js.while'],
    requires: ['js.logic'],
    level: 'core',
    tags: ['web'],
    unit: 'Control flow',
  },
  {
    id: 'js.functions',
    title: 'Functions',
    blurb: 'Declarations, arrow functions, parameters and defaults.',
    concepts: ['js.functions', 'js.arrow', 'js.params'],
    requires: ['js.loops'],
    level: 'core',
    tags: ['web', 'apps'],
    unit: 'Building blocks',
  },
  {
    id: 'js.arrays',
    title: 'Arrays',
    blurb: 'The methods that made JavaScript pleasant: map, filter, reduce.',
    concepts: ['js.arrays', 'js.arraymethods', 'js.mapfilter'],
    requires: ['js.functions'],
    level: 'core',
    tags: ['web', 'data', 'interviews'],
    unit: 'Data',
  },
  {
    id: 'js.objects',
    title: 'Objects',
    blurb: 'Key-value shapes, destructuring, and spreading.',
    concepts: ['js.objects', 'js.destructuring', 'js.spread'],
    requires: ['js.functions'],
    level: 'core',
    tags: ['web', 'apps'],
    unit: 'Data',
  },
  {
    id: 'js.async',
    title: 'Asynchronous JavaScript',
    blurb: 'Promises, async/await, and why the order surprises you.',
    concepts: ['js.async', 'js.promises'],
    requires: ['js.objects', 'js.arrays'],
    level: 'advanced',
    tags: ['web', 'apps'],
    unit: 'The real world',
  },
  {
    id: 'js.dom',
    title: 'The browser',
    blurb: 'Find elements, change them, and respond to clicks.',
    concepts: ['js.dom', 'js.events'],
    requires: ['js.objects'],
    level: 'applied',
    tags: ['web'],
    unit: 'The real world',
  },
];

export const javascriptTrack: Track = {
  id: 'javascript',
  name: 'JavaScript',
  kind: 'language',
  tagline: 'The language of everything with a screen',
  blurb:
    'Runs in every browser on earth, and on servers through Node. If you want to build something people can open with a link, this is the shortest path.',
  lang: 'javascript',
  runLang: 'javascript',
  mark: 'JS',
  tags: ['web', 'apps', 'interviews'],
  goals: ['web', 'apps', 'interviews', 'curious'],
  slope: 2,
  transfersFrom: ['python', 'typescript'],
  skills,
};

export const javascriptExercises = forTrack('javascript', [
  /* ------------------------------------------------------------ js.first */
  {
    id: 'js.log.1',
    concepts: ['js.log'],
    difficulty: 1,
    kind: 'assemble',
    prompt: 'Build the line that logs Hello to the console.',
    answer: ['console', '.', 'log', '(', '"Hello"', ')', ';'],
    distractors: ['print', 'echo'],
    explain: 'console.log is a method on the console object, which is why it needs the dot.',
  },
  {
    id: 'js.log.2',
    concepts: ['js.log'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'console.log("a", 1, true);',
    options: ['a 1 true', 'a1true', 'a,1,true', 'Error'],
    answer: 0,
    explain: 'console.log takes any number of arguments and separates them with spaces.',
  },
  {
    id: 'js.comments.1',
    concepts: ['js.comments'],
    difficulty: 1,
    kind: 'choice',
    prompt: 'Which is a valid JavaScript comment?',
    options: ['# a note', '-- a note', '// a note', '<!-- a note -->'],
    answer: [2],
    explain: '// for one line, /* ... */ for several. The # form belongs to Python and shell.',
  },
  {
    id: 'js.comments.2',
    concepts: ['js.comments', 'js.log'],
    difficulty: 2,
    kind: 'bug',
    prompt: 'This should log both lines. Which line stops that?',
    code: 'console.log("one");\n/* console.log("two");\nconsole.log("three");',
    buggyLine: 2,
    why: {
      options: [
        'The block comment is never closed, so everything after it is ignored',
        'console is misspelled',
        'Semicolons are missing',
      ],
      answer: 0,
    },
    explain: 'An unclosed /* swallows the rest of the file. Editors colour it grey — trust the colour.',
  },

  /* ------------------------------------------------------------- js.vars */
  {
    id: 'js.var.1',
    concepts: ['js.variables'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'Which should you reach for by default?',
    options: ['var', 'let', 'const', 'No keyword at all'],
    answer: [2],
    explain: 'const first, let when you must reassign, var effectively never in modern code.',
  },
  {
    id: 'js.var.2',
    concepts: ['js.variables'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What happens here?',
    code: 'const xs = [1, 2];\nxs.push(3);\nconsole.log(xs.length);',
    options: ['2', '3', 'TypeError: Assignment to constant', 'undefined'],
    answer: 1,
    explain: 'const freezes the binding, not the contents. You cannot reassign xs, but you can change the array.',
  },
  {
    id: 'js.types.1',
    concepts: ['js.types'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each value to what typeof reports.',
    pairs: [
      ['42', '"number"'],
      ['"hi"', '"string"'],
      ['[]', '"object"'],
      ['undefined', '"undefined"'],
    ],
    explain: 'Arrays report as "object" — use Array.isArray() when you need to be sure.',
  },
  {
    id: 'js.types.2',
    concepts: ['js.types'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is the difference between null and undefined?',
    options: [
      'They are identical',
      'undefined means "never given a value"; null means "deliberately empty"',
      'null is a string',
      'undefined only appears in functions',
    ],
    answer: [1],
    explain: 'undefined is what JavaScript hands you; null is what you choose to store.',
  },
  {
    id: 'js.tmpl.1',
    concepts: ['js.template'],
    difficulty: 2,
    kind: 'blank',
    prompt: 'Complete the template literal so it greets by name.',
    template: 'const name = "Ada";\nconsole.log({{0}}Hello, ${name}!{{1}});',
    blanks: [
      { accept: ['`'], width: 2 },
      { accept: ['`'], width: 2 },
    ],
    explain: 'Backticks, not quotes. ${...} only interpolates inside a template literal.',
  },
  {
    id: 'js.tmpl.2',
    concepts: ['js.template'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Log "3 x 4 = 12" using a template literal, for a = 3 and b = 4.',
    runLang: 'javascript',
    starter: 'const a = 3;\nconst b = 4;\n',
    solution: 'const a = 3;\nconst b = 4;\nconsole.log(`${a} x ${b} = ${a * b}`);',
    tests: [{ name: 'multiplies', expect: '3 x 4 = 12' }],
    mustContain: [{ pattern: '`', label: 'use a template literal' }],
    explain: 'Any expression goes inside ${}, including the multiplication itself.',
  },

  /* ------------------------------------------------------------ js.logic */
  {
    id: 'js.cmp.1',
    concepts: ['js.comparison'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'console.log(1 == "1", 1 === "1");',
    options: ['true true', 'false false', 'true false', 'false true'],
    answer: 2,
    explain: '== converts types before comparing. === does not. Use === unless you have a reason.',
  },
  {
    id: 'js.cmp.2',
    concepts: ['js.comparison'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why is [] == false true in JavaScript?',
    options: [
      'Arrays are always false',
      'Both sides get converted: [] becomes "" becomes 0, and false becomes 0',
      'It is a bug in the language spec',
      'It is not true',
    ],
    answer: [1],
    explain: 'This chain of conversions is precisely why === exists. Avoid == and you never think about it.',
  },
  {
    id: 'js.truthy.1',
    concepts: ['js.truthy'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'Which of these is truthy?',
    options: ['0', '""', '"0"', 'null'],
    answer: [2],
    explain: 'The falsy values are false, 0, -0, 0n, "", null, undefined and NaN. Everything else is truthy.',
  },
  {
    id: 'js.truthy.2',
    concepts: ['js.truthy'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'const count = 0;\nconsole.log(count || "none");\nconsole.log(count ?? "none");',
    options: ['none\n0', '0\n0', 'none\nnone', '0\nnone'],
    answer: 0,
    explain: '|| falls through on any falsy value; ?? only on null or undefined. That is the whole difference.',
  },
  {
    id: 'js.if.1',
    concepts: ['js.if'],
    difficulty: 2,
    kind: 'order',
    prompt: 'Order these lines into a working check.',
    lines: ['const n = 5;', 'if (n > 3) {', '  console.log("big");', '} else {', '  console.log("small");', '}'],
    explain: 'The condition goes in round brackets; the body in curly ones.',
  },
  {
    id: 'js.if.2',
    concepts: ['js.if'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Write a function sign(n) that returns "positive", "negative" or "zero", and log sign(-4).',
    runLang: 'javascript',
    starter: 'function sign(n) {\n  // your turn\n}\nconsole.log(sign(-4));',
    solution:
      'function sign(n) {\n  if (n > 0) return "positive";\n  if (n < 0) return "negative";\n  return "zero";\n}\nconsole.log(sign(-4));',
    tests: [{ name: 'negative', expect: 'negative' }],
    mustContain: [{ pattern: 'return', label: 'return the answer' }],
    explain: 'Early returns beat nested else branches: each case is one flat line.',
  },

  /* ------------------------------------------------------------ js.loops */
  {
    id: 'js.for.1',
    concepts: ['js.for'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Complete the classic loop so it runs 5 times.',
    template: 'for (let i = 0; i {{0}} 5; i{{1}}) {\n  console.log(i);\n}',
    blanks: [
      { accept: ['<'], width: 3 },
      { accept: ['++', '+= 1'], width: 5 },
    ],
    explain: 'Start, condition, step. i < 5 with i starting at 0 gives exactly five rounds.',
  },
  {
    id: 'js.for.2',
    concepts: ['js.for'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This should log 0 to 4 but logs one line too many. Which line is wrong?',
    code: 'for (let i = 0; i <= 5; i++) {\n  console.log(i);\n}',
    buggyLine: 1,
    why: {
      options: ['<= should be <', 'i should start at 1', 'i++ should be i--'],
      answer: 0,
    },
    explain: 'Off-by-one errors nearly always live in the comparison operator. Count the rounds on your fingers.',
  },
  {
    id: 'js.forof.1',
    concepts: ['js.forof'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'Which loop gives you the values of an array directly?',
    options: ['for...in', 'for...of', 'while', 'do...while'],
    answer: [1],
    explain: 'for...of walks values; for...in walks keys, which on an array means index strings.',
  },
  {
    id: 'js.forof.2',
    concepts: ['js.forof'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'for (const x of ["a", "b"]) console.log(x);',
    options: ['0\n1', 'a\nb', '["a","b"]', 'a b'],
    answer: 1,
    explain: 'Swapping to for...in here would log 0 and 1 — a classic source of confusion.',
  },
  {
    id: 'js.while.1',
    concepts: ['js.while'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'How many times does this log?',
    code: 'let n = 3;\nwhile (n > 0) {\n  console.log(n);\n  n--;\n}',
    options: ['2', '3', '4', 'forever'],
    answer: 1,
    explain: 'n takes the values 3, 2 and 1, then the condition fails at 0.',
  },
  {
    id: 'js.loops.write.1',
    concepts: ['js.for', 'js.forof'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Log the sum of the numbers 1 to 10.',
    runLang: 'javascript',
    starter: 'let total = 0;\n',
    solution: 'let total = 0;\nfor (let i = 1; i <= 10; i++) total += i;\nconsole.log(total);',
    tests: [{ name: 'sums to 55', expect: '55' }],
    explain: 'total must be let, not const, because the loop reassigns it every round.',
  },

  /* -------------------------------------------------------- js.functions */
  {
    id: 'js.fn.1',
    concepts: ['js.functions'],
    difficulty: 2,
    kind: 'assemble',
    prompt: 'Build the header of a function called double that takes n.',
    answer: ['function', 'double', '(', 'n', ')', '{'],
    distractors: ['def', '=>', ':'],
    explain: 'The keyword, the name, the parameters in round brackets, then the body in curly ones.',
  },
  {
    id: 'js.arrow.1',
    concepts: ['js.arrow'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each arrow function to its meaning.',
    pairs: [
      ['n => n * 2', 'takes n, returns n doubled'],
      ['() => 42', 'takes nothing, returns 42'],
      ['(a, b) => a + b', 'takes two values, returns their sum'],
    ],
    explain: 'With no braces the body is the return value. Adding braces means you must write return yourself.',
  },
  {
    id: 'js.arrow.2',
    concepts: ['js.arrow'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'const f = n => { n * 2 };\nconsole.log(f(4));',
    options: ['8', 'undefined', '4', 'Error'],
    answer: 1,
    explain: 'The braces make it a block, and the block never returns. Drop them, or add return.',
  },
  {
    id: 'js.params.1',
    concepts: ['js.params'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'function greet(name = "friend") {\n  return `Hi ${name}`;\n}\nconsole.log(greet(), greet("Ada"));',
    options: ['Hi friend Hi Ada', 'Hi undefined Hi Ada', 'Hi Hi Ada', 'Error'],
    answer: 0,
    explain: 'A default fires when the argument is undefined — including when it is simply left out.',
  },
  {
    id: 'js.fn.write.1',
    concepts: ['js.functions', 'js.arrow'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Write an arrow function shout that upper-cases text and adds "!", then log shout("hey").',
    runLang: 'javascript',
    starter: 'const shout = ;\nconsole.log(shout("hey"));',
    solution: 'const shout = (s) => s.toUpperCase() + "!";\nconsole.log(shout("hey"));',
    tests: [{ name: 'shouts', expect: 'HEY!' }],
    mustContain: [{ pattern: '=>', label: 'use an arrow function' }],
    explain: 'One expression, no braces, no return keyword needed.',
  },

  /* ----------------------------------------------------------- js.arrays */
  {
    id: 'js.arr.1',
    concepts: ['js.arrays'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'const xs = [1, 2, 3];\nconsole.log(xs.length, xs[0]);',
    options: ['3 1', '3 0', '2 1', '3 undefined'],
    answer: 0,
    explain: 'length counts items; indexing starts at 0. xs[xs.length] is always undefined.',
  },
  {
    id: 'js.arrm.1',
    concepts: ['js.arraymethods'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each array method to what it returns.',
    pairs: [
      ['push', 'the new length, after adding to the end'],
      ['slice', 'a copy of part of the array'],
      ['includes', 'true or false'],
      ['join', 'a single string'],
    ],
    explain: 'slice copies, splice cuts the original. One letter, completely different consequences.',
  },
  {
    id: 'js.mapf.1',
    concepts: ['js.mapfilter'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'console.log([1, 2, 3, 4].filter(n => n % 2 === 0));',
    options: ['[ 1, 3 ]', '[ 2, 4 ]', '[ true, false ]', '2'],
    answer: 1,
    explain: 'filter keeps the items whose callback returns true, and always returns a new array.',
  },
  {
    id: 'js.mapf.2',
    concepts: ['js.mapfilter'],
    difficulty: 4,
    kind: 'assemble',
    prompt: 'Build the expression that doubles every number in xs.',
    answer: ['xs', '.', 'map', '(', 'n => n * 2', ')'],
    distractors: ['filter', 'forEach', 'reduce'],
    explain: 'map transforms one-for-one. forEach would run the function but hand you nothing back.',
  },
  {
    id: 'js.mapf.3',
    concepts: ['js.mapfilter', 'js.arraymethods'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Given the array, log the sum of the even numbers only.',
    runLang: 'javascript',
    starter: 'const xs = [1, 2, 3, 4, 5, 6];\n',
    solution:
      'const xs = [1, 2, 3, 4, 5, 6];\nconsole.log(xs.filter(n => n % 2 === 0).reduce((a, b) => a + b, 0));',
    tests: [{ name: '2 + 4 + 6', expect: '12' }],
    explain: 'filter then reduce reads as one sentence. The 0 is the starting total, and skipping it breaks empty arrays.',
    hint: 'Which method turns many values into one?',
  },

  /* ---------------------------------------------------------- js.objects */
  {
    id: 'js.obj.1',
    concepts: ['js.objects'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'const user = { name: "Ada", age: 36 };\nconsole.log(user.name, user["age"]);',
    options: ['Ada 36', 'name age', 'undefined undefined', 'Error'],
    answer: 0,
    explain: 'Dot notation and bracket notation reach the same property. Brackets take a computed key.',
  },
  {
    id: 'js.obj.2',
    concepts: ['js.objects'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does user.missing give you?',
    options: ['null', 'undefined', 'An error', 'An empty string'],
    answer: [1],
    explain: 'Reading a missing property is safe. Reading a property *of* undefined is what throws.',
  },
  {
    id: 'js.destr.1',
    concepts: ['js.destructuring'],
    difficulty: 4,
    kind: 'blank',
    prompt: 'Pull name and age out of user in one line.',
    template: 'const {{0}} name, age {{1}} = user;',
    blanks: [
      { accept: ['{'], width: 2 },
      { accept: ['}'], width: 2 },
    ],
    explain: 'Curly braces on the left destructure an object; square brackets destructure an array.',
  },
  {
    id: 'js.destr.2',
    concepts: ['js.destructuring'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'const [a, b] = [10, 20, 30];\nconsole.log(a, b);',
    options: ['10 20', '20 30', '10 30', 'Error'],
    answer: 0,
    explain: 'Array destructuring takes them in order and quietly ignores the rest.',
  },
  {
    id: 'js.spread.1',
    concepts: ['js.spread'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this log?',
    code: 'const a = { x: 1 };\nconst b = { ...a, y: 2 };\nconsole.log(Object.keys(b).join(","));',
    options: ['x', 'y', 'x,y', 'a,y'],
    answer: 2,
    explain: '...a copies a shallow set of properties. It is how you update state without mutating it.',
  },
  {
    id: 'js.spread.2',
    concepts: ['js.spread', 'js.objects'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Log a copy of user with the age changed to 40, without changing user itself.',
    runLang: 'javascript',
    starter: 'const user = { name: "Ada", age: 36 };\n',
    solution:
      'const user = { name: "Ada", age: 36 };\nconst older = { ...user, age: 40 };\nconsole.log(older.age, user.age);',
    tests: [{ name: 'copies without mutating', expect: '40 36' }],
    mustContain: [{ pattern: '...', label: 'use the spread syntax' }],
    explain: 'Later keys win, so putting age after the spread overrides it.',
  },

  /* ------------------------------------------------------------ js.async */
  {
    id: 'js.async.1',
    concepts: ['js.async'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'In what order do these log?',
    code: 'console.log("a");\nsetTimeout(() => console.log("b"), 0);\nconsole.log("c");',
    options: ['a b c', 'a c b', 'b a c', 'c a b'],
    answer: 1,
    explain: 'Even a zero-millisecond timeout waits for the current work to finish. That queue is the event loop.',
  },
  {
    id: 'js.prom.1',
    concepts: ['js.promises'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What does an async function always return?',
    options: ['The value you returned', 'A Promise', 'undefined', 'A callback'],
    answer: [1],
    explain: 'Even `async function f() { return 1 }` returns a Promise that resolves to 1.',
  },
  {
    id: 'js.prom.2',
    concepts: ['js.promises', 'js.async'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'This logs a Promise instead of the data. Which line is wrong?',
    code: 'async function load() {\n  return 42;\n}\nconst data = load();\nconsole.log(data);',
    buggyLine: 4,
    why: {
      options: [
        'load needs await in front of it',
        'load should not be async',
        'return 42 should be console.log(42)',
      ],
      answer: 0,
    },
    explain: 'await unwraps the promise. Without it you hold the box rather than what is inside.',
  },
  {
    id: 'js.async.2',
    concepts: ['js.async'],
    difficulty: 5,
    kind: 'order',
    prompt: 'Order the lines of an async function that handles failure.',
    lines: [
      'async function main() {',
      '  try {',
      '    const data = await load();',
      '    console.log(data);',
      '  } catch (err) {',
      '    console.log("failed");',
      '  }',
      '}',
    ],
    explain: 'await turns a rejected promise into a thrown error, so ordinary try/catch works on it.',
  },

  /* -------------------------------------------------------------- js.dom */
  {
    id: 'js.dom.1',
    concepts: ['js.dom'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each call to what it finds.',
    pairs: [
      ['document.querySelector("#total")', 'the element with id "total"'],
      ['document.querySelectorAll(".row")', 'every element with class "row"'],
      ['element.textContent', 'the text inside an element'],
    ],
    explain: 'querySelector takes a CSS selector, so everything you know from CSS works here.',
  },
  {
    id: 'js.dom.2',
    concepts: ['js.dom'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why does querySelector sometimes return null?',
    options: [
      'The page is still loading, or nothing matches the selector',
      'The element is hidden',
      'JavaScript is disabled',
      'It never returns null',
    ],
    answer: [0],
    explain: 'A script in <head> runs before the body exists. Load it with defer, or put it at the end.',
  },
  {
    id: 'js.events.1',
    concepts: ['js.events'],
    difficulty: 4,
    kind: 'assemble',
    prompt: 'Build the line that runs onClick when the button is clicked.',
    answer: ['button', '.', 'addEventListener', '(', '"click"', ',', 'onClick', ')'],
    distractors: ['onclick=', 'listen', '"press"'],
    explain: 'Pass the function itself, not onClick() — the brackets would call it immediately.',
  },
  {
    id: 'js.events.2',
    concepts: ['js.events'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'The handler fires once at page load instead of on click. Which line is wrong?',
    code: 'const btn = document.querySelector("button");\nfunction hi() { console.log("hi"); }\nbtn.addEventListener("click", hi());',
    buggyLine: 3,
    why: {
      options: [
        'hi() calls the function and passes its result; it should be hi',
        'The event should be "onclick"',
        'btn is null',
      ],
      answer: 0,
    },
    explain: 'Passing hi() hands over undefined. Passing hi hands over the function itself.',
  },
]);
