import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const javascriptExtraSkills: Skill[] = [
  {
    id: 'js.modules',
    title: 'Modules and tooling',
    blurb: 'Split code across files, and know what a bundler is actually doing.',
    concepts: ['js.modules', 'js.npm', 'js.strict'],
    requires: ['js.functions'],
    level: 'applied',
    tags: ['web', 'apps'],
    unit: 'The real world',
  },
  {
    id: 'js.errors',
    title: 'Errors and edge cases',
    blurb: 'try/catch, throwing usefully, and the values that trip everybody up.',
    concepts: ['js.trycatch', 'js.throw', 'js.nullish'],
    requires: ['js.functions'],
    level: 'applied',
    tags: ['apps', 'interviews'],
    unit: 'The real world',
  },
  {
    id: 'js.classes',
    title: 'Classes and this',
    blurb: 'Objects with behaviour, and the one keyword everybody gets wrong.',
    concepts: ['js.classes', 'js.this', 'js.prototype'],
    requires: ['js.objects'],
    level: 'advanced',
    tags: ['apps', 'interviews'],
    unit: 'Going deeper',
  },
];

export const javascriptExtra = forTrack('javascript', [
  /* ------------------------------------------------ the bottom of the ladder */
  {
    id: 'js.log.x1',
    concepts: ['js.log'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which line prints hello to the console?',
    options: ['console.log("hello")', 'print("hello")', 'echo("hello")', 'log hello'],
    answer: [0],
    explain: 'console.log is the one you will type ten thousand times. Get it into your fingers.',
  },
  {
    id: 'js.log.x2',
    concepts: ['js.log'],
    difficulty: 1,
    level: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'console.log("5" + 1);',
    options: ['51', '6', '5 1', 'an error'],
    answer: 0,
    explain: 'A string plus anything is a string. This one line explains half of JavaScript’s reputation.',
  },
  {
    id: 'js.log.x3',
    concepts: ['js.log'],
    difficulty: 2,
    level: 2,
    kind: 'blank',
    prompt: 'Print the value of total.',
    template: 'const total = 9;\nconsole.{{0}}(total);',
    blanks: [{ accept: ['log'], width: 4 }],
    explain: 'console has other methods — warn, error, table — but log is the workhorse.',
  },
  {
    id: 'js.comments.x1',
    concepts: ['js.comments'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which of these is a comment?',
    options: ['// note to self', '# note to self', '<!-- note -->', '" note "'],
    answer: [0],
    explain: 'Two slashes for one line, /* … */ for a block. The others belong to other languages.',
  },
  {
    id: 'js.vars.x1',
    concepts: ['js.variables'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which declaration should you reach for first?',
    options: ['const', 'let', 'var', 'It makes no difference'],
    answer: [0],
    explain: 'const unless you need to reassign, then let. var has scoping rules nobody wants back.',
  },
  {
    id: 'js.vars.x2',
    concepts: ['js.variables'],
    difficulty: 2,
    level: 2,
    kind: 'bug',
    prompt: 'Which line throws?',
    code: 'const score = 1;\nscore = 2;\nconsole.log(score);',
    buggyLine: 2,
    why: {
      options: [
        'A const binding cannot be reassigned',
        'score is not defined',
        'Numbers cannot be reassigned',
        'The semicolon is missing',
      ],
      answer: 0,
    },
    explain: 'const freezes the binding, not the value: you can still push to a const array.',
  },
  {
    id: 'js.types.x1',
    concepts: ['js.types'],
    difficulty: 2,
    level: 2,
    kind: 'match',
    prompt: 'Match each value to what typeof reports.',
    pairs: [
      ['42', '"number"'],
      ['"hi"', '"string"'],
      ['true', '"boolean"'],
      ['undefined', '"undefined"'],
    ],
    explain: 'typeof null is "object", which is a famous bug the language can never fix.',
  },
  {
    id: 'js.tmpl.x1',
    concepts: ['js.template'],
    difficulty: 2,
    level: 2,
    kind: 'blank',
    prompt: 'Greet the name using a template literal.',
    template: 'const name = "Sam";\nconsole.log({{0}}Hi, ${name}!{{1}});',
    blanks: [{ accept: ['`'], width: 2 }, { accept: ['`'], width: 2 }],
    explain: 'Backticks, not quotes. ${...} only interpolates inside a template literal.',
  },
  {
    id: 'js.cmp.x1',
    concepts: ['js.comparison'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'console.log(2 === "2");',
    options: ['false', 'true', 'an error', 'undefined'],
    answer: 0,
    explain: 'Three equals compares type as well as value. Use it and this whole category of bug disappears.',
  },
  {
    id: 'js.truthy.x1',
    concepts: ['js.truthy'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'Which of these is falsy?',
    options: ['""', '"0"', '[]', '{}'],
    answer: [0],
    explain: 'The falsy list is short: false, 0, -0, 0n, "", null, undefined, NaN. Everything else is truthy.',
  },
  {
    id: 'js.if.x1',
    concepts: ['js.if'],
    difficulty: 2,
    level: 2,
    kind: 'order',
    prompt: 'Put this check in order.',
    lines: ['const temp = 30;', 'if (temp > 25) {', '  console.log("hot");', '} else {', '  console.log("fine");', '}'],
    explain: 'The condition goes in brackets, the body in braces. Both are non-negotiable.',
  },
  {
    id: 'js.for.x1',
    concepts: ['js.for'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for (let i = 0; i < 3; i++) console.log(i);',
    options: ['0\n1\n2', '1\n2\n3', '0\n1\n2\n3', '3'],
    answer: 0,
    explain: 'Start, condition, step. The loop stops the moment the condition is false.',
  },
  {
    id: 'js.forof.x1',
    concepts: ['js.forof'],
    difficulty: 2,
    level: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for (const c of "ab") console.log(c);',
    options: ['a\nb', 'ab', '0\n1', 'an error'],
    answer: 0,
    explain: 'for...of walks values. for...in walks keys, which on a string means indexes.',
  },
  {
    id: 'js.arrays.x1',
    concepts: ['js.arrays'],
    difficulty: 1,
    level: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'const xs = [1, 2, 3];\nconsole.log(xs.length);',
    options: ['3', '2', '4', 'undefined'],
    answer: 0,
    explain: 'length counts items; the last index is always length - 1.',
  },
  {
    id: 'js.arrays.x2',
    concepts: ['js.arrays'],
    difficulty: 2,
    level: 2,
    kind: 'assemble',
    prompt: 'Add "c" to the end of the array.',
    answer: ['letters', '.', 'push', '(', '"c"', ')'],
    distractors: ['append', 'add'],
    explain: 'push adds to the end and returns the new length. pop takes one off.',
  },

  /* ------------------------------------------------------------ js.modules */
  {
    id: 'js.mod.1',
    concepts: ['js.modules'],
    difficulty: 3,
    level: 4,
    kind: 'match',
    prompt: 'Match each export to how it is imported.',
    pairs: [
      ['export function add() {}', 'import { add } from "./m.js"'],
      ['export default add', 'import add from "./m.js"'],
      ['export const PI = 3', 'import { PI } from "./m.js"'],
      ['export * from "./o.js"', 'Re-exports everything from another file'],
    ],
    explain: 'Braces mean named exports. No braces means the default one, and a file has at most one.',
  },
  {
    id: 'js.mod.2',
    concepts: ['js.modules'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'What is the practical difference between `import` and `require`?',
    options: [
      'import is the standard module system; require is CommonJS, from Node’s early days',
      'import is faster',
      'require works in browsers, import does not',
      'They are identical',
    ],
    answer: [0],
    explain: 'ES modules are static, which is what lets bundlers drop code you never import.',
  },
  {
    id: 'js.mod.3',
    concepts: ['js.npm'],
    difficulty: 3,
    level: 5,
    kind: 'terminal',
    prompt: 'Install the project’s dependencies exactly as the lockfile records them.',
    intro: ['~/app $ ls', 'package.json  package-lock.json  src'],
    cwd: '~/app',
    accept: ['npm ci'],
    output: ['added 214 packages in 3s'],
    explain: 'npm ci installs from the lockfile and fails if it disagrees with package.json. Use it in CI, always.',
  },
  {
    id: 'js.mod.4',
    concepts: ['js.npm'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What does the lockfile do that package.json does not?',
    options: [
      'Pins the exact version of every package, including packages of packages',
      'Lists the direct dependencies',
      'Stores the package source',
      'Describes the scripts',
    ],
    answer: [0],
    explain: 'Without it, two installs a week apart can produce different code with the same package.json.',
  },
  {
    id: 'js.mod.5',
    concepts: ['js.strict'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'Which is true of strict mode?',
    options: [
      'It is on automatically inside every ES module',
      'It has to be enabled per function',
      'It only affects performance',
      'It was removed in modern JavaScript',
    ],
    answer: [0],
    explain: 'Modules are strict by default: assigning to an undeclared variable throws instead of leaking a global.',
  },

  /* ------------------------------------------------------------- js.errors */
  {
    id: 'js.err.1',
    concepts: ['js.trycatch'],
    difficulty: 3,
    level: 4,
    kind: 'order',
    prompt: 'Handle a failure without taking the program down with it.',
    lines: ['try {', '  const data = JSON.parse(text);', '} catch (err) {', '  console.error("bad json", err.message);', '}'],
    explain: 'Catch as narrowly as you can. A try around a whole file hides the bug you needed to see.',
  },
  {
    id: 'js.err.2',
    concepts: ['js.throw'],
    difficulty: 4,
    level: 5,
    kind: 'choice',
    prompt: 'What should you throw?',
    options: [
      'new Error("something specific") — an Error object, with a message',
      'A string, so it is easy to read',
      'The value that failed',
      'false',
    ],
    answer: [0],
    explain: 'Only an Error carries a stack trace, and the stack is the thing you will want at 2am.',
  },
  {
    id: 'js.err.3',
    concepts: ['js.nullish'],
    difficulty: 3,
    level: 5,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'const count = 0;\nconsole.log(count || 10);\nconsole.log(count ?? 10);',
    options: ['10\n0', '0\n10', '0\n0', '10\n10'],
    answer: 0,
    explain: '|| falls through for any falsy value, including 0. ?? only for null and undefined.',
  },
  {
    id: 'js.err.4',
    concepts: ['js.nullish'],
    difficulty: 4,
    level: 6,
    kind: 'blank',
    prompt: 'Read a nested value without crashing when user has no address.',
    template: 'const city = user{{0}}address{{1}}city;',
    blanks: [{ accept: ['?.'], width: 3 }, { accept: ['?.'], width: 3 }],
    explain: 'Optional chaining short-circuits to undefined instead of throwing on null.',
  },
  {
    id: 'js.err.5',
    concepts: ['js.trycatch'],
    difficulty: 5,
    level: 7,
    kind: 'bug',
    prompt: 'The catch never fires. Which line is the reason?',
    code: 'try {\n  setTimeout(() => { throw new Error("late"); }, 10);\n} catch (err) {\n  console.log("caught");\n}',
    buggyLine: 2,
    why: {
      options: [
        'The callback runs later, on a different tick, long after the try block finished',
        'setTimeout cannot throw',
        'The error message is wrong',
        'catch needs a finally',
      ],
      answer: 0,
    },
    explain: 'try/catch is synchronous. Errors from a callback have to be handled inside the callback.',
  },

  /* ------------------------------------------------------------ js.classes */
  {
    id: 'js.cls.1',
    concepts: ['js.classes'],
    difficulty: 3,
    level: 5,
    kind: 'order',
    prompt: 'Write the smallest useful class.',
    lines: ['class Counter {', '  constructor() {', '    this.n = 0;', '  }', '  bump() {', '    this.n += 1;', '  }', '}'],
    explain: 'constructor sets up state, methods act on it. No commas between members.',
  },
  {
    id: 'js.cls.2',
    concepts: ['js.this'],
    difficulty: 4,
    level: 6,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'const obj = {\n  n: 1,\n  get() { return this.n; },\n};\nconst fn = obj.get;\nconsole.log(obj.get());',
    options: ['1', 'undefined', 'an error', 'null'],
    answer: 0,
    explain: 'Called as obj.get(), this is obj. Pulled out into fn and called alone, it would not be.',
  },
  {
    id: 'js.cls.3',
    concepts: ['js.this'],
    difficulty: 5,
    level: 7,
    kind: 'choice',
    prompt: 'Why does an arrow function help inside a class method?',
    options: [
      'It has no this of its own, so it keeps the one from where it was written',
      'It runs faster',
      'It binds this to the global object',
      'It cannot be passed as a callback',
    ],
    answer: [0],
    explain: 'That single rule is why callbacks written as arrows stopped needing .bind(this) everywhere.',
  },
  {
    id: 'js.cls.4',
    concepts: ['js.prototype'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'What is a class in JavaScript, underneath?',
    options: [
      'A function plus a prototype object that instances delegate to',
      'A separate kind of type, like in Java',
      'A frozen object',
      'A compile-time construct that disappears',
    ],
    answer: [0],
    explain: 'class is syntax over prototypes. Knowing that explains why methods are shared, not copied.',
  },
  {
    id: 'js.cls.5',
    concepts: ['js.classes'],
    difficulty: 5,
    level: 8,
    kind: 'write',
    prompt: 'Write a Stack class with push, pop and size, then print the results shown.',
    runLang: 'javascript',
    starter:
      'class Stack {\n  // your code\n}\n\nconst s = new Stack();\ns.push(1);\ns.push(2);\nconsole.log(s.size());\nconsole.log(s.pop());\nconsole.log(s.size());\n',
    solution:
      'class Stack {\n  constructor() {\n    this.items = [];\n  }\n  push(x) {\n    this.items.push(x);\n  }\n  pop() {\n    return this.items.pop();\n  }\n  size() {\n    return this.items.length;\n  }\n}\n\nconst s = new Stack();\ns.push(1);\ns.push(2);\nconsole.log(s.size());\nconsole.log(s.pop());\nconsole.log(s.size());\n',
    tests: [{ name: 'push, pop, size', expect: '2\n2\n1' }],
    mustContain: [{ pattern: 'class', label: 'use a class' }],
    explain: 'State in the constructor, behaviour in the methods. A stack is the smallest example that needs both.',
  },
]);
