import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

/* ============================================================================
   Python, continued.

   Two jobs. The first is the bottom of the ladder: a pile of level one and two
   questions about the things a first week is actually made of, so that nobody
   meets a list comprehension in lesson three. The second is the top of it —
   four more skills that take the course past "you can write a loop" and into
   files, modules, real data and tests.
   ========================================================================== */

export const pythonExtraSkills: Skill[] = [
  {
    id: 'py.files',
    title: 'Files and paths',
    blurb: 'Read a file without leaking a handle, and build a path that works on every machine.',
    concepts: ['py.files', 'py.with', 'py.pathlib'],
    requires: ['py.errors'],
    level: 'applied',
    tags: ['automation', 'data'],
    unit: 'Real programs',
  },
  {
    id: 'py.modules',
    title: 'Modules and the library',
    blurb: 'Import your own code, borrow the standard library, and keep projects apart.',
    concepts: ['py.imports', 'py.stdlib', 'py.venv'],
    requires: ['py.functions'],
    level: 'applied',
    tags: ['automation'],
    unit: 'Real programs',
  },
  {
    id: 'py.data',
    title: 'Real data',
    blurb: 'JSON, CSV and dataclasses — the three shapes most real Python data arrives in.',
    concepts: ['py.json', 'py.csv', 'py.dataclasses'],
    requires: ['py.classes', 'py.files'],
    level: 'applied',
    tags: ['data', 'automation'],
    unit: 'Data in the wild',
  },
  {
    id: 'py.craft',
    title: 'Tests and type hints',
    blurb: 'Prove your code works, and say what it expects.',
    concepts: ['py.assert', 'py.pytest', 'py.typing'],
    requires: ['py.functions'],
    level: 'advanced',
    tags: ['interviews', 'automation'],
    unit: 'Craft',
  },
];

export const pythonExtra = forTrack('python', [
  /* ------------------------------------------------ the bottom of the ladder */
  {
    id: 'py.print.x1',
    concepts: ['py.print'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which line prints the word hello?',
    options: ['print("hello")', 'echo "hello"', 'printf("hello")', 'console.log("hello")'],
    answer: [0],
    explain: 'print is a function, so the thing you want printed goes inside its brackets.',
  },
  {
    id: 'py.print.x2',
    concepts: ['py.print'],
    difficulty: 1,
    level: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("2 + 2")',
    options: ['2 + 2', '4', '"2 + 2"', 'nothing'],
    answer: 0,
    explain: 'Quotes make it text. Python prints the characters, it does not do the sum.',
  },
  {
    id: 'py.print.x3',
    concepts: ['py.print'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Print the word ready.',
    template: '{{0}}("ready")',
    blanks: [{ accept: ['print'], width: 5 }],
    explain: 'Every Python program starts here: print, brackets, the thing to show.',
  },
  {
    id: 'py.print.x4',
    concepts: ['py.print'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("a", "b")',
    options: ['a b', 'ab', 'a, b', '"a" "b"'],
    answer: 0,
    explain: 'Several arguments are printed with a space between them by default.',
  },
  {
    id: 'py.comments.x1',
    concepts: ['py.comments'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which line does Python ignore?',
    options: ['# this is a note', 'print("# hello")', '"a comment"', '// a note'],
    answer: [0],
    explain: 'A # starts a comment. Everything after it on that line is for humans only.',
  },
  {
    id: 'py.comments.x2',
    concepts: ['py.comments'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("hi")  # print("bye")',
    options: ['hi', 'bye', 'hi\nbye', 'nothing'],
    answer: 0,
    explain: 'The comment is not code, so the second print never happens.',
  },
  {
    id: 'py.errors.x1',
    concepts: ['py.errors'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'You see: NameError: name "totl" is not defined. What happened?',
    options: [
      'A name was misspelled, or used before it was given a value',
      'Python ran out of memory',
      'The file is missing',
      'A number was divided by zero',
    ],
    answer: [0],
    explain: 'A NameError almost always means a typo. Read the name it quotes back to you.',
  },
  {
    id: 'py.errors.x2',
    concepts: ['py.errors'],
    difficulty: 2,
    level: 2,
    kind: 'match',
    prompt: 'Match each error to what causes it.',
    pairs: [
      ['SyntaxError', 'A missing bracket or colon'],
      ['NameError', 'Using a name that does not exist'],
      ['TypeError', 'Adding a number to a string'],
      ['IndexError', 'Asking for item 10 of a 3-item list'],
    ],
    explain: 'The error type tells you which of four completely different mistakes you made.',
  },
  {
    id: 'py.vars.x1',
    concepts: ['py.variables'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Store the number 7 under the name score.',
    template: '{{0}} = 7',
    blanks: [{ accept: ['score'], width: 5 }],
    explain: 'A name on the left, a value on the right, and one equals sign between them.',
  },
  {
    id: 'py.vars.x2',
    concepts: ['py.variables'],
    difficulty: 1,
    level: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'name = "Sam"\nname = "Alex"\nprint(name)',
    options: ['Alex', 'Sam', 'Sam Alex', 'an error'],
    answer: 0,
    explain: 'Assigning again replaces the value. The name always points at the newest one.',
  },
  {
    id: 'py.types.x1',
    concepts: ['py.types'],
    difficulty: 1,
    level: 1,
    kind: 'match',
    prompt: 'Match each value to its type.',
    pairs: [
      ['42', 'int'],
      ['3.5', 'float'],
      ['"42"', 'str'],
      ['True', 'bool'],
    ],
    explain: 'Quotes make a string, a dot makes a float. "42" and 42 are not the same thing.',
  },
  {
    id: 'py.input.x1',
    concepts: ['py.input'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What type does input() always give you?',
    options: ['str', 'int', 'whatever was typed', 'float'],
    answer: [0],
    explain: 'Always a string. If you need a number, wrap it: int(input()).',
  },
  {
    id: 'py.arith.x1',
    concepts: ['py.arithmetic'],
    difficulty: 1,
    level: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(3 + 4 * 2)',
    options: ['11', '14', '24', '9'],
    answer: 0,
    explain: 'Multiplication happens before addition, exactly as in school maths.',
  },
  {
    id: 'py.arith.x2',
    concepts: ['py.arithmetic'],
    difficulty: 1,
    level: 1,
    kind: 'assemble',
    prompt: 'Build a line that prints ten minus three.',
    answer: ['print', '(', '10', '-', '3', ')'],
    distractors: ['+', 'echo'],
    explain: 'The expression is worked out first, then handed to print.',
  },
  {
    id: 'py.div.x1',
    concepts: ['py.division'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(-7 // 2)',
    options: ['-4', '-3', '-3.5', '3'],
    answer: 0,
    explain: '// floors, it does not chop: it rounds towards negative infinity, so -3.5 becomes -4 rather than -3.',
  },
  {
    id: 'py.cast.x1',
    concepts: ['py.casting'],
    difficulty: 2,
    level: 2,
    kind: 'bug',
    prompt: 'This should add the two numbers. Which line is wrong?',
    code: 'a = input("first: ")\nb = input("second: ")\nprint(a + b)',
    buggyLine: 3,
    why: {
      options: [
        'Both are strings, so + joins them instead of adding',
        'print cannot take an expression',
        'input needs no argument',
        'The names are wrong',
      ],
      answer: 0,
    },
    explain: 'int(a) + int(b) adds. Without the conversion you get "12" from 1 and 2.',
  },
  {
    id: 'py.str.x1',
    concepts: ['py.strings'],
    difficulty: 1,
    level: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("cod" + "ing")',
    options: ['coding', 'cod ing', 'cod+ing', 'an error'],
    answer: 0,
    explain: '+ glues two strings together exactly as they are — no space is added, which is the mistake to watch for.'
  },
  {
    id: 'py.fstr.x1',
    concepts: ['py.fstrings'],
    difficulty: 2,
    level: 2,
    kind: 'blank',
    prompt: 'Print "Hi, Sam!" using the name variable.',
    template: 'name = "Sam"\nprint({{0}}"Hi, {name}!")',
    blanks: [{ accept: ['f'], width: 2 }],
    explain: 'The f before the quote is what turns {name} into the value rather than the text.',
  },
  {
    id: 'py.bool.x1',
    concepts: ['py.booleans'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which of these is False?',
    options: ['0', '1', '"False"', '-1'],
    answer: [0],
    explain: 'Zero is false. Any non-zero number is true, and so is any non-empty string.',
  },
  {
    id: 'py.cmp.x1',
    concepts: ['py.comparison'],
    difficulty: 1,
    level: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(3 == 3.0)',
    options: ['True', 'False', 'an error', 'None'],
    answer: 0,
    explain: 'Python compares the values, not the types, so an int can equal a float.',
  },
  {
    id: 'py.if.x1',
    concepts: ['py.if'],
    difficulty: 2,
    level: 2,
    kind: 'order',
    prompt: 'Put this check in order.',
    lines: ['age = 20', 'if age >= 18:', '    print("adult")', 'else:', '    print("minor")'],
    explain: 'The colon opens the block, and the indented lines are what runs inside it.',
  },
  {
    id: 'py.if.x2',
    concepts: ['py.if'],
    difficulty: 2,
    level: 2,
    kind: 'bug',
    prompt: 'Which line stops this from running?',
    code: 'score = 10\nif score > 5\n    print("pass")',
    buggyLine: 2,
    why: {
      options: ['The if line is missing its colon', 'score is not defined', 'print is misspelled', 'The indent is wrong'],
      answer: 0,
    },
    explain: 'Every if, for, while and def line ends in a colon. Forgetting it is a SyntaxError.',
  },
  {
    id: 'py.for.x1',
    concepts: ['py.for'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for letter in "hi":\n    print(letter)',
    options: ['h\ni', 'hi', 'h i', '0\n1'],
    answer: 0,
    explain: 'A string is a sequence of characters, so a for loop walks it one letter at a time.',
  },
  {
    id: 'py.range.x1',
    concepts: ['py.range'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for i in range(3):\n    print(i)',
    options: ['0\n1\n2', '1\n2\n3', '0\n1\n2\n3', '3'],
    answer: 0,
    explain: 'range starts at zero and stops before the number you gave it.',
  },
  {
    id: 'py.lists.x1',
    concepts: ['py.lists'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which one makes a list of three numbers?',
    options: ['[1, 2, 3]', '(1, 2, 3)', '{1: 2, 3: 4}', '"1, 2, 3"'],
    answer: [0],
    explain: 'Square brackets make a list. Round brackets make a tuple, which cannot be changed.',
  },
  {
    id: 'py.index.x1',
    concepts: ['py.indexing'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'names = ["a", "b", "c"]\nprint(names[0], names[-1])',
    options: ['a c', 'a b', 'b c', 'an error'],
    answer: 0,
    explain: 'Counting starts at zero, and -1 is the shortest way to say "the last one".',
  },

  /* -------------------------------------------------------------- py.files */
  {
    id: 'py.files.1',
    concepts: ['py.with', 'py.files'],
    difficulty: 2,
    level: 4,
    kind: 'choice',
    prompt: 'Why open a file with `with open(path) as f:` rather than `f = open(path)`?',
    options: [
      'The file is closed for you, even if the code inside raises',
      'It reads the file faster',
      'It is the only way to read text',
      'It locks the file against other programs',
    ],
    answer: [0],
    explain: 'with is a promise to clean up. Handles left open are a classic slow leak.',
  },
  {
    id: 'py.files.2',
    concepts: ['py.files'],
    difficulty: 3,
    level: 5,
    kind: 'match',
    prompt: 'Match each file mode to what it does.',
    pairs: [
      ['"r"', 'Read; fails if the file is missing'],
      ['"w"', 'Write; empties the file first'],
      ['"a"', 'Append to the end'],
      ['"x"', 'Create; fails if it already exists'],
    ],
    explain: 'Reaching for "w" when you meant "a" is how people delete their own data.',
  },
  {
    id: 'py.files.3',
    concepts: ['py.files'],
    difficulty: 3,
    level: 5,
    kind: 'order',
    prompt: 'Put together a loop that prints every line of a file without the trailing newlines.',
    lines: ['with open("notes.txt") as f:', '    for line in f:', '        print(line.rstrip())'],
    decoys: ['    f.close()'],
    explain: 'A file object is iterable, and with closes it — the explicit close is not needed.',
  },
  {
    id: 'py.files.4',
    concepts: ['py.pathlib'],
    difficulty: 3,
    level: 6,
    kind: 'choice',
    prompt: 'Which builds a path that works on Windows as well as Linux?',
    options: [
      'Path("data") / "raw" / "in.csv"',
      '"data" + "/" + "raw" + "/" + "in.csv"',
      '"data\\\\raw\\\\in.csv"',
      'os.path.join("data/raw/in.csv")',
    ],
    answer: [0],
    explain: 'pathlib uses the right separator for the machine it is running on. Slashes glued by hand do not.',
  },
  {
    id: 'py.files.5',
    concepts: ['py.pathlib'],
    difficulty: 4,
    level: 6,
    kind: 'blank',
    prompt: 'Read a whole file into a string with pathlib.',
    template: 'from pathlib import Path\ntext = Path("in.txt").{{0}}()',
    blanks: [{ accept: ['read_text'], width: 10 }],
    explain: 'read_text opens, reads and closes in one call — the shortest correct way to slurp a file.',
  },
  {
    id: 'py.files.6',
    concepts: ['py.with'],
    difficulty: 4,
    level: 7,
    kind: 'bug',
    prompt: 'This writes a report. Which line is the problem?',
    code: 'rows = ["a", "b"]\nf = open("out.txt", "w")\nfor row in rows:\n    f.write(row)',
    buggyLine: 2,
    why: {
      options: [
        'The file is never closed, so the writes may never reach disk',
        'open cannot take a mode',
        'write needs a list',
        'The loop variable shadows something',
      ],
      answer: 0,
    },
    explain: 'Without with (or an explicit close) the buffer can still be unflushed when the program ends.',
  },

  /* ------------------------------------------------------------ py.modules */
  {
    id: 'py.mod.1',
    concepts: ['py.imports'],
    difficulty: 2,
    level: 4,
    kind: 'choice',
    prompt: 'What does `from math import sqrt` do that `import math` does not?',
    options: [
      'Puts sqrt straight into your namespace, so you call it as sqrt(9)',
      'Loads the module faster',
      'Imports only part of the file',
      'Nothing, they are identical',
    ],
    answer: [0],
    explain: 'Both load the whole module. The difference is only what name you end up with.',
  },
  {
    id: 'py.mod.2',
    concepts: ['py.imports'],
    difficulty: 3,
    level: 5,
    kind: 'predict',
    prompt: 'helpers.py contains `VALUE = 2`. What does this print?',
    code: 'import helpers\nhelpers.VALUE = 5\nprint(helpers.VALUE)',
    options: ['5', '2', 'an error', 'None'],
    answer: 0,
    explain: 'A module is an object. Assigning to its attribute really does change it for everyone who imported it.',
  },
  {
    id: 'py.mod.3',
    concepts: ['py.stdlib'],
    difficulty: 3,
    level: 5,
    kind: 'match',
    prompt: 'Match each standard library module to the job it does.',
    pairs: [
      ['json', 'Text in, dicts out'],
      ['datetime', 'Dates and durations'],
      ['random', 'Shuffling and dice'],
      ['collections', 'Counter, deque, defaultdict'],
    ],
    explain: 'Most "I need a library for this" moments in Python are already answered by the standard one.',
  },
  {
    id: 'py.mod.4',
    concepts: ['py.stdlib'],
    difficulty: 3,
    level: 6,
    kind: 'blank',
    prompt: 'Count how often each word appears, using the standard library.',
    template: 'from collections import {{0}}\ncounts = {{0}}(words)',
    blanks: [{ accept: ['Counter'], width: 8 }, { accept: ['Counter'], width: 8 }],
    explain: 'Counter is a dict that counts. Writing the loop by hand is three lines you do not need.',
  },
  {
    id: 'py.mod.5',
    concepts: ['py.venv'],
    difficulty: 3,
    level: 6,
    kind: 'choice',
    prompt: 'What is a virtual environment for?',
    options: [
      'Keeping one project’s package versions from breaking another project',
      'Making Python run faster',
      'Sandboxing untrusted code',
      'Running several Python versions at once',
    ],
    answer: [0],
    explain: 'Two projects wanting different versions of the same library is the whole reason venvs exist.',
  },
  {
    id: 'py.mod.6',
    concepts: ['py.imports'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'Why is `if __name__ == "__main__":` at the bottom of a script?',
    options: [
      'So the code below only runs when the file is run directly, not when it is imported',
      'It is required by Python for any script',
      'It makes the file importable',
      'It speeds up start-up',
    ],
    answer: [0],
    explain: 'Without it, importing your script for its functions also runs the whole program.',
  },

  /* --------------------------------------------------------------- py.data */
  {
    id: 'py.data.1',
    concepts: ['py.json'],
    difficulty: 3,
    level: 5,
    kind: 'match',
    prompt: 'Match each json function to what it takes and gives back.',
    pairs: [
      ['json.loads', 'String in, Python object out'],
      ['json.dumps', 'Python object in, string out'],
      ['json.load', 'File in, Python object out'],
      ['json.dump', 'Object and file in, nothing out'],
    ],
    explain: 'The s stands for string. That single letter is the whole difference between the pairs.',
  },
  {
    id: 'py.data.2',
    concepts: ['py.json'],
    difficulty: 3,
    level: 6,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'import json\nprint(json.dumps({"a": 1, "b": True}))',
    options: ['{"a": 1, "b": true}', "{'a': 1, 'b': True}", '{"a": 1, "b": True}', 'an error'],
    answer: 0,
    explain: 'JSON is not Python: strings get double quotes and True becomes true.',
  },
  {
    id: 'py.data.3',
    concepts: ['py.csv'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'Why use the csv module rather than line.split(",")?',
    options: [
      'It handles quoted fields that contain commas',
      'It is faster on large files',
      'split does not exist for file lines',
      'It sorts the rows',
    ],
    answer: [0],
    explain: 'One address field with a comma in it is all it takes for hand-rolled splitting to corrupt a dataset.',
  },
  {
    id: 'py.data.4',
    concepts: ['py.csv'],
    difficulty: 4,
    level: 7,
    kind: 'order',
    prompt: 'Read a CSV with a header row and print each row as a dict.',
    lines: [
      'import csv',
      'with open("people.csv", newline="") as f:',
      '    for row in csv.DictReader(f):',
      '        print(row["name"])',
    ],
    explain: 'DictReader reads the header once and hands you a dict per row, which beats counting columns.',
  },
  {
    id: 'py.data.5',
    concepts: ['py.dataclasses'],
    difficulty: 4,
    level: 7,
    kind: 'blank',
    prompt: 'Turn this into a dataclass.',
    template: 'from dataclasses import dataclass\n\n@{{0}}\nclass Point:\n    x: int\n    y: int',
    blanks: [{ accept: ['dataclass'], width: 10 }],
    explain: 'The decorator writes __init__, __repr__ and __eq__ for you from the annotations.',
  },
  {
    id: 'py.data.6',
    concepts: ['py.dataclasses'],
    difficulty: 5,
    level: 8,
    kind: 'bug',
    prompt: 'Every Basket ends up sharing one list. Which line is the cause?',
    code: '@dataclass\nclass Basket:\n    items: list = []\n    owner: str = ""',
    buggyLine: 3,
    why: {
      options: [
        'A mutable default is shared by every instance; it needs field(default_factory=list)',
        'list is not a valid annotation',
        'Defaults must come last',
        'The class needs an __init__',
      ],
      answer: 0,
    },
    explain: 'Python evaluates the default once, at class creation. Dataclasses refuse mutable defaults for exactly this reason.',
  },

  /* -------------------------------------------------------------- py.craft */
  {
    id: 'py.craft.1',
    concepts: ['py.assert'],
    difficulty: 3,
    level: 5,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'def half(n):\n    assert n % 2 == 0, "odd"\n    return n // 2\n\nprint(half(8))',
    options: ['4', 'odd', 'an AssertionError', 'None'],
    answer: 0,
    explain: 'The assertion passes, so it is invisible. It only speaks up when the assumption is broken.',
  },
  {
    id: 'py.craft.2',
    concepts: ['py.assert'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'Why should asserts not be used to validate user input?',
    options: [
      'They can be stripped out entirely when Python runs with -O',
      'They are slower than an if',
      'They cannot carry a message',
      'They only work inside functions',
    ],
    answer: [0],
    explain: 'Asserts state what you believe about your own code. Input checks have to survive optimisation.',
  },
  {
    id: 'py.craft.3',
    concepts: ['py.pytest'],
    difficulty: 4,
    level: 6,
    kind: 'order',
    prompt: 'Write the smallest useful pytest file.',
    lines: ['from mymath import add', '', 'def test_add():', '    assert add(2, 2) == 4'],
    explain: 'pytest finds files named test_*.py and functions named test_*. There is no framework to set up.',
  },
  {
    id: 'py.craft.4',
    concepts: ['py.typing'],
    difficulty: 4,
    level: 7,
    kind: 'blank',
    prompt: 'Annotate a function that takes a list of ints and returns an int.',
    template: 'def total(values: {{0}}[int]) -> {{1}}:\n    return sum(values)',
    blanks: [{ accept: ['list', 'List'], width: 5 }, { accept: ['int'], width: 4 }],
    explain: 'Since 3.9 the built-in list works as an annotation; typing.List is the older spelling.',
  },
  {
    id: 'py.craft.5',
    concepts: ['py.typing'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'What does Python itself do with type hints at runtime?',
    options: [
      'Nothing — they are stored, but never enforced',
      'Raises TypeError when a call does not match',
      'Converts arguments to the annotated type',
      'Refuses to import the module',
    ],
    answer: [0],
    explain: 'Hints are for you, your editor and mypy. The interpreter is completely uninterested.',
  },
  {
    id: 'py.craft.6',
    concepts: ['py.pytest', 'py.assert'],
    difficulty: 5,
    level: 8,
    kind: 'write',
    prompt: 'Write clamp(value, low, high): return low if value is below it, high if above, otherwise value.',
    runLang: 'python',
    starter: 'def clamp(value, low, high):\n    pass\n\nprint(clamp(5, 0, 10))\nprint(clamp(-3, 0, 10))\nprint(clamp(42, 0, 10))\n',
    solution:
      'def clamp(value, low, high):\n    if value < low:\n        return low\n    if value > high:\n        return high\n    return value\n\nprint(clamp(5, 0, 10))\nprint(clamp(-3, 0, 10))\nprint(clamp(42, 0, 10))\n',
    tests: [{ name: 'inside, below and above', expect: '5\n0\n10' }],
    explain: 'Three cases, and the middle one is the easy one to forget. Tests exist to catch exactly that.',
  },
]);
