import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'py.first',
    title: 'Your first lines',
    blurb: 'Print things out, leave notes for yourself, and read an error without panicking.',
    concepts: ['py.print', 'py.comments', 'py.errors'],
    requires: [],
    level: 'intro',
    tags: ['automation'],
    unit: 'Getting started',
  },
  {
    id: 'py.vars',
    title: 'Names and values',
    blurb: 'Store something, name it well, and find out what type it is.',
    concepts: ['py.variables', 'py.types', 'py.input'],
    requires: ['py.first'],
    level: 'intro',
    tags: ['automation'],
    unit: 'Getting started',
  },
  {
    id: 'py.numbers',
    title: 'Numbers and maths',
    blurb: 'Integer versus float, the two kinds of division, and converting between types.',
    concepts: ['py.arithmetic', 'py.division', 'py.casting'],
    requires: ['py.vars'],
    level: 'core',
    tags: ['data'],
    unit: 'Working with data',
  },
  {
    id: 'py.strings',
    title: 'Strings',
    blurb: 'Build text, slice it apart, and format it the modern way.',
    concepts: ['py.strings', 'py.fstrings', 'py.strmethods', 'py.slicing'],
    requires: ['py.vars'],
    level: 'core',
    tags: ['automation', 'web'],
    unit: 'Working with data',
  },
  {
    id: 'py.logic',
    title: 'Making decisions',
    blurb: 'Booleans, comparisons, and branching with if / elif / else.',
    concepts: ['py.booleans', 'py.comparison', 'py.if'],
    requires: ['py.vars'],
    level: 'core',
    tags: ['interviews'],
    unit: 'Control flow',
  },
  {
    id: 'py.loops',
    title: 'Repeating work',
    blurb: 'for, while, range, and knowing when to break out.',
    concepts: ['py.for', 'py.while', 'py.range', 'py.loopcontrol'],
    requires: ['py.logic'],
    level: 'core',
    tags: ['automation', 'interviews'],
    unit: 'Control flow',
  },
  {
    id: 'py.lists',
    title: 'Lists',
    blurb: 'Ordered collections, indexing from both ends, and the methods that change them.',
    concepts: ['py.lists', 'py.indexing', 'py.listmethods'],
    requires: ['py.loops'],
    level: 'core',
    tags: ['data', 'interviews'],
    unit: 'Collections',
  },
  {
    id: 'py.dicts',
    title: 'Dictionaries and sets',
    blurb: 'Look things up by key instead of by position, and throw away duplicates.',
    concepts: ['py.dicts', 'py.dictmethods', 'py.sets'],
    requires: ['py.lists'],
    level: 'core',
    tags: ['data', 'interviews'],
    unit: 'Collections',
  },
  {
    id: 'py.functions',
    title: 'Functions',
    blurb: 'Name a piece of work, give it inputs, get something back.',
    concepts: ['py.functions', 'py.arguments', 'py.return', 'py.scope'],
    requires: ['py.loops'],
    level: 'core',
    tags: ['automation', 'apps'],
    unit: 'Structure',
  },
  {
    id: 'py.comprehensions',
    title: 'Comprehensions and sorting',
    blurb: 'Build a list in one line, and sort by whatever you like.',
    concepts: ['py.comprehension', 'py.sorting'],
    requires: ['py.functions', 'py.dicts'],
    level: 'applied',
    tags: ['data'],
    unit: 'Structure',
  },
  {
    id: 'py.errors',
    title: 'When things go wrong',
    blurb: 'Read a traceback, catch what you expect, and let the rest crash loudly.',
    concepts: ['py.exceptions', 'py.debugging'],
    requires: ['py.functions'],
    level: 'applied',
    tags: ['automation', 'apps'],
    unit: 'Real programs',
  },
  {
    id: 'py.classes',
    title: 'Classes',
    blurb: 'Bundle data with the code that works on it.',
    concepts: ['py.classes', 'py.methods', 'py.attributes'],
    requires: ['py.functions'],
    level: 'advanced',
    tags: ['apps', 'games'],
    unit: 'Real programs',
  },
];

export const pythonTrack: Track = {
  id: 'python',
  name: 'Python',
  kind: 'language',
  tagline: 'The one that reads like English',
  blurb:
    'Gentle syntax, enormous reach: scripting, data, servers, machine learning. The best first language for most people, and the one you will keep reaching for.',
  lang: 'python',
  runLang: 'python',
  mark: 'Py',
  tags: ['automation', 'data', 'apps', 'interviews'],
  goals: ['automation', 'data', 'apps', 'interviews', 'curious'],
  slope: 2,
  transfersFrom: [],
  skills,
};

export const pythonExercises = forTrack('python', [
  /* ------------------------------------------------------------ py.first */
  {
    id: 'py.print.1',
    concepts: ['py.print'],
    difficulty: 1,
    kind: 'assemble',
    prompt: 'Build the line that prints Hello, world!',
    answer: ['print', '(', '"Hello, world!"', ')'],
    distractors: ['echo', 'console.log', ';'],
    explain: 'print() is a function: the name, then round brackets holding what you want shown.',
    hint: 'Python has no semicolons and no console.log.',
  },
  {
    id: 'py.print.2',
    concepts: ['py.print'],
    difficulty: 1,
    kind: 'choice',
    prompt: 'Which of these prints the number 42, not the text "42"?',
    options: ['print("42")', 'print(42)', "print('42')", 'print(4, 2)'],
    answer: [1],
    explain: 'Quotes make it text. Without quotes it is a number you can do maths with.',
  },
  {
    id: 'py.print.3',
    concepts: ['py.print'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("a", "b", "c")',
    options: ['abc', 'a b c', 'a, b, c', '("a", "b", "c")'],
    answer: 1,
    explain: 'print() joins its arguments with a single space by default. Pass sep="" to change that.',
  },
  {
    id: 'py.print.4',
    concepts: ['py.print'],
    difficulty: 2,
    kind: 'write',
    prompt: 'Print your two favourite things, one per line.',
    runLang: 'python',
    starter: '# Print two lines\n',
    solution: 'print("coffee")\nprint("silence")',
    tests: [{ name: 'prints two lines', expect: '', expectContains: ['\n', '\n'] }],
    mustContain: [{ pattern: 'print', label: 'use print()' }],
    explain: 'Two print() calls means two lines: each one ends with a newline for you.',
  },
  {
    id: 'py.comments.1',
    concepts: ['py.comments'],
    difficulty: 1,
    kind: 'choice',
    prompt: 'How do you write a comment that Python ignores?',
    options: ['// a note', '/* a note */', '# a note', '<!-- a note -->'],
    answer: [2],
    explain: 'Python uses #. Everything after it on that line is for humans only.',
  },
  {
    id: 'py.comments.2',
    concepts: ['py.comments', 'py.print'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("one")\n# print("two")\nprint("three")',
    options: ['one\ntwo\nthree', 'one\nthree', 'one', 'three'],
    answer: 1,
    explain: 'The commented line never runs. Commenting a line out is the quickest debugging tool there is.',
  },
  {
    id: 'py.errors.1',
    concepts: ['py.errors'],
    difficulty: 2,
    kind: 'bug',
    prompt: 'One line will not run. Which?',
    code: 'print("start")\nprint("middle"\nprint("end")',
    buggyLine: 2,
    why: {
      options: ['The text is wrong', 'A closing bracket is missing', 'print is misspelled'],
      answer: 1,
    },
    explain: 'Python reports a SyntaxError on the *next* line, because it kept reading, hoping for the bracket.',
  },
  {
    id: 'py.errors.2',
    concepts: ['py.errors'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each error to what causes it.',
    pairs: [
      ['NameError', 'Using a variable you never created'],
      ['SyntaxError', 'Python cannot even read the line'],
      ['TypeError', 'Doing something a value does not support'],
    ],
    explain: 'The error name is the fastest clue you get. Read it before you read anything else.',
  },
  {
    id: 'py.errors.3',
    concepts: ['py.errors', 'py.print'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'Where should you look first in a Python traceback?',
    options: [
      'The first line',
      'The last line, then the line number just above it',
      'The middle',
      'The file name only',
    ],
    answer: [1],
    explain: 'Python prints the error type and message last. Read it bottom-up.',
  },

  /* ------------------------------------------------------------- py.vars */
  {
    id: 'py.vars.1',
    concepts: ['py.variables'],
    difficulty: 1,
    kind: 'blank',
    prompt: 'Store the number 7 in a variable called lucky.',
    template: '{{0}} = {{1}}',
    blanks: [{ accept: ['lucky'], width: 6 }, { accept: ['7'], width: 3 }],
    explain: 'A single = assigns. The name goes on the left, the value on the right.',
  },
  {
    id: 'py.vars.2',
    concepts: ['py.variables'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'x = 5\ny = x\nx = 9\nprint(y)',
    options: ['5', '9', '14', 'None'],
    answer: 0,
    explain: 'y copied the value 5. Re-pointing x later does not reach back and change y.',
  },
  {
    id: 'py.vars.3',
    concepts: ['py.variables'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'Which is NOT a legal Python variable name?',
    options: ['user_name', '_total', '2fast', 'itemCount'],
    answer: [2],
    explain: 'Names may contain digits but cannot start with one.',
  },
  {
    id: 'py.types.1',
    concepts: ['py.types'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each value to its type.',
    pairs: [
      ['42', 'int'],
      ['"42"', 'str'],
      ['4.2', 'float'],
      ['True', 'bool'],
    ],
    explain: 'Quotes always mean str, a dot always means float. type(x) will tell you at any time.',
  },
  {
    id: 'py.types.2',
    concepts: ['py.types', 'py.errors'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What happens here?',
    code: 'age = "30"\nprint(age + 1)',
    options: ['31', '"301"', 'TypeError', '301'],
    answer: 2,
    explain: 'age is text, not a number. Python refuses to guess; convert it with int(age) first.',
  },
  {
    id: 'py.input.1',
    concepts: ['py.input', 'py.types'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What type does input() always return?',
    options: ['int', 'str', 'whatever the user typed', 'float'],
    answer: [1],
    explain: 'Always a string, even when the user types 42. Wrap it in int() when you need a number.',
  },
  {
    id: 'py.input.2',
    concepts: ['py.input'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Read a name from input and greet it: "Hello, Ada!" for the input Ada.',
    runLang: 'python',
    starter: 'name = input()\n# print the greeting\n',
    solution: 'name = input()\nprint("Hello, " + name + "!")',
    tests: [
      { name: 'Ada', stdin: 'Ada', expect: 'Hello, Ada!' },
      { name: 'Grace', stdin: 'Grace', expect: 'Hello, Grace!' },
    ],
    explain: 'input() hands you a string, so you can join it straight onto other strings with +.',
    hint: 'Remember the exclamation mark at the end.',
  },

  /* ---------------------------------------------------------- py.numbers */
  {
    id: 'py.arith.1',
    concepts: ['py.arithmetic'],
    difficulty: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(2 + 3 * 4)',
    options: ['20', '14', '24', '9'],
    answer: 1,
    explain: 'Multiplication runs before addition, exactly as in school maths. Brackets override it.',
  },
  {
    id: 'py.arith.2',
    concepts: ['py.arithmetic'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each operator to what it does.',
    pairs: [
      ['**', 'raise to a power'],
      ['%', 'remainder after division'],
      ['//', 'divide and throw away the fraction'],
      ['/', 'divide, always giving a float'],
    ],
    explain: 'The two division operators are the ones people mix up. // floors, / does not.',
  },
  {
    id: 'py.arith.3',
    concepts: ['py.arithmetic'],
    difficulty: 2,
    kind: 'blank',
    prompt: 'Add 3 to the score, in the short form.',
    template: 'score {{0}} 3',
    blanks: [{ accept: ['+='], width: 4 }],
    explain: 'score += 3 is exactly score = score + 3, and every operator has this short form.',
  },
  {
    id: 'py.div.1',
    concepts: ['py.division'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(7 / 2)\nprint(7 // 2)',
    options: ['3.5\n3', '3\n3.5', '3.5\n3.5', '3\n3'],
    answer: 0,
    explain: '/ always gives a float, even for 4 / 2. // floors the result towards negative infinity.',
  },
  {
    id: 'py.div.2',
    concepts: ['py.division'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(10 % 3)',
    options: ['3', '1', '3.33', '0'],
    answer: 1,
    explain: '10 divided by 3 is 3 with 1 left over. % is how you test "is this divisible?" — n % 2 == 0 means even.',
  },
  {
    id: 'py.div.3',
    concepts: ['py.division', 'py.errors'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does 5 / 0 do?',
    options: ['Gives 0', 'Gives infinity', 'Raises ZeroDivisionError', 'Gives None'],
    answer: [2],
    explain: 'Python stops rather than inventing an answer. Check the divisor before dividing by it.',
  },
  {
    id: 'py.cast.1',
    concepts: ['py.casting'],
    difficulty: 2,
    kind: 'assemble',
    prompt: 'Turn the text "30" into the number 30.',
    answer: ['int', '(', '"30"', ')'],
    distractors: ['str', 'float', 'number'],
    explain: 'int() parses text into a whole number. It raises ValueError if the text is not a number.',
  },
  {
    id: 'py.cast.2',
    concepts: ['py.casting'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(int(3.9))',
    options: ['4', '3', '3.9', 'Error'],
    answer: 1,
    explain: 'int() truncates towards zero, it does not round. Use round() when you want 4.',
  },
  {
    id: 'py.numbers.write.1',
    concepts: ['py.arithmetic', 'py.casting'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Read two numbers from input, one per line, and print their sum.',
    runLang: 'python',
    starter: 'a = int(input())\n# read b and print the sum\n',
    solution: 'a = int(input())\nb = int(input())\nprint(a + b)',
    tests: [
      { name: '2 + 3', stdin: '2\n3', expect: '5' },
      { name: '10 + -4', stdin: '10\n-4', expect: '6' },
      { name: '0 + 0', stdin: '0\n0', expect: '0', hidden: true },
    ],
    explain: 'Convert first, add second. Forgetting int() would concatenate the text instead: "23".',
  },

  /* ---------------------------------------------------------- py.strings */
  {
    id: 'py.str.1',
    concepts: ['py.strings'],
    difficulty: 1,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("ab" * 3)',
    options: ['ababab', 'ab3', 'Error', 'ab ab ab'],
    answer: 0,
    explain: 'Multiplying a string repeats it. "-" * 40 is the quickest divider line you will ever write.',
  },
  {
    id: 'py.str.2',
    concepts: ['py.strings'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'Which expression joins first and last with a space between them?',
    options: ['first + last', 'first + " " + last', 'first, last', 'first " " last'],
    answer: [1],
    explain: '+ glues strings together exactly as written, so the space has to be there on purpose.',
  },
  {
    id: 'py.fstr.1',
    concepts: ['py.fstrings'],
    difficulty: 2,
    kind: 'blank',
    prompt: 'Complete the f-string so it prints "You have 3 messages".',
    template: 'n = 3\nprint({{0}}"You have {n} messages")',
    blanks: [{ accept: ['f'], width: 2 }],
    explain: 'The f prefix turns {n} into the value of n. Without it you get the literal braces.',
  },
  {
    id: 'py.fstr.2',
    concepts: ['py.fstrings'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'price = 3.14159\nprint(f"{price:.2f}")',
    options: ['3.14159', '3.14', '3.1', '3'],
    answer: 1,
    explain: 'The bit after the colon is a format spec. .2f means "fixed point, two decimals".',
  },
  {
    id: 'py.fstr.3',
    concepts: ['py.fstrings', 'py.arithmetic'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Print "5 squared is 25" using an f-string, for the number read from input.',
    runLang: 'python',
    starter: 'n = int(input())\n# print the sentence\n',
    solution: 'n = int(input())\nprint(f"{n} squared is {n ** 2}")',
    tests: [
      { name: '5', stdin: '5', expect: '5 squared is 25' },
      { name: '12', stdin: '12', expect: '12 squared is 144' },
    ],
    mustContain: [{ pattern: 'f"', label: 'use an f-string' }],
    explain: 'Any expression fits inside the braces, including arithmetic like n ** 2.',
  },
  {
    id: 'py.strm.1',
    concepts: ['py.strmethods'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each string method to its result on "  Hello World  ".',
    pairs: [
      ['.strip()', '"Hello World"'],
      ['.upper()', '"  HELLO WORLD  "'],
      ['.replace("o", "0")', '"  Hell0 W0rld  "'],
    ],
    explain: 'String methods never change the original — they return a new string. Assign the result.',
  },
  {
    id: 'py.strm.2',
    concepts: ['py.strmethods'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("a,b,c".split(","))',
    options: ["['a', 'b', 'c']", "'a b c'", "['a,b,c']", "('a', 'b', 'c')"],
    answer: 0,
    explain: 'split() cuts a string into a list. join() is its opposite: ",".join(parts).',
  },
  {
    id: 'py.strm.3',
    concepts: ['py.strmethods'],
    difficulty: 3,
    kind: 'bug',
    prompt: 'This is meant to shout the name. Which line is wrong?',
    code: 'name = "  ada  "\nname.strip()\nname.upper()\nprint(name)',
    buggyLine: 2,
    why: {
      options: [
        'strip() is spelled wrong',
        'The result is thrown away instead of being stored',
        'You cannot call two methods on one string',
      ],
      answer: 1,
    },
    explain: 'Strings are immutable. name = name.strip().upper() keeps the result.',
  },
  {
    id: 'py.slice.1',
    concepts: ['py.slicing'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'word = "python"\nprint(word[0:3])',
    options: ['pyt', 'pyth', 'yth', 'ytho'],
    answer: 0,
    explain: 'Slices include the start and exclude the end, so [0:3] is characters 0, 1 and 2.',
  },
  {
    id: 'py.slice.2',
    concepts: ['py.slicing'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print("python"[::-1])',
    options: ['python', 'nohtyp', 'p', 'nohty'],
    answer: 1,
    explain: 'A step of -1 walks backwards. [::-1] is the idiomatic Python reverse.',
  },
  {
    id: 'py.slice.3',
    concepts: ['py.slicing', 'py.indexing'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Get the last character of word.',
    template: 'word[{{0}}]',
    blanks: [{ accept: ['-1'], width: 4 }],
    explain: 'Negative indexes count from the end: -1 is last, -2 second to last.',
  },

  /* ------------------------------------------------------------ py.logic */
  {
    id: 'py.bool.1',
    concepts: ['py.booleans'],
    difficulty: 1,
    kind: 'choice',
    prompt: 'Which of these is False?',
    options: ['True and True', 'True or False', 'not True', '1 == 1'],
    answer: [2],
    explain: 'not flips a boolean. and needs both sides; or needs only one.',
  },
  {
    id: 'py.bool.2',
    concepts: ['py.booleans'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(bool(0), bool(""), bool([]), bool("no"))',
    options: [
      'False False False True',
      'True True True True',
      'False False False False',
      'True False True False',
    ],
    answer: 0,
    explain: 'Zero, empty text and empty containers are falsy. Everything else is truthy — including the string "False".',
  },
  {
    id: 'py.cmp.1',
    concepts: ['py.comparison'],
    difficulty: 1,
    kind: 'choice',
    prompt: 'Which operator asks "are these equal?"',
    options: ['=', '==', '=>', ':='],
    answer: [1],
    explain: 'One = assigns, two == compares. Mixing them up is the most common beginner bug in every language.',
  },
  {
    id: 'py.cmp.2',
    concepts: ['py.comparison'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(3 <= 3, "b" > "a", 2 != 2)',
    options: ['True True False', 'False True False', 'True False True', 'True True True'],
    answer: 0,
    explain: 'Strings compare alphabetically by character code, so "b" > "a" is True.',
  },
  {
    id: 'py.if.1',
    concepts: ['py.if'],
    difficulty: 2,
    kind: 'order',
    prompt: 'Put this age check in the right order.',
    lines: ['age = 20', 'if age >= 18:', '    print("adult")', 'else:', '    print("minor")'],
    explain: 'The colon opens a block, and the indent is what actually puts a line inside it.',
  },
  {
    id: 'py.if.2',
    concepts: ['py.if'],
    difficulty: 3,
    kind: 'bug',
    prompt: 'This should print "big" for 100. Which line is wrong?',
    code: 'n = 100\nif n > 10\n    print("big")',
    buggyLine: 2,
    why: {
      options: ['The colon is missing', 'n is not defined', 'The indent is wrong'],
      answer: 0,
    },
    explain: 'Every block header in Python ends with a colon: if, elif, else, for, while, def, class.',
  },
  {
    id: 'py.if.3',
    concepts: ['py.if', 'py.comparison'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Read a number and print "even" or "odd".',
    runLang: 'python',
    starter: 'n = int(input())\n',
    solution: 'n = int(input())\nif n % 2 == 0:\n    print("even")\nelse:\n    print("odd")',
    tests: [
      { name: '4 is even', stdin: '4', expect: 'even' },
      { name: '7 is odd', stdin: '7', expect: 'odd' },
      { name: '0 is even', stdin: '0', expect: 'even', hidden: true },
      { name: '-3 is odd', stdin: '-3', expect: 'odd', hidden: true },
    ],
    mustContain: [{ pattern: '%', label: 'use the remainder operator' }],
    explain: 'n % 2 == 0 is the standard evenness test, and it works for negative numbers too.',
  },
  {
    id: 'py.if.4',
    concepts: ['py.if'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print for score = 85?',
    code: 'score = 85\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")',
    options: ['A', 'B', 'B\nC', 'C'],
    answer: 1,
    explain: 'elif stops as soon as one branch matches. A chain of plain ifs would print both B and C.',
  },

  /* ------------------------------------------------------------ py.loops */
  {
    id: 'py.for.1',
    concepts: ['py.for', 'py.range'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'How many lines does this print?',
    code: 'for i in range(3):\n    print(i)',
    options: ['2', '3', '4', '0'],
    answer: 1,
    explain: 'range(3) gives 0, 1, 2 — three values, stopping before 3.',
  },
  {
    id: 'py.range.1',
    concepts: ['py.range'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each range to what it produces.',
    pairs: [
      ['range(4)', '0 1 2 3'],
      ['range(1, 4)', '1 2 3'],
      ['range(0, 10, 3)', '0 3 6 9'],
    ],
    explain: 'One argument is a stop, two are start and stop, three add a step.',
  },
  {
    id: 'py.for.2',
    concepts: ['py.for'],
    difficulty: 2,
    kind: 'assemble',
    prompt: 'Build the header of a loop over every item in the list names.',
    answer: ['for', 'name', 'in', 'names', ':'],
    distractors: ['while', 'of', 'each'],
    explain: 'Python loops over the items directly. You rarely need an index at all.',
  },
  {
    id: 'py.while.1',
    concepts: ['py.while'],
    difficulty: 3,
    kind: 'bug',
    prompt: 'This loop never stops. Which line is the problem?',
    code: 'n = 5\nwhile n > 0:\n    print(n)\n    n = n + 1',
    buggyLine: 4,
    why: {
      options: [
        'n should get smaller, not bigger',
        'The condition should be n < 0',
        'print is inside the loop',
      ],
      answer: 0,
    },
    explain: 'A while loop needs something inside it that moves towards the condition being false.',
  },
  {
    id: 'py.while.2',
    concepts: ['py.while', 'py.for'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'When is while the right choice over for?',
    options: [
      'When you know exactly how many times to repeat',
      'When you repeat until something becomes true, however long that takes',
      'When looping over a list',
      'Never, for is always better',
    ],
    answer: [1],
    explain: 'for is for a known collection; while is for an unknown number of rounds.',
  },
  {
    id: 'py.loopctl.1',
    concepts: ['py.loopcontrol'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for i in range(5):\n    if i == 3:\n        break\n    print(i)',
    options: ['0 1 2 3 4', '0\n1\n2', '0\n1\n2\n3', '0\n1\n2\n4'],
    answer: 1,
    explain: 'break leaves the loop entirely. continue would skip only that one round.',
  },
  {
    id: 'py.loopctl.2',
    concepts: ['py.loopcontrol'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'for i in range(5):\n    if i % 2 == 0:\n        continue\n    print(i)',
    options: ['0\n2\n4', '1\n3', '0\n1\n2\n3\n4', 'nothing'],
    answer: 1,
    explain: 'continue jumps straight to the next round, so the even numbers never reach print.',
  },
  {
    id: 'py.loops.write.1',
    concepts: ['py.for', 'py.range'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Print the numbers 1 to 5, one per line.',
    runLang: 'python',
    starter: '# loop from 1 to 5\n',
    solution: 'for i in range(1, 6):\n    print(i)',
    tests: [{ name: 'counts 1 to 5', expect: '1\n2\n3\n4\n5' }],
    mustContain: [{ pattern: 'for', label: 'use a for loop' }],
    explain: 'range(1, 6) stops *before* 6, which is why the second number is one more than you want.',
    hint: 'range stops before its second argument.',
  },
  {
    id: 'py.loops.write.2',
    concepts: ['py.for', 'py.arithmetic'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Print the total of the numbers 1 to 100.',
    runLang: 'python',
    starter: 'total = 0\n',
    solution: 'total = 0\nfor i in range(1, 101):\n    total += i\nprint(total)',
    tests: [{ name: 'sums to 5050', expect: '5050' }],
    explain: 'Start an accumulator at 0, add to it inside the loop, print it after. This shape never changes.',
  },
  {
    id: 'py.loops.write.3',
    concepts: ['py.for', 'py.if', 'py.loopcontrol'],
    difficulty: 5,
    kind: 'write',
    prompt: 'FizzBuzz for 1 to 15: multiples of 3 print Fizz, of 5 print Buzz, of both print FizzBuzz, otherwise the number.',
    runLang: 'python',
    starter: 'for i in range(1, 16):\n    # your turn\n',
    solution:
      'for i in range(1, 16):\n    if i % 15 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)',
    tests: [
      {
        name: '1 to 15',
        expect: '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz',
      },
    ],
    explain: 'Test the both-case first. Checking 3 before 15 means 15 prints Fizz and stops.',
    hint: 'Which condition must be checked first?',
  },

  /* ------------------------------------------------------------ py.lists */
  {
    id: 'py.list.1',
    concepts: ['py.lists', 'py.indexing'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'xs = [10, 20, 30]\nprint(xs[1])',
    options: ['10', '20', '30', 'Error'],
    answer: 1,
    explain: 'Indexes start at 0, so xs[1] is the second item. This trips everyone up once.',
  },
  {
    id: 'py.list.2',
    concepts: ['py.indexing'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'xs = [1, 2, 3]\nprint(xs[-1], xs[len(xs) - 1])',
    options: ['3 3', '1 3', 'Error 3', '3 Error'],
    answer: 0,
    explain: 'Both reach the last item. The negative index is shorter and harder to get wrong.',
  },
  {
    id: 'py.listm.1',
    concepts: ['py.listmethods'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each list method to what it does.',
    pairs: [
      ['.append(x)', 'add x to the end'],
      ['.pop()', 'remove and return the last item'],
      ['.sort()', 'reorder this list in place'],
      ['.insert(0, x)', 'add x at the front'],
    ],
    explain: 'append and sort change the list itself and return None — do not write xs = xs.sort().',
  },
  {
    id: 'py.listm.2',
    concepts: ['py.listmethods'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This should print a sorted list. Which line breaks it?',
    code: 'xs = [3, 1, 2]\nxs = xs.sort()\nprint(xs)',
    buggyLine: 2,
    why: {
      options: [
        'sort() needs an argument',
        'sort() sorts in place and returns None, so xs becomes None',
        'You cannot sort numbers',
      ],
      answer: 1,
    },
    explain: 'Use xs.sort() on its own line, or ys = sorted(xs) if you want a new list.',
  },
  {
    id: 'py.list.3',
    concepts: ['py.lists', 'py.listmethods'],
    difficulty: 3,
    kind: 'order',
    prompt: 'Order these lines to collect the squares of 1, 2 and 3.',
    lines: ['squares = []', 'for n in [1, 2, 3]:', '    squares.append(n * n)', 'print(squares)'],
    explain: 'Create the empty list before the loop, or you would wipe it out on every round.',
  },
  {
    id: 'py.list.4',
    concepts: ['py.lists', 'py.for'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Read one line of space-separated numbers and print the largest.',
    runLang: 'python',
    starter: 'parts = input().split()\n',
    solution: 'parts = input().split()\nbest = int(parts[0])\nfor p in parts:\n    if int(p) > best:\n        best = int(p)\nprint(best)',
    tests: [
      { name: 'mixed', stdin: '3 9 2 7', expect: '9' },
      { name: 'single', stdin: '5', expect: '5' },
      { name: 'negatives', stdin: '-4 -9 -1', expect: '-1', hidden: true },
    ],
    explain: 'Starting best at the first item rather than 0 is what makes it work for negative numbers.',
    hint: 'What should best start as?',
  },
  {
    id: 'py.list.5',
    concepts: ['py.lists'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'a = [1, 2]\nb = a\nb.append(3)\nprint(a)',
    options: ['[1, 2]', '[1, 2, 3]', '[3]', 'Error'],
    answer: 1,
    explain: 'b is not a copy — both names point at one list. Use b = a.copy() when you want a separate one.',
  },

  /* ------------------------------------------------------------ py.dicts */
  {
    id: 'py.dict.1',
    concepts: ['py.dicts'],
    difficulty: 2,
    kind: 'blank',
    prompt: 'Look up the value stored under "name".',
    template: 'user{{0}}',
    blanks: [{ accept: ['["name"]', "['name']"], width: 10 }],
    explain: 'Dictionaries are indexed by key instead of position, using the same square brackets.',
  },
  {
    id: 'py.dict.2',
    concepts: ['py.dicts', 'py.errors'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What happens here?',
    code: 'user = {"name": "Ada"}\nprint(user["age"])',
    options: ['None', 'Empty string', 'KeyError', '0'],
    answer: 2,
    explain: 'A missing key raises. user.get("age") returns None instead, and user.get("age", 0) a default.',
  },
  {
    id: 'py.dictm.1',
    concepts: ['py.dictmethods'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each dictionary method to what it gives you.',
    pairs: [
      ['.keys()', 'every key'],
      ['.values()', 'every value'],
      ['.items()', 'key and value pairs'],
      ['.get(k, d)', 'the value, or d if the key is missing'],
    ],
    explain: '.items() is what you want in a for loop: for key, value in d.items().',
  },
  {
    id: 'py.dictm.2',
    concepts: ['py.dictmethods', 'py.for'],
    difficulty: 4,
    kind: 'assemble',
    prompt: 'Build the loop header that walks a dictionary as key and value.',
    answer: ['for', 'k', ',', 'v', 'in', 'scores.items', '(', ')', ':'],
    distractors: ['scores', 'keys'],
    explain: 'Without .items() you would loop over keys alone, which is often all you need.',
  },
  {
    id: 'py.dict.3',
    concepts: ['py.dicts', 'py.for'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Count how many times each word appears in a line of input. Print each word and its count, in the order first seen, as "word count".',
    runLang: 'python',
    starter: 'words = input().split()\ncounts = {}\n',
    solution:
      'words = input().split()\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1\nfor w, n in counts.items():\n    print(w, n)',
    tests: [
      { name: 'repeats', stdin: 'a b a c b a', expect: 'a 3\nb 2\nc 1' },
      { name: 'single word', stdin: 'hello', expect: 'hello 1' },
    ],
    explain: 'counts.get(w, 0) + 1 is the counting idiom: it treats a missing key as zero.',
    hint: 'How do you add 1 to a key that might not exist yet?',
  },
  {
    id: 'py.set.1',
    concepts: ['py.sets'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(len(set([1, 2, 2, 3, 3, 3])))',
    options: ['6', '3', '1', '2'],
    answer: 1,
    explain: 'A set keeps only distinct values, which makes set() the one-line way to remove duplicates.',
  },
  {
    id: 'py.set.2',
    concepts: ['py.sets', 'py.lists'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why check membership in a set rather than a list for large data?',
    options: [
      'Sets keep order',
      'Sets can hold more items',
      'Checking a set is near-instant; checking a list scans every item',
      'There is no difference',
    ],
    answer: [2],
    explain: 'Sets hash their contents. On a million items that is the difference between instant and a coffee break.',
  },

  /* -------------------------------------------------------- py.functions */
  {
    id: 'py.fn.1',
    concepts: ['py.functions'],
    difficulty: 2,
    kind: 'order',
    prompt: 'Order the lines of a function that doubles a number.',
    lines: ['def double(n):', '    return n * 2', 'print(double(4))'],
    explain: 'The call has to come after the definition — Python reads the file top to bottom.',
  },
  {
    id: 'py.fn.2',
    concepts: ['py.functions', 'py.return'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'def add(a, b):\n    print(a + b)\nresult = add(2, 3)\nprint(result)',
    options: ['5\n5', '5\nNone', 'None\n5', '5'],
    answer: 1,
    explain: 'The function prints but never returns, so result is None. print and return are different jobs.',
  },
  {
    id: 'py.ret.1',
    concepts: ['py.return'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'def f(n):\n    return n\n    print("after")\nprint(f(1))',
    options: ['1\nafter', 'after\n1', '1', 'after'],
    answer: 2,
    explain: 'return leaves the function immediately. Anything after it on that path is dead code.',
  },
  {
    id: 'py.args.1',
    concepts: ['py.arguments'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Give greeting a default value of "Hello".',
    template: 'def greet(name, greeting{{0}}"Hello"):',
    blanks: [{ accept: ['='], width: 3 }],
    explain: 'Defaults must come after all the parameters without one, or Python cannot tell them apart.',
  },
  {
    id: 'py.args.2',
    concepts: ['py.arguments'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'def box(w, h=2):\n    return w * h\nprint(box(3), box(3, 4))',
    options: ['6 12', '5 7', '6 6', 'Error'],
    answer: 0,
    explain: 'The default is used only when the argument is left out.',
  },
  {
    id: 'py.scope.1',
    concepts: ['py.scope'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'x = 1\ndef f():\n    x = 2\nf()\nprint(x)',
    options: ['1', '2', 'None', 'Error'],
    answer: 0,
    explain: 'Assigning inside a function makes a new local name. The outer x is untouched.',
  },
  {
    id: 'py.fn.write.1',
    concepts: ['py.functions', 'py.return'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Write is_even(n) that returns True or False, then print is_even for the number on input.',
    runLang: 'python',
    starter: 'def is_even(n):\n    # return True or False\n    pass\n\nprint(is_even(int(input())))',
    solution: 'def is_even(n):\n    return n % 2 == 0\n\nprint(is_even(int(input())))',
    tests: [
      { name: '4', stdin: '4', expect: 'True' },
      { name: '7', stdin: '7', expect: 'False' },
    ],
    mustContain: [{ pattern: 'return', label: 'return the answer instead of printing it' }],
    explain: 'return n % 2 == 0 returns the comparison directly. No if statement is needed.',
  },
  {
    id: 'py.fn.write.2',
    concepts: ['py.functions', 'py.for'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Write reverse_words(s) that reverses the order of words. "one two three" becomes "three two one".',
    runLang: 'python',
    starter: 'def reverse_words(s):\n    pass\n\nprint(reverse_words(input()))',
    solution: 'def reverse_words(s):\n    return " ".join(s.split()[::-1])\n\nprint(reverse_words(input()))',
    tests: [
      { name: 'three words', stdin: 'one two three', expect: 'three two one' },
      { name: 'one word', stdin: 'solo', expect: 'solo' },
    ],
    explain: 'split, reverse with [::-1], join back. Three steps that chain into one readable line.',
    hint: 'split() gives a list. What reverses a list?',
  },

  /* -------------------------------------------------- py.comprehensions */
  {
    id: 'py.comp.1',
    concepts: ['py.comprehension'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print([n * 2 for n in [1, 2, 3]])',
    options: ['[1, 2, 3]', '[2, 4, 6]', '[1, 4, 9]', '6'],
    answer: 1,
    explain: 'Read it as "the doubled n, for each n in the list". The expression comes first.',
  },
  {
    id: 'py.comp.2',
    concepts: ['py.comprehension'],
    difficulty: 4,
    kind: 'assemble',
    prompt: 'Build a list of every even number below 10.',
    answer: ['[', 'n', 'for', 'n', 'in', 'range(10)', 'if', 'n % 2 == 0', ']'],
    distractors: ['while', 'else', 'append'],
    explain: 'The filter goes at the end. An if before the for would need an else too.',
  },
  {
    id: 'py.comp.3',
    concepts: ['py.comprehension', 'py.strmethods'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Read a line of words and print a list of their lengths, using a comprehension.',
    runLang: 'python',
    starter: 'words = input().split()\n',
    solution: 'words = input().split()\nprint([len(w) for w in words])',
    tests: [
      { name: 'three words', stdin: 'a bb ccc', expect: '[1, 2, 3]' },
      { name: 'one word', stdin: 'hello', expect: '[5]' },
    ],
    mustContain: [{ pattern: 'for', label: 'use a comprehension' }],
    explain: 'One line replaces four: create, loop, append, print.',
  },
  {
    id: 'py.sort.1',
    concepts: ['py.sorting'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'print(sorted(["pear", "fig", "banana"], key=len))',
    options: [
      "['banana', 'fig', 'pear']",
      "['fig', 'pear', 'banana']",
      "['pear', 'fig', 'banana']",
      "['fig', 'banana', 'pear']",
    ],
    answer: 1,
    explain: 'key=len sorts by length rather than alphabetically. The key is a function, not a value.',
  },
  {
    id: 'py.sort.2',
    concepts: ['py.sorting'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is the difference between sorted(xs) and xs.sort()?',
    options: [
      'None, they are aliases',
      'sorted() returns a new list; .sort() reorders xs and returns None',
      '.sort() is faster on strings',
      'sorted() only works on numbers',
    ],
    answer: [1],
    explain: 'Choose by whether you still need the original order.',
  },

  /* ----------------------------------------------------------- py.errors */
  {
    id: 'py.exc.1',
    concepts: ['py.exceptions'],
    difficulty: 3,
    kind: 'order',
    prompt: 'Order the lines that guard against bad input.',
    lines: ['try:', '    n = int(input())', 'except ValueError:', '    print("not a number")'],
    explain: 'Put as little as possible inside try, so you are not accidentally catching bugs elsewhere.',
  },
  {
    id: 'py.exc.2',
    concepts: ['py.exceptions'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why is a bare "except:" a bad habit?',
    options: [
      'It is slower',
      'It swallows every error, including your own typos and Ctrl+C',
      'It only works in functions',
      'It is not valid Python',
    ],
    answer: [1],
    explain: 'Catch the specific error you expect. Hiding the rest turns a crash into a mystery.',
  },
  {
    id: 'py.exc.3',
    concepts: ['py.exceptions'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Read a line and print the number doubled, or "not a number" if it is not one.',
    runLang: 'python',
    starter: 'raw = input()\n',
    solution: 'raw = input()\ntry:\n    print(int(raw) * 2)\nexcept ValueError:\n    print("not a number")',
    tests: [
      { name: 'a number', stdin: '21', expect: '42' },
      { name: 'not a number', stdin: 'cat', expect: 'not a number' },
    ],
    mustContain: [{ pattern: 'except', label: 'catch the error' }],
    explain: 'int() raises ValueError on text it cannot parse, which is exactly the error to catch.',
  },
  {
    id: 'py.debug.1',
    concepts: ['py.debugging'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'A loop gives the wrong total. What is the fastest first move?',
    options: [
      'Rewrite the whole thing',
      'Print the running total inside the loop and watch it change',
      'Add a try/except',
      'Search the internet for the answer',
    ],
    answer: [1],
    explain: 'Make the invisible visible. Most bugs are obvious the moment you can see the intermediate values.',
  },
  {
    id: 'py.debug.2',
    concepts: ['py.debugging', 'py.for'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'This should total the list but always prints the last item. Which line is wrong?',
    code: 'xs = [1, 2, 3]\ntotal = 0\nfor x in xs:\n    total = x\nprint(total)',
    buggyLine: 4,
    why: {
      options: [
        'It should be total += x',
        'The loop should use range',
        'total should start at 1',
      ],
      answer: 0,
    },
    explain: 'total = x replaces the running sum each time. += is what accumulates.',
  },

  /* ---------------------------------------------------------- py.classes */
  {
    id: 'py.cls.1',
    concepts: ['py.classes'],
    difficulty: 4,
    kind: 'blank',
    prompt: 'Complete the method that runs when a Dog is created.',
    template: 'class Dog:\n    def {{0}}(self, name):\n        self.name = name',
    blanks: [{ accept: ['__init__'], width: 12 }],
    explain: '__init__ is the constructor. It runs automatically when you write Dog("Rex").',
  },
  {
    id: 'py.cls.2',
    concepts: ['py.classes', 'py.methods'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is self?',
    options: [
      'A keyword Python requires',
      'The particular object the method was called on',
      'The class itself',
      'A copy of the object',
    ],
    answer: [1],
    explain: 'It is just the first parameter, and it could be named anything — but never is.',
  },
  {
    id: 'py.attr.1',
    concepts: ['py.attributes'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'class P:\n    def __init__(self, n):\n        self.n = n\na = P(1)\nb = P(2)\nprint(a.n, b.n)',
    options: ['1 2', '2 2', '1 1', 'Error'],
    answer: 0,
    explain: 'Each instance carries its own attributes. That separation is the whole point of a class.',
  },
  {
    id: 'py.methods.1',
    concepts: ['py.methods'],
    difficulty: 5,
    kind: 'order',
    prompt: 'Order the lines of a counter class and its use.',
    lines: [
      'class Counter:',
      '    def __init__(self):',
      '        self.total = 0',
      '    def bump(self):',
      '        self.total += 1',
      'c = Counter()',
      'c.bump()',
      'print(c.total)',
    ],
    explain: 'Methods are indented inside the class; the code that uses it starts back at the margin.',
  },
  {
    id: 'py.cls.write.1',
    concepts: ['py.classes', 'py.methods', 'py.attributes'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Write a Wallet class with a balance that starts at 0, an add(n) method, and print the balance after adding 5 then 7.',
    runLang: 'python',
    starter: 'class Wallet:\n    pass\n\nw = Wallet()\nw.add(5)\nw.add(7)\nprint(w.balance)',
    solution:
      'class Wallet:\n    def __init__(self):\n        self.balance = 0\n    def add(self, n):\n        self.balance += n\n\nw = Wallet()\nw.add(5)\nw.add(7)\nprint(w.balance)',
    tests: [{ name: 'balance is 12', expect: '12' }],
    mustContain: [{ pattern: '__init__', label: 'define __init__' }],
    explain: 'State lives on self so it survives between method calls. That is what an object is for.',
  },
]);
