import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const rustExtraSkills: Skill[] = [
  {
    id: 'rs.collections',
    title: 'Collections and iterators',
    blurb: 'Vec, HashMap, and the iterator chain that replaces most loops.',
    concepts: ['rs.vec', 'rs.hashmap', 'rs.iterators'],
    requires: ['rs.control'],
    level: 'applied',
    tags: ['systems', 'interviews'],
    unit: 'Everyday Rust',
  },
  {
    id: 'rs.cargo',
    title: 'Cargo and modules',
    blurb: 'Crates, modules and the tooling that makes Rust pleasant.',
    concepts: ['rs.cargo', 'rs.modules', 'rs.tests'],
    requires: ['rs.first'],
    level: 'applied',
    tags: ['systems'],
    unit: 'Everyday Rust',
  },
];

export const rustExtra = forTrack('rust', [
  {
    id: 'rs.main.x1',
    concepts: ['rs.main'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Where does a Rust program start?',
    options: ['fn main()', 'fn start()', 'pub fn run()', 'main:'],
    answer: [0],
    explain: 'fn main takes no arguments; command line arguments come from std::env::args().',
  },
  {
    id: 'rs.print.x1',
    concepts: ['rs.println'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Print hello with a newline.',
    template: 'fn main() {\n    {{0}}!("hello");\n}',
    blanks: [{ accept: ['println'], width: 8 }],
    explain: 'The exclamation mark means it is a macro, which is how it can check the format string at compile time.',
  },
  {
    id: 'rs.print.x2',
    concepts: ['rs.println'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'let n = 3;\nprintln!("n = {n}");',
    options: ['n = 3', 'n = {n}', '3', 'an error'],
    answer: 0,
    explain: 'Since Rust 2021 you can name the variable inside the braces directly.',
  },
  {
    id: 'rs.let.x1',
    concepts: ['rs.let'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'What is true of `let x = 5;`?',
    options: ['x cannot be reassigned', 'x is a global', 'x is heap allocated', 'x has no type'],
    answer: [0],
    explain: 'Bindings are immutable by default. That default is most of what makes Rust feel safe.',
  },
  {
    id: 'rs.mut.x1',
    concepts: ['rs.mut'],
    difficulty: 2,
    level: 2,
    kind: 'bug',
    prompt: 'Which line does the compiler reject?',
    code: 'let count = 0;\ncount += 1;\nprintln!("{count}");',
    buggyLine: 2,
    why: {
      options: ['count was not declared mut', 'count is the wrong type', 'println needs a reference', 'Nothing is wrong'],
      answer: 0,
    },
    explain: 'let mut count = 0; is the fix. Rust wants mutability to be visible at the declaration.',
  },
  {
    id: 'rs.types.x1',
    concepts: ['rs.types'],
    difficulty: 2,
    level: 2,
    kind: 'match',
    prompt: 'Match each type to what it is for.',
    pairs: [
      ['i32', 'A signed 32-bit integer'],
      ['f64', 'A double-precision float'],
      ['bool', 'true or false'],
      ['&str', 'A borrowed string slice'],
    ],
    explain: 'String owns its bytes; &str borrows them. Half of early Rust confusion lives in that distinction.',
  },
  {
    id: 'rs.own.x1',
    concepts: ['rs.ownership'],
    difficulty: 3,
    level: 3,
    kind: 'predict',
    prompt: 'Does this compile?',
    code: 'let a = String::from("hi");\nlet b = a;\nprintln!("{a}");',
    options: ['No — a was moved into b', 'Yes, it prints hi', 'No — b is unused', 'Yes, with a warning'],
    answer: 0,
    explain: 'Assignment moves ownership for types that own heap data. Clone if you really need two.',
  },
  {
    id: 'rs.borrow.x1',
    concepts: ['rs.borrow'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'How many mutable borrows of one value may exist at once?',
    options: ['One', 'Two', 'As many as you like', 'None'],
    answer: [0],
    explain: 'Many readers or one writer, never both. That single rule removes whole categories of bug.',
  },
  {
    id: 'rs.match.x1',
    concepts: ['rs.match'],
    difficulty: 3,
    level: 4,
    kind: 'order',
    prompt: 'Match on an Option.',
    lines: ['match maybe {', '    Some(value) => println!("{value}"),', '    None => println!("nothing"),', '}'],
    explain: 'match must be exhaustive; leaving out None is a compile error, not a runtime surprise.',
  },
  {
    id: 'rs.if.x1',
    concepts: ['rs.if'],
    difficulty: 2,
    level: 3,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'let n = 4;\nlet label = if n % 2 == 0 { "even" } else { "odd" };\nprintln!("{label}");',
    options: ['even', 'odd', 'true', 'an error'],
    answer: 0,
    explain: 'if is an expression in Rust, so it can produce a value — no ternary needed.',
  },

  /* ------------------------------------------------------ rs.collections */
  {
    id: 'rs.coll.1',
    concepts: ['rs.vec'],
    difficulty: 3,
    level: 5,
    kind: 'blank',
    prompt: 'Make a growable list and add to it.',
    template: 'let mut items = {{0}}::new();\nitems.{{1}}(3);',
    blanks: [{ accept: ['Vec'], width: 4 }, { accept: ['push'], width: 5 }],
    explain: 'Vec is the workhorse: heap allocated, growable, and contiguous.',
  },
  {
    id: 'rs.coll.2',
    concepts: ['rs.hashmap'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What does map.get("key") return?',
    options: ['Option<&V> — Some when present, None when not', '&V, or panics', 'V', 'A Result'],
    answer: [0],
    explain: 'Indexing with [] panics on a missing key; get hands you the absence to deal with.',
  },
  {
    id: 'rs.coll.3',
    concepts: ['rs.iterators'],
    difficulty: 4,
    level: 6,
    kind: 'predict',
    prompt: 'What does this print?',
    code: 'let xs = vec![1, 2, 3];\nlet total: i32 = xs.iter().map(|x| x * 2).sum();\nprintln!("{total}");',
    options: ['12', '6', '123', 'an error'],
    answer: 0,
    explain: 'Iterators are lazy: nothing runs until sum drives the chain.',
  },
  {
    id: 'rs.coll.4',
    concepts: ['rs.iterators'],
    difficulty: 5,
    level: 7,
    kind: 'match',
    prompt: 'Match each adaptor to what it does.',
    pairs: [
      ['map', 'Transform every item'],
      ['filter', 'Keep the items that pass a test'],
      ['collect', 'Run the chain into a collection'],
      ['enumerate', 'Pair each item with its index'],
    ],
    explain: 'collect is the one that actually does the work. Everything before it just describes it.',
  },
  {
    id: 'rs.coll.5',
    concepts: ['rs.vec', 'rs.iterators'],
    difficulty: 4,
    level: 7,
    kind: 'write',
    prompt: 'Print the sum of the even numbers from 1 to 10 inclusive.',
    runLang: 'rust',
    starter: 'fn main() {\n    // your code\n}\n',
    solution:
      'fn main() {\n    let total: i32 = (1..=10).filter(|n| n % 2 == 0).sum();\n    println!("{total}");\n}\n',
    tests: [{ name: 'sums 2+4+6+8+10', expect: '30' }],
    explain: '1..=10 is inclusive; 1..10 stops at nine. That one character is a classic off-by-one.',
  },

  /* ----------------------------------------------------------- rs.cargo */
  {
    id: 'rs.cargo.1',
    concepts: ['rs.cargo'],
    difficulty: 2,
    level: 4,
    kind: 'terminal',
    prompt: 'Run the project you are in, in debug mode.',
    intro: ['~/app $ ls', 'Cargo.toml  src'],
    cwd: '~/app',
    accept: ['cargo run'],
    output: ['   Compiling app v0.1.0', '    Finished dev profile', '     Running `target/debug/app`'],
    explain: 'cargo run builds and runs. cargo build only builds; cargo check only type-checks, and is much faster.',
  },
  {
    id: 'rs.cargo.2',
    concepts: ['rs.cargo'],
    difficulty: 3,
    level: 5,
    kind: 'match',
    prompt: 'Match each cargo command to its job.',
    pairs: [
      ['cargo check', 'Type-check without producing a binary'],
      ['cargo test', 'Build and run the tests'],
      ['cargo clippy', 'Lint for common mistakes'],
      ['cargo fmt', 'Format the code'],
    ],
    explain: 'cargo check in a watch loop is the fastest feedback Rust has to offer.',
  },
  {
    id: 'rs.cargo.3',
    concepts: ['rs.modules'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What does `mod shapes;` do in main.rs?',
    options: [
      'Loads shapes.rs (or shapes/mod.rs) as a module of this crate',
      'Imports an external crate',
      'Declares a namespace with no file',
      'Re-exports everything from shapes',
    ],
    answer: [0],
    explain: 'mod declares the module; use brings names from it into scope. They are two different jobs.',
  },
  {
    id: 'rs.cargo.4',
    concepts: ['rs.tests'],
    difficulty: 4,
    level: 6,
    kind: 'order',
    prompt: 'Write a unit test inside the same file as the code.',
    lines: ['#[cfg(test)]', 'mod tests {', '    use super::*;', '', '    #[test]', '    fn adds() {', '        assert_eq!(add(2, 2), 4);', '    }', '}'],
    explain: 'cfg(test) means the module only exists during tests, so it costs nothing in the shipped binary.',
  },
  {
    id: 'rs.cargo.5',
    concepts: ['rs.modules'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'Why is an item private by default even inside your own crate?',
    options: [
      'So a module can change its internals without breaking anything outside it',
      'To make compilation faster',
      'Because pub is deprecated',
      'It only applies to structs',
    ],
    answer: [0],
    explain: 'pub is an explicit promise. Adding it later is easy; taking it away is a breaking change.',
  },
]);
