import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'rs.first',
    title: 'First program',
    blurb: 'fn main, println!, and the exclamation mark that means macro.',
    concepts: ['rs.main', 'rs.println', 'rs.syntax'],
    requires: [],
    level: 'intro',
    tags: ['systems'],
    unit: 'Getting started',
  },
  {
    id: 'rs.bindings',
    title: 'Bindings and types',
    blurb: 'Immutable by default, and the types that never surprise you.',
    concepts: ['rs.let', 'rs.mut', 'rs.types'],
    requires: ['rs.first'],
    level: 'core',
    tags: ['systems'],
    unit: 'Getting started',
  },
  {
    id: 'rs.ownership',
    title: 'Ownership',
    blurb: 'The idea the whole language is built on: move, borrow, and lifetimes.',
    concepts: ['rs.ownership', 'rs.borrow', 'rs.lifetime'],
    requires: ['rs.bindings'],
    level: 'advanced',
    tags: ['systems'],
    unit: 'The big idea',
  },
  {
    id: 'rs.control',
    title: 'Control flow and matching',
    blurb: 'if as an expression, loops, and exhaustive match.',
    concepts: ['rs.if', 'rs.loops', 'rs.match'],
    requires: ['rs.bindings'],
    level: 'core',
    tags: ['systems', 'interviews'],
    unit: 'Control flow',
  },
  {
    id: 'rs.errors',
    title: 'Option and Result',
    blurb: 'No null, no exceptions — just two enums and the ? operator.',
    concepts: ['rs.option', 'rs.result', 'rs.question'],
    requires: ['rs.control'],
    level: 'applied',
    tags: ['systems', 'apps'],
    unit: 'Handling absence',
  },
  {
    id: 'rs.structs',
    title: 'Structs and traits',
    blurb: 'Your own types, and shared behaviour without inheritance.',
    concepts: ['rs.structs', 'rs.impl', 'rs.traits'],
    requires: ['rs.control'],
    level: 'applied',
    tags: ['systems'],
    unit: 'Your own types',
  },
];

export const rustTrack: Track = {
  id: 'rust',
  name: 'Rust',
  kind: 'language',
  tagline: 'The compiler is strict so the program is not',
  blurb:
    'Memory safety without a garbage collector, and a compiler that argues with you until the program is right. Hard at first, then oddly relaxing.',
  lang: 'rust',
  runLang: 'rust',
  mark: 'Rs',
  tags: ['systems', 'apps'],
  goals: ['systems', 'apps'],
  slope: 5,
  transfersFrom: ['cpp', 'go', 'typescript'],
  skills,
};

export const rustExercises = forTrack('rust', [
  /* ------------------------------------------------------------ rs.first */
  {
    id: 'rs.main.1',
    concepts: ['rs.main', 'rs.println'],
    difficulty: 2,
    kind: 'order',
    prompt: 'Order the smallest Rust program.',
    lines: ['fn main() {', '    println!("Hello, Rust!");', '}'],
    explain: 'Every binary starts at fn main. There is no return value to write.',
  },
  {
    id: 'rs.print.1',
    concepts: ['rs.println'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'Why does println! end with an exclamation mark?',
    options: [
      'It is emphatic',
      'It is a macro, not a function, and expands at compile time',
      'It flushes the output',
      'It is optional',
    ],
    answer: [1],
    explain: 'The macro checks your format string against the arguments while compiling. A typo is a build error.',
  },
  {
    id: 'rs.print.2',
    concepts: ['rs.println'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Print the value of name inside a sentence.',
    template: 'println!("Hello, {{0}}!", name);',
    blanks: [{ accept: ['{}'], width: 4 }],
    explain: 'Curly braces are placeholders filled in order. {name} also works for a variable of that name.',
  },
  {
    id: 'rs.syn.1',
    concepts: ['rs.syntax'],
    difficulty: 3,
    kind: 'bug',
    prompt: 'Which line will not compile?',
    code: 'fn main() {\n    let x = 5\n    println!("{}", x);\n}',
    buggyLine: 2,
    why: {
      options: ['Missing semicolon', 'x needs a type', 'let should be var'],
      answer: 0,
    },
    explain: 'A missing semicolon changes the meaning: without it the line becomes an expression, not a statement.',
  },
  {
    id: 'rs.syn.2',
    concepts: ['rs.syntax', 'rs.println'],
    difficulty: 3,
    kind: 'write',
    prompt: 'Print "Hello from Rust".',
    runLang: 'rust',
    starter: 'fn main() {\n    \n}',
    solution: 'fn main() {\n    println!("Hello from Rust");\n}',
    tests: [{ name: 'greets', expect: 'Hello from Rust' }],
    explain: 'println! writes to stdout and adds the newline for you.',
  },

  /* --------------------------------------------------------- rs.bindings */
  {
    id: 'rs.let.1',
    concepts: ['rs.let', 'rs.mut'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does the compiler say?',
    code: 'fn main() {\n    let x = 5;\n    x = 6;\n    println!("{}", x);\n}',
    options: ['Prints 6', 'Prints 5', 'cannot assign twice to immutable variable', 'x is undefined'],
    answer: 2,
    explain: 'let bindings are immutable by default. Write `let mut x = 5;` when you mean to change it.',
  },
  {
    id: 'rs.mut.1',
    concepts: ['rs.mut'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Make this counter changeable.',
    template: 'let {{0}} count = 0;',
    blanks: [{ accept: ['mut'], width: 4 }],
    explain: 'Making mutability opt-in means every mutable value is visible at a glance.',
  },
  {
    id: 'rs.type.1',
    concepts: ['rs.types'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each Rust type to what it holds.',
    pairs: [
      ['i32', 'a signed 32-bit integer'],
      ['f64', 'a 64-bit float'],
      ['bool', 'true or false'],
      ['&str', 'a borrowed string slice'],
    ],
    explain: 'The size is in the name, so there is never a question of how wide an integer is.',
  },
  {
    id: 'rs.type.2',
    concepts: ['rs.types'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is the difference between String and &str?',
    options: [
      'String owns its bytes and can grow; &str borrows a view of somebody else s',
      '&str is faster to print',
      'String is only for ASCII',
      'They are aliases',
    ],
    answer: [0],
    explain: 'Take &str as a parameter, return String when you build something new.',
  },

  /* -------------------------------------------------------- rs.ownership */
  {
    id: 'rs.own.1',
    concepts: ['rs.ownership'],
    difficulty: 5,
    kind: 'predict',
    prompt: 'What does the compiler say?',
    code: 'fn main() {\n    let a = String::from("hi");\n    let b = a;\n    println!("{}", a);\n}',
    options: ['Prints hi', 'Prints nothing', 'borrow of moved value: `a`', 'Prints an address'],
    answer: 2,
    explain: 'Assigning a String moves ownership. Use a.clone() for a copy, or &a to borrow.',
  },
  {
    id: 'rs.own.2',
    concepts: ['rs.ownership'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What problem does ownership solve without a garbage collector?',
    options: [
      'Slow compilation',
      'Use-after-free and double-free, by giving every value exactly one owner',
      'Integer overflow',
      'Deadlocks',
    ],
    answer: [1],
    explain: 'When the owner goes out of scope the value is dropped, exactly once, at a point the compiler can prove.',
  },
  {
    id: 'rs.borrow.1',
    concepts: ['rs.borrow'],
    difficulty: 5,
    kind: 'match',
    prompt: 'Match each borrow to its rule.',
    pairs: [
      ['&x', 'a shared borrow: many at once, read only'],
      ['&mut x', 'a unique borrow: only one, and no shared ones alive'],
      ['x', 'ownership moves to the new binding'],
    ],
    explain: 'Many readers or one writer, never both. That single rule is what makes data races impossible.',
  },
  {
    id: 'rs.borrow.2',
    concepts: ['rs.borrow'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'The borrow checker rejects this. Which line?',
    code: 'let mut xs = vec![1, 2, 3];\nlet first = &xs[0];\nxs.push(4);\nprintln!("{}", first);',
    buggyLine: 3,
    why: {
      options: [
        'push needs a unique borrow while first still holds a shared one',
        'vec! is spelled wrong',
        'first should be mut',
      ],
      answer: 0,
    },
    explain: 'Pushing can reallocate the vector, which would leave `first` dangling. C++ lets you do exactly this.',
  },
  {
    id: 'rs.life.1',
    concepts: ['rs.lifetime'],
    difficulty: 5,
    kind: 'choice',
    prompt: "What is a lifetime annotation like <'a> telling the compiler?",
    options: [
      'How long the value lives in milliseconds',
      'That the returned reference lives at least as long as the input it came from',
      'To free the value early',
      'That the value is static',
    ],
    answer: [1],
    explain: 'Lifetimes describe relationships that already exist. They never change how long anything lives.',
  },

  /* ---------------------------------------------------------- rs.control */
  {
    id: 'rs.if.1',
    concepts: ['rs.if'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What is x?',
    code: 'let n = 7;\nlet x = if n > 5 { "big" } else { "small" };',
    options: ['"big"', '"small"', 'true', 'A compile error'],
    answer: 0,
    explain: 'if is an expression in Rust, so it produces a value. Both arms must have the same type.',
  },
  {
    id: 'rs.loop.1',
    concepts: ['rs.loops'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each loop form to what it is for.',
    pairs: [
      ['loop', 'repeat forever until you break'],
      ['while cond', 'repeat while a condition holds'],
      ['for x in xs', 'walk every item of something iterable'],
    ],
    explain: 'loop can also return a value: `let v = loop { break 5; };`',
  },
  {
    id: 'rs.loop.2',
    concepts: ['rs.loops'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Print the sum of 1 to 10.',
    runLang: 'rust',
    starter: 'fn main() {\n    let mut total = 0;\n    \n}',
    solution:
      'fn main() {\n    let mut total = 0;\n    for i in 1..=10 {\n        total += i;\n    }\n    println!("{}", total);\n}',
    tests: [{ name: 'sums to 55', expect: '55' }],
    explain: '1..10 excludes the end; 1..=10 includes it. That equals sign is easy to miss.',
  },
  {
    id: 'rs.match.1',
    concepts: ['rs.match'],
    difficulty: 4,
    kind: 'order',
    prompt: 'Order a match over a number.',
    lines: ['match n {', '    0 => println!("zero"),', '    1..=9 => println!("small"),', '    _ => println!("big"),', '}'],
    explain: 'Arms are tried in order and _ catches the rest. Leave it out and the compiler checks you covered everything.',
  },
  {
    id: 'rs.match.2',
    concepts: ['rs.match'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What does it mean that match is exhaustive?',
    options: [
      'It is slow',
      'Every possible value must be handled, or it will not compile',
      'It stops at the first arm',
      'It can only match integers',
    ],
    answer: [1],
    explain: 'Add a variant to an enum and every match on it becomes a compile error until you handle it.',
  },

  /* ----------------------------------------------------------- rs.errors */
  {
    id: 'rs.opt.1',
    concepts: ['rs.option'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is Option<T>?',
    options: [
      'An enum that is either Some(value) or None',
      'A nullable pointer',
      'A collection',
      'A trait',
    ],
    answer: [0],
    explain: 'Rust has no null. Absence is a value you must unwrap, so you cannot forget to handle it.',
  },
  {
    id: 'rs.opt.2',
    concepts: ['rs.option', 'rs.match'],
    difficulty: 5,
    kind: 'assemble',
    prompt: 'Build the expression that reads an Option with a fallback of 0.',
    answer: ['value', '.', 'unwrap_or', '(', '0', ')'],
    distractors: ['unwrap', 'expect', 'None'],
    explain: 'unwrap() panics on None. unwrap_or gives a default, and is almost always the better choice.',
  },
  {
    id: 'rs.res.1',
    concepts: ['rs.result'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each variant to its meaning.',
    pairs: [
      ['Ok(v)', 'it worked, here is the value'],
      ['Err(e)', 'it failed, here is why'],
      ['Some(v)', 'there is a value'],
      ['None', 'there is no value'],
    ],
    explain: 'Result carries a reason for failure; Option only says whether something is there.',
  },
  {
    id: 'rs.q.1',
    concepts: ['rs.question'],
    difficulty: 5,
    kind: 'predict',
    prompt: 'What does the ? do here?',
    code: 'fn read() -> Result<String, Error> {\n    let s = load()?;\n    Ok(s)\n}',
    options: [
      'Ignores the error',
      'Returns early with the Err if load failed, otherwise unwraps the Ok',
      'Panics on failure',
      'Converts to an Option',
    ],
    answer: 1,
    explain: 'It replaces five lines of match with one character, and only works in a function returning Result.',
  },
  {
    id: 'rs.q.2',
    concepts: ['rs.question', 'rs.result'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'Which line does the compiler reject?',
    code: 'fn main() {\n    let n = "42".parse::<i32>()?;\n    println!("{}", n);\n}',
    buggyLine: 2,
    why: {
      options: [
        'main does not return Result, so ? has nowhere to return the error to',
        'parse needs a turbofish',
        '"42" is not a number',
      ],
      answer: 0,
    },
    explain: 'Either give main a Result return type, or handle it with match or unwrap_or.',
  },

  /* ---------------------------------------------------------- rs.structs */
  {
    id: 'rs.struct.1',
    concepts: ['rs.structs'],
    difficulty: 4,
    kind: 'order',
    prompt: 'Order a struct definition and its construction.',
    lines: ['struct Point {', '    x: i32,', '    y: i32,', '}', '', 'let p = Point { x: 1, y: 2 };'],
    explain: 'Fields are named and comma-separated, and there is no semicolon after the closing brace.',
  },
  {
    id: 'rs.impl.1',
    concepts: ['rs.impl'],
    difficulty: 5,
    kind: 'blank',
    prompt: 'Add methods to Point.',
    template: '{{0}} Point {\n    fn sum(&self) -> i32 {\n        self.x + self.y\n    }\n}',
    blanks: [{ accept: ['impl'], width: 5 }],
    explain: 'Data and behaviour live in separate blocks, which is why one struct can have several impl blocks.',
  },
  {
    id: 'rs.impl.2',
    concepts: ['rs.impl'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What is the difference between &self and self in a method?',
    options: [
      '&self borrows the value; self takes ownership and consumes it',
      'They are the same',
      'self is only for constructors',
      '&self is faster',
    ],
    answer: [0],
    explain: 'Taking self is how a builder can hand you a finished value and refuse to be reused.',
  },
  {
    id: 'rs.trait.1',
    concepts: ['rs.traits'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What is a trait?',
    options: [
      'A set of methods a type can promise to provide, like an interface',
      'A base struct to inherit from',
      'A module',
      'A kind of macro',
    ],
    answer: [0],
    explain: 'Rust has no inheritance. Shared behaviour comes from traits, and you can implement one for a foreign type.',
  },
  {
    id: 'rs.trait.2',
    concepts: ['rs.traits', 'rs.structs'],
    difficulty: 5,
    kind: 'write',
    prompt: 'Give Point an area-free `sum` method and print it for x=3, y=4.',
    runLang: 'rust',
    starter:
      'struct Point { x: i32, y: i32 }\n\nimpl Point {\n    \n}\n\nfn main() {\n    let p = Point { x: 3, y: 4 };\n    println!("{}", p.sum());\n}',
    solution:
      'struct Point { x: i32, y: i32 }\n\nimpl Point {\n    fn sum(&self) -> i32 {\n        self.x + self.y\n    }\n}\n\nfn main() {\n    let p = Point { x: 3, y: 4 };\n    println!("{}", p.sum());\n}',
    tests: [{ name: 'sums fields', expect: '7' }],
    explain: 'The last expression of a function is its return value — no semicolon, no return keyword.',
  },
]);
