import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'sql.select',
    title: 'Asking for rows',
    blurb: 'SELECT, FROM, WHERE, and the order the database actually reads them in.',
    concepts: ['sql.select', 'sql.where', 'sql.order'],
    requires: [],
    level: 'intro',
    tags: ['data'],
    unit: 'Queries',
  },
  {
    id: 'sql.filter',
    title: 'Filtering properly',
    blurb: 'NULL, IN, BETWEEN, LIKE, and the trap that NULL sets for you.',
    concepts: ['sql.null', 'sql.operators', 'sql.like'],
    requires: ['sql.select'],
    level: 'core',
    tags: ['data'],
    unit: 'Queries',
  },
  {
    id: 'sql.aggregate',
    title: 'Summarising',
    blurb: 'COUNT, SUM, GROUP BY, and why HAVING is not WHERE.',
    concepts: ['sql.aggregate', 'sql.groupby', 'sql.having'],
    requires: ['sql.filter'],
    level: 'core',
    tags: ['data', 'interviews'],
    unit: 'Analysis',
  },
  {
    id: 'sql.joins',
    title: 'Joining tables',
    blurb: 'INNER, LEFT, and what actually happens when you forget the ON.',
    concepts: ['sql.joins', 'sql.keys'],
    requires: ['sql.filter'],
    level: 'applied',
    tags: ['data', 'interviews'],
    unit: 'Analysis',
  },
  {
    id: 'sql.write',
    title: 'Changing data',
    blurb: 'INSERT, UPDATE, DELETE, and the WHERE clause you must not forget.',
    concepts: ['sql.insert', 'sql.update', 'sql.schema'],
    requires: ['sql.select'],
    level: 'applied',
    tags: ['data', 'apps'],
    unit: 'Writing',
  },
];

export const sqlTrack: Track = {
  id: 'sql',
  name: 'SQL',
  kind: 'language',
  tagline: 'Fifty years old and still how you ask data questions',
  blurb:
    'Every serious application stores its data somewhere that speaks SQL. A week of it makes you dramatically more useful, whatever else you write.',
  lang: 'sql',
  mark: 'SQ',
  tags: ['data', 'interviews', 'apps'],
  goals: ['data', 'interviews', 'apps', 'automation'],
  slope: 2,
  transfersFrom: [],
  skills,
};

export const sqlExercises = forTrack('sql', [
  /* --------------------------------------------------------- sql.select */
  {
    id: 'sql.sel.1',
    concepts: ['sql.select'],
    difficulty: 1,
    kind: 'assemble',
    prompt: 'Build a query for every column of the users table.',
    answer: ['SELECT', '*', 'FROM', 'users', ';'],
    distractors: ['GET', 'ALL', 'WHERE'],
    explain: 'SELECT chooses columns, FROM chooses the table. * means every column.',
  },
  {
    id: 'sql.sel.2',
    concepts: ['sql.select'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'Why avoid SELECT * in application code?',
    options: [
      'It breaks silently when columns are added or reordered, and moves data you do not need',
      'It is invalid SQL',
      'It is slower to type',
      'It locks the table',
    ],
    answer: [0],
    explain: 'Name your columns. Then adding one to the table cannot change what your code receives.',
  },
  {
    id: 'sql.where.1',
    concepts: ['sql.where'],
    difficulty: 2,
    kind: 'blank',
    prompt: 'Keep only the rows where age is over 18.',
    template: 'SELECT name FROM users {{0}} age > 18;',
    blanks: [{ accept: ['WHERE'], width: 7 }],
    explain: 'WHERE filters rows before anything is grouped or sorted.',
  },
  {
    id: 'sql.order.1',
    concepts: ['sql.order'],
    difficulty: 2,
    kind: 'predict',
    prompt: 'What order do the rows come back in?',
    code: 'SELECT name FROM users ORDER BY name DESC;',
    options: ['A to Z', 'Z to A', 'Insertion order', 'Random'],
    answer: 1,
    explain: 'ASC is the default, DESC reverses it. Without ORDER BY the order is not guaranteed at all.',
  },
  {
    id: 'sql.order.2',
    concepts: ['sql.order', 'sql.select'],
    difficulty: 3,
    kind: 'order',
    prompt: 'Put the clauses of a query in the order SQL requires.',
    lines: ['SELECT name', 'FROM users', 'WHERE active = 1', 'ORDER BY name', 'LIMIT 10;'],
    explain: 'You write SELECT first, but the database evaluates FROM, then WHERE, then SELECT, then ORDER BY.',
  },

  /* --------------------------------------------------------- sql.filter */
  {
    id: 'sql.null.1',
    concepts: ['sql.null'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'How many rows does this return if every email is NULL?',
    code: 'SELECT * FROM users WHERE email = NULL;',
    options: ['All of them', 'None', 'Only one', 'An error'],
    answer: 1,
    explain: 'NULL is not equal to anything, including NULL. You need IS NULL.',
  },
  {
    id: 'sql.null.2',
    concepts: ['sql.null'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Find users with no email recorded.',
    template: 'SELECT * FROM users WHERE email {{0}};',
    blanks: [{ accept: ['IS NULL'], width: 10 }],
    explain: 'IS NULL and IS NOT NULL are the only operators that work on unknown values.',
  },
  {
    id: 'sql.op.1',
    concepts: ['sql.operators'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each operator to what it does.',
    pairs: [
      ['IN (1, 2, 3)', 'matches any of the listed values'],
      ['BETWEEN 1 AND 5', 'inclusive range check'],
      ['<>', 'not equal to'],
      ['AND', 'both conditions must hold'],
    ],
    explain: 'BETWEEN includes both ends, which surprises people filtering on dates.',
  },
  {
    id: 'sql.like.1',
    concepts: ['sql.like'],
    difficulty: 3,
    kind: 'predict',
    prompt: "Which names match LIKE 'A%'?",
    code: "SELECT name FROM users WHERE name LIKE 'A%';",
    options: ['Names containing A', 'Names starting with A', 'Names ending with A', 'Exactly "A%"'],
    answer: 1,
    explain: '% matches any run of characters, _ matches exactly one. %A% is "contains".',
  },
  {
    id: 'sql.like.2',
    concepts: ['sql.like', 'sql.operators'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This finds nothing even though matching rows exist. Which line?',
    code: 'SELECT *\nFROM products\nWHERE name LIKE "phone%"\nORDER BY price;',
    buggyLine: 3,
    why: {
      options: [
        'Standard SQL uses single quotes for string literals; double quotes mean an identifier',
        'LIKE needs an underscore',
        'ORDER BY must come first',
      ],
      answer: 0,
    },
    explain: 'In strict databases "phone%" is read as a column name, and you get an error or nothing.',
  },

  /* ------------------------------------------------------ sql.aggregate */
  {
    id: 'sql.agg.1',
    concepts: ['sql.aggregate'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each aggregate to what it computes.',
    pairs: [
      ['COUNT(*)', 'how many rows'],
      ['SUM(price)', 'the total'],
      ['AVG(price)', 'the mean'],
      ['MAX(price)', 'the largest value'],
    ],
    explain: 'COUNT(column) skips NULLs while COUNT(*) does not — an easy way to get two different answers.',
  },
  {
    id: 'sql.group.1',
    concepts: ['sql.groupby'],
    difficulty: 4,
    kind: 'assemble',
    prompt: 'Build a query counting orders per customer.',
    answer: ['SELECT', 'customer_id', ',', 'COUNT(*)', 'FROM', 'orders', 'GROUP BY', 'customer_id', ';'],
    distractors: ['HAVING', 'ORDER BY', 'WHERE'],
    explain: 'Every non-aggregated column in SELECT has to appear in GROUP BY.',
  },
  {
    id: 'sql.group.2',
    concepts: ['sql.groupby'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'How many rows come back?',
    code: 'SELECT country, COUNT(*)\nFROM users\nGROUP BY country;',
    options: ['One per user', 'One per distinct country', 'Exactly one', 'None'],
    answer: 1,
    explain: 'GROUP BY collapses many rows into one per group. That is the whole idea.',
  },
  {
    id: 'sql.hav.1',
    concepts: ['sql.having'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What is the difference between WHERE and HAVING?',
    options: [
      'WHERE filters rows before grouping; HAVING filters groups after aggregating',
      'HAVING is faster',
      'They are the same',
      'WHERE only works on numbers',
    ],
    answer: [0],
    explain: 'You cannot use COUNT(*) in WHERE — at that point the counting has not happened yet.',
  },
  {
    id: 'sql.hav.2',
    concepts: ['sql.having', 'sql.groupby'],
    difficulty: 5,
    kind: 'blank',
    prompt: 'Keep only the customers with more than 5 orders.',
    template: 'SELECT customer_id, COUNT(*) AS n\nFROM orders\nGROUP BY customer_id\n{{0}} COUNT(*) > 5;',
    blanks: [{ accept: ['HAVING'], width: 8 }],
    explain: 'Some databases let you write HAVING n > 5 using the alias; not all do.',
  },

  /* ---------------------------------------------------------- sql.joins */
  {
    id: 'sql.join.1',
    concepts: ['sql.joins'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each join to what it keeps.',
    pairs: [
      ['INNER JOIN', 'only rows matching on both sides'],
      ['LEFT JOIN', 'every left row, with NULLs where nothing matched'],
      ['CROSS JOIN', 'every combination of both tables'],
    ],
    explain: 'LEFT JOIN plus WHERE right.id IS NULL is how you find the rows with no match.',
  },
  {
    id: 'sql.join.2',
    concepts: ['sql.joins'],
    difficulty: 5,
    kind: 'assemble',
    prompt: 'Build a query listing every order with its customer name.',
    answer: [
      'SELECT',
      'o.id, c.name',
      'FROM',
      'orders o',
      'JOIN',
      'customers c',
      'ON',
      'o.customer_id = c.id',
      ';',
    ],
    distractors: ['GROUP BY', 'WHERE', 'UNION'],
    explain: 'The ON clause says how the two tables line up. Leave it out and you get every combination.',
  },
  {
    id: 'sql.join.3',
    concepts: ['sql.joins'],
    difficulty: 5,
    kind: 'predict',
    prompt: 'Two tables have 1,000 rows each. How many rows does a join with no ON clause return?',
    code: 'SELECT * FROM a, b;',
    options: ['1,000', '2,000', '1,000,000', '0'],
    answer: 2,
    explain: 'A cartesian product. This is why a forgotten ON clause takes down a production database.',
  },
  {
    id: 'sql.keys.1',
    concepts: ['sql.keys'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each key to its job.',
    pairs: [
      ['PRIMARY KEY', 'uniquely identifies a row in this table'],
      ['FOREIGN KEY', 'points at a row in another table'],
      ['UNIQUE', 'no two rows may share this value'],
      ['INDEX', 'makes lookups on a column fast'],
    ],
    explain: 'A foreign key also stops you deleting a row that something else still points at.',
  },
  {
    id: 'sql.keys.2',
    concepts: ['sql.keys'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'A query filtering on a column is slow. What is usually the first thing to try?',
    options: [
      'Add an index on that column',
      'Add more RAM',
      'Rewrite it with SELECT *',
      'Split the table',
    ],
    answer: [0],
    explain: 'An index turns a full scan into a lookup — at the cost of slightly slower writes and more disk.',
  },

  /* ---------------------------------------------------------- sql.write */
  {
    id: 'sql.ins.1',
    concepts: ['sql.insert'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Complete the insert.',
    template: "INSERT INTO users (name, age)\n{{0}} ('Ada', 36);",
    blanks: [{ accept: ['VALUES'], width: 8 }],
    explain: 'Naming the columns means the statement keeps working when the table gains a new one.',
  },
  {
    id: 'sql.upd.1',
    concepts: ['sql.update'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This updates every row in the table. Which line is missing something?',
    code: 'UPDATE users\nSET active = 0;',
    buggyLine: 2,
    why: {
      options: ['There is no WHERE clause', 'active should be a string', 'UPDATE needs a JOIN'],
      answer: 0,
    },
    explain: 'Run the SELECT with the same WHERE first, look at the row count, then change it to an UPDATE.',
  },
  {
    id: 'sql.upd.2',
    concepts: ['sql.update'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What does a transaction give you?',
    options: [
      'All the statements commit together, or none of them do',
      'Faster queries',
      'Automatic indexes',
      'A backup',
    ],
    answer: [0],
    explain: 'BEGIN, then your statements, then COMMIT — or ROLLBACK when the row count looks wrong.',
  },
  {
    id: 'sql.sch.1',
    concepts: ['sql.schema'],
    difficulty: 4,
    kind: 'order',
    prompt: 'Order a CREATE TABLE statement.',
    lines: ['CREATE TABLE users (', '  id INTEGER PRIMARY KEY,', '  name TEXT NOT NULL,', '  age INTEGER', ');'],
    explain: 'NOT NULL on the columns that must always have a value is the cheapest data quality you can buy.',
  },
  {
    id: 'sql.sch.2',
    concepts: ['sql.schema'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why store money as an integer number of cents rather than a float?',
    options: [
      'Floats cannot represent 0.10 exactly, so totals drift',
      'Integers sort better',
      'Floats are not supported',
      'It uses less space',
    ],
    answer: [0],
    explain: 'Or use a DECIMAL type. Never a float — the rounding errors turn up in an audit.',
  },
]);
