import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const sqlExtraSkills: Skill[] = [
  {
    id: 'sql.deeper',
    title: 'Subqueries and CTEs',
    blurb: 'Queries that build on queries, without a temporary table in sight.',
    concepts: ['sql.subquery', 'sql.cte', 'sql.window'],
    requires: ['sql.aggregate'],
    level: 'advanced',
    tags: ['data'],
    unit: 'Analysis',
  },
  {
    id: 'sql.speed',
    title: 'Indexes and plans',
    blurb: 'Why a query is slow, and what an index actually costs.',
    concepts: ['sql.index', 'sql.explain'],
    requires: ['sql.joins'],
    level: 'advanced',
    tags: ['data', 'systems'],
    unit: 'Analysis',
  },
];

export const sqlExtra = forTrack('sql', [
  {
    id: 'sql.sel.x1',
    concepts: ['sql.select'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which query returns every column of every row in customers?',
    options: ['SELECT * FROM customers;', 'GET ALL customers;', 'SELECT customers;', 'FROM customers SELECT *;'],
    answer: [0],
    explain: 'SELECT then FROM. The star means every column, and is fine while exploring.',
  },
  {
    id: 'sql.sel.x2',
    concepts: ['sql.select'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Ask for just the name column.',
    template: '{{0}} name {{1}} customers;',
    blanks: [{ accept: ['SELECT', 'select'], width: 7 }, { accept: ['FROM', 'from'], width: 5 }],
    explain: 'Naming the columns you want is both faster and safer than SELECT * in real code.',
  },
  {
    id: 'sql.where.x1',
    concepts: ['sql.where'],
    difficulty: 2,
    level: 2,
    kind: 'assemble',
    prompt: 'Build a query for customers in France.',
    answer: ['SELECT', '*', 'FROM', 'customers', 'WHERE', "country = 'FR'", ';'],
    distractors: ['HAVING', 'GROUP BY'],
    explain: 'WHERE filters rows before grouping. HAVING filters groups after it.',
  },
  {
    id: 'sql.where.x2',
    concepts: ['sql.where'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'Table has ages 10, 20 and 30. How many rows come back?',
    code: 'SELECT * FROM people WHERE age > 10 AND age <= 30;',
    options: ['2', '3', '1', '0'],
    answer: 0,
    explain: '> excludes the boundary, <= includes it. Half of SQL bugs live on that line.',
  },
  {
    id: 'sql.order.x1',
    concepts: ['sql.order'],
    difficulty: 2,
    level: 2,
    kind: 'blank',
    prompt: 'Sort newest first.',
    template: 'SELECT * FROM posts ORDER BY created_at {{0}};',
    blanks: [{ accept: ['DESC', 'desc'], width: 5 }],
    explain: 'ASC is the default, so DESC is the one you have to say out loud.',
  },
  {
    id: 'sql.like.x1',
    concepts: ['sql.like'],
    difficulty: 2,
    level: 3,
    kind: 'choice',
    prompt: "Which pattern finds every email at example.com?",
    options: ["email LIKE '%@example.com'", "email LIKE '@example.com'", "email = '%@example.com'", "email LIKE '_@example.com'"],
    answer: [0],
    explain: '% matches any run of characters, _ matches exactly one.',
  },
  {
    id: 'sql.null.x1',
    concepts: ['sql.null'],
    difficulty: 3,
    level: 3,
    kind: 'predict',
    prompt: 'Which rows does this return, given some rows have NULL in country?',
    code: "SELECT * FROM users WHERE country != 'FR';",
    options: [
      'Only rows with a country that is not FR — NULL rows are excluded',
      'Every row except the FR ones, NULLs included',
      'All rows',
      'No rows',
    ],
    answer: 0,
    explain: 'NULL is unknown, and any comparison with unknown is unknown, which is not true. Use IS NULL.',
  },
  {
    id: 'sql.op.x1',
    concepts: ['sql.operators'],
    difficulty: 2,
    level: 3,
    kind: 'match',
    prompt: 'Match each operator to what it does.',
    pairs: [
      ['BETWEEN', 'Inclusive range test'],
      ['IN', 'Membership of a list'],
      ['IS NULL', 'Tests for missing values'],
      ['LIKE', 'Pattern match on text'],
    ],
    explain: 'BETWEEN includes both ends, which surprises people writing date ranges.',
  },
  {
    id: 'sql.agg.x1',
    concepts: ['sql.aggregate'],
    difficulty: 3,
    level: 4,
    kind: 'predict',
    prompt: 'Column score holds 1, NULL and 3. What does this return?',
    code: 'SELECT COUNT(score), COUNT(*), SUM(score) FROM t;',
    options: ['2, 3, 4', '3, 3, 4', '2, 2, 4', '3, 3, NULL'],
    answer: 0,
    explain: 'COUNT(column) skips NULLs, COUNT(*) counts rows, and SUM ignores NULLs too.',
  },

  /* ---------------------------------------------------------- sql.deeper */
  {
    id: 'sql.deep.1',
    concepts: ['sql.subquery'],
    difficulty: 4,
    level: 6,
    kind: 'order',
    prompt: 'Find customers who have ever ordered.',
    lines: ['SELECT name', 'FROM customers', 'WHERE id IN (', '    SELECT customer_id FROM orders', ');'],
    explain: 'A subquery in WHERE is read inside out. EXISTS often reads better and stops at the first match.',
  },
  {
    id: 'sql.deep.2',
    concepts: ['sql.cte'],
    difficulty: 4,
    level: 6,
    kind: 'blank',
    prompt: 'Name a subquery so the main query stays readable.',
    template: '{{0}} recent AS (\n    SELECT * FROM orders WHERE created_at > date(\'now\', \'-7 days\')\n)\nSELECT count(*) FROM recent;',
    blanks: [{ accept: ['WITH', 'with'], width: 5 }],
    explain: 'A CTE is a named result you can reference. Two of them beat one query nested three deep.',
  },
  {
    id: 'sql.deep.3',
    concepts: ['sql.window'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'What does a window function do that GROUP BY does not?',
    options: [
      'Computes across a set of rows while keeping every row in the output',
      'Runs faster',
      'Works without an ORDER BY',
      'Aggregates several tables at once',
    ],
    answer: [0],
    explain: 'Running totals and per-row ranks need the row *and* the aggregate. That is the whole point.',
  },
  {
    id: 'sql.deep.4',
    concepts: ['sql.window'],
    difficulty: 5,
    level: 9,
    kind: 'blank',
    prompt: 'Number each customer’s orders, newest first.',
    template: 'SELECT id,\n       ROW_NUMBER() {{0}} (PARTITION BY customer_id ORDER BY created_at DESC) AS n\nFROM orders;',
    blanks: [{ accept: ['OVER', 'over'], width: 5 }],
    explain: 'PARTITION BY restarts the numbering per customer; ORDER BY decides what "first" means.',
  },

  /* ----------------------------------------------------------- sql.speed */
  {
    id: 'sql.fast.1',
    concepts: ['sql.index'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What does an index cost you?',
    options: [
      'Disk space, and slower inserts and updates, since the index must be maintained',
      'Nothing',
      'Query correctness',
      'The ability to use ORDER BY',
    ],
    answer: [0],
    explain: 'Indexes are a trade. On a write-heavy table, an unused index is pure loss.',
  },
  {
    id: 'sql.fast.2',
    concepts: ['sql.index'],
    difficulty: 5,
    level: 8,
    kind: 'bug',
    prompt: 'There is an index on created_at, and this query still scans the table. Which line is why?',
    code: 'SELECT *\nFROM orders\nWHERE date(created_at) = date(\'now\')\nORDER BY created_at;',
    buggyLine: 3,
    why: {
      options: [
        'Wrapping the column in a function stops the index being usable',
        'ORDER BY defeats the index',
        'SELECT * defeats the index',
        'date() is not a real function',
      ],
      answer: 0,
    },
    explain: 'Compare the bare column to a range instead, and the index comes back into play.',
  },
  {
    id: 'sql.fast.3',
    concepts: ['sql.explain'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'What does EXPLAIN tell you?',
    options: [
      'How the database plans to run the query — which indexes and joins it will use',
      'How long the query took',
      'Whether the SQL is valid',
      'The rows it will return',
    ],
    answer: [0],
    explain: 'EXPLAIN ANALYZE actually runs it and reports real timings, which is usually what you want.',
  },
  {
    id: 'sql.fast.4',
    concepts: ['sql.explain', 'sql.joins'],
    difficulty: 5,
    level: 9,
    kind: 'choice',
    prompt: 'A join between two large tables is slow. What do you check first?',
    options: [
      'Whether the join columns are indexed on both sides',
      'The column order in SELECT',
      'Whether the tables have primary keys at all',
      'The database version',
    ],
    answer: [0],
    explain: 'A join without an index on the joining column is a nested loop over everything.',
  },
]);
