import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const typescriptExtraSkills: Skill[] = [
  {
    id: 'ts.classes',
    title: 'Classes and access',
    blurb: 'Typed classes, readonly fields, and what private actually protects.',
    concepts: ['ts.classes', 'ts.access', 'ts.abstract'],
    requires: ['ts.shapes'],
    level: 'applied',
    tags: ['apps'],
    unit: 'Going further',
  },
  {
    id: 'ts.config',
    title: 'Config and the compiler',
    blurb: 'What tsc is doing, what it refuses to do, and which flags earn their keep.',
    concepts: ['ts.tsconfig', 'ts.erasure', 'ts.declaration'],
    requires: ['ts.basics'],
    level: 'applied',
    tags: ['apps', 'web'],
    unit: 'Going further',
  },
];

export const typescriptExtra = forTrack('typescript', [
  {
    id: 'ts.ann.x1',
    concepts: ['ts.annotations'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Say that count holds a number.',
    template: 'let count: {{0}} = 0;',
    blanks: [{ accept: ['number'], width: 7 }],
    explain: 'The annotation goes after the name, separated by a colon.',
  },
  {
    id: 'ts.ann.x2',
    concepts: ['ts.annotations'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which annotation is right for a list of strings?',
    options: ['string[]', 'Array<String>', '[string]', 'strings'],
    answer: [0],
    explain: 'string[] and Array<string> are the same thing. The capital-S String is the wrapper object, not the type you want.',
  },
  {
    id: 'ts.inf.x1',
    concepts: ['ts.inference'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What type does TypeScript infer here?',
    code: 'let count = 0;',
    options: ['number', '0', 'any', 'Number'],
    answer: 0,
    explain: 'let widens to the general type, because you are plainly going to reassign it. const would have kept the literal 0.',
  },
  {
    id: 'ts.inf.x2',
    concepts: ['ts.inference'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'What type is `items` here?',
    code: 'const items = [];\nitems.push("a");',
    options: ['any[], and the push tells you nothing', 'string[]', 'never[]', 'unknown[]'],
    answer: 0,
    explain: 'An empty array literal has nothing to infer from, so it starts as any[] (never[] under strict inference). Annotate it: const items: string[] = [].',
  },
  {
    id: 'ts.prim.x1',
    concepts: ['ts.primitives'],
    difficulty: 2,
    level: 2,
    kind: 'match',
    prompt: 'Match each type to what belongs to it.',
    pairs: [
      ['boolean', 'true'],
      ['number', '3.14'],
      ['string', '"hi"'],
      ['null', 'null'],
    ],
    explain: 'There is no int or float in TypeScript: every number is a number.',
  },
  {
    id: 'ts.iface.x1',
    concepts: ['ts.interfaces'],
    difficulty: 2,
    level: 3,
    kind: 'order',
    prompt: 'Describe a user with a name and an age.',
    lines: ['interface User {', '  name: string;', '  age: number;', '}'],
    explain: 'Members are separated by semicolons or newlines — commas work too, but pick one and keep it.',
  },
  {
    id: 'ts.opt.x1',
    concepts: ['ts.optional'],
    difficulty: 2,
    level: 3,
    kind: 'blank',
    prompt: 'Make the title argument optional, so greet("Ada") compiles.',
    template: 'function greet(name: string, title{{0}}: string) {\n  return title ? `${title} ${name}` : name;\n}',
    blanks: [{ accept: ['?'], width: 2 }],
    explain: 'An optional parameter has to come after the required ones, and inside the function its type is string | undefined.',
  },
  {
    id: 'ts.alias.x1',
    concepts: ['ts.aliases'],
    difficulty: 3,
    level: 3,
    kind: 'choice',
    prompt: 'When must you use a type alias rather than an interface?',
    options: [
      'For a union, like type Id = string | number',
      'For an object shape',
      'For anything with methods',
      'They are interchangeable everywhere',
    ],
    answer: [0],
    explain: 'Interfaces describe object shapes and can be merged; aliases can name anything, unions included.',
  },
  {
    id: 'ts.union.x1',
    concepts: ['ts.unions'],
    difficulty: 3,
    level: 4,
    kind: 'predict',
    prompt: 'Does this compile?',
    code: 'let id: string | number;\nid = 7;\nid = "7";',
    options: ['Yes, both assignments are allowed', 'No, the second fails', 'No, the first fails', 'Only with any'],
    answer: 0,
    explain: 'A union accepts any member. Narrowing is what you need before you can use it as one.',
  },
  {
    id: 'ts.narrow.x1',
    concepts: ['ts.narrowing'],
    difficulty: 3,
    level: 4,
    kind: 'blank',
    prompt: 'Narrow the union before calling a string method.',
    template: 'function show(id: string | number) {\n  if ({{0}} id === "string") {\n    console.log(id.toUpperCase());\n  }\n}',
    blanks: [{ accept: ['typeof'], width: 7 }],
    explain: 'typeof is a type guard: inside the branch, TypeScript knows id is a string.',
  },

  /* ----------------------------------------------------------- ts.classes */
  {
    id: 'ts.cls.1',
    concepts: ['ts.classes'],
    difficulty: 3,
    level: 5,
    kind: 'order',
    prompt: 'Write a typed class with a constructor.',
    lines: ['class Point {', '  constructor(', '    public x: number,', '    public y: number,', '  ) {}', '}'],
    explain: 'Parameter properties: marking a constructor argument public declares and assigns the field in one go.',
  },
  {
    id: 'ts.cls.2',
    concepts: ['ts.access'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What does `private` actually stop?',
    options: [
      'Access from outside the class at compile time — the field is still there at runtime',
      'Any access at runtime',
      'Serialisation of the field',
      'Subclasses from reading it, but not other code',
    ],
    answer: [0],
    explain: 'For real runtime privacy use a #field. private is a promise between you and the compiler.',
  },
  {
    id: 'ts.cls.3',
    concepts: ['ts.access'],
    difficulty: 4,
    level: 6,
    kind: 'bug',
    prompt: 'Which line will the compiler reject?',
    code: 'class Box {\n  readonly size = 4;\n  grow() {\n    this.size = 5;\n  }\n}',
    buggyLine: 4,
    why: {
      options: [
        'readonly fields can only be set in the declaration or the constructor',
        'size needs a type annotation',
        'grow needs a return type',
        'Classes cannot have fields',
      ],
      answer: 0,
    },
    explain: 'readonly is the field-level version of const, and it is checked everywhere but the constructor.',
  },
  {
    id: 'ts.cls.4',
    concepts: ['ts.abstract'],
    difficulty: 5,
    level: 7,
    kind: 'choice',
    prompt: 'What is an abstract class for?',
    options: [
      'A base class that cannot be instantiated and can demand methods from its subclasses',
      'A class with no fields',
      'A class that only exists at compile time',
      'A faster class',
    ],
    answer: [0],
    explain: 'Use it when there is shared behaviour to inherit. Where there is not, an interface is lighter.',
  },
  {
    id: 'ts.cls.5',
    concepts: ['ts.classes'],
    difficulty: 5,
    level: 8,
    kind: 'write',
    prompt: 'Write a Queue class with add, take and size, and print the results shown.',
    runLang: 'typescript',
    starter:
      'class Queue {\n  // your code\n}\n\nconst q = new Queue();\nq.add(1);\nq.add(2);\nconsole.log(q.size());\nconsole.log(q.take());\nconsole.log(q.size());\n',
    solution:
      'class Queue {\n  private items: number[] = [];\n  add(x: number): void {\n    this.items.push(x);\n  }\n  take(): number | undefined {\n    return this.items.shift();\n  }\n  size(): number {\n    return this.items.length;\n  }\n}\n\nconst q = new Queue();\nq.add(1);\nq.add(2);\nconsole.log(q.size());\nconsole.log(q.take());\nconsole.log(q.size());\n',
    tests: [{ name: 'first in, first out', expect: '2\n1\n1' }],
    mustContain: [{ pattern: 'class', label: 'use a class' }],
    explain: 'A queue takes from the front, a stack from the back. That one difference is the whole data structure.',
  },

  /* ------------------------------------------------------------ ts.config */
  {
    id: 'ts.cfg.1',
    concepts: ['ts.erasure'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'What happens to types when TypeScript compiles?',
    options: [
      'They are erased — the output is plain JavaScript with the annotations removed',
      'They become runtime checks',
      'They are stored in a sidecar file the runtime reads',
      'They are compiled into classes',
    ],
    answer: [0],
    explain: 'This is why you cannot ask "is this an interface" at runtime. There is nothing left to ask.',
  },
  {
    id: 'ts.cfg.2',
    concepts: ['ts.tsconfig'],
    difficulty: 4,
    level: 6,
    kind: 'match',
    prompt: 'Match each compiler option to what it does.',
    pairs: [
      ['strict', 'Turns on the whole family of strict checks'],
      ['target', 'Which JavaScript version to emit'],
      ['noEmit', 'Type-check only, write nothing'],
      ['paths', 'Alias import prefixes to folders'],
    ],
    explain: 'strict is one flag that turns on about eight. Starting a project without it is a decision you will regret.',
  },
  {
    id: 'ts.cfg.3',
    concepts: ['ts.declaration'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What is a .d.ts file?',
    options: [
      'Types with no implementation, describing JavaScript that already exists',
      'A compiled TypeScript file',
      'A test file',
      'A config file',
    ],
    answer: [0],
    explain: 'It is how a library written in JavaScript can still be typed for everyone importing it.',
  },
  {
    id: 'ts.cfg.4',
    concepts: ['ts.erasure'],
    difficulty: 5,
    level: 8,
    kind: 'predict',
    prompt: 'What does the compiler emit for this?',
    code: 'interface User { name: string }\nconst u: User = { name: "Sam" };\nconsole.log(u.name);',
    options: [
      'const u = { name: "Sam" };\nconsole.log(u.name);',
      'The same code, with the interface kept',
      'A runtime check that u matches User',
      'An error',
    ],
    answer: 0,
    explain: 'The interface leaves no trace. Everything it did happened before the program ever ran.',
  },
  {
    id: 'ts.cfg.5',
    concepts: ['ts.tsconfig'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'Your build passes but the editor shows errors. What is the usual cause?',
    options: [
      'The editor and the build are using different tsconfig files or TypeScript versions',
      'The editor caches types for an hour',
      'Type errors are random',
      'The build never type-checks',
    ],
    answer: [0],
    explain: 'A bundler that only strips types will happily build code that tsc rejects. Run tsc --noEmit in CI.',
  },
]);
