import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'ts.basics',
    title: 'Types on values',
    blurb: 'Annotate what you must, and let inference do the rest.',
    concepts: ['ts.annotations', 'ts.inference', 'ts.primitives'],
    requires: [],
    level: 'intro',
    tags: ['web', 'apps'],
    unit: 'Foundations',
  },
  {
    id: 'ts.shapes',
    title: 'Describing objects',
    blurb: 'Interfaces, type aliases, optional and readonly properties.',
    concepts: ['ts.interfaces', 'ts.aliases', 'ts.optional'],
    requires: ['ts.basics'],
    level: 'core',
    tags: ['apps', 'web'],
    unit: 'Foundations',
  },
  {
    id: 'ts.unions',
    title: 'Unions and narrowing',
    blurb: 'One of several shapes, and how to prove which one you have.',
    concepts: ['ts.unions', 'ts.narrowing', 'ts.literal'],
    requires: ['ts.shapes'],
    level: 'core',
    tags: ['apps', 'interviews'],
    unit: 'Making types work',
  },
  {
    id: 'ts.functions',
    title: 'Typing functions',
    blurb: 'Parameters, return types, and why void is not undefined.',
    concepts: ['ts.fnTypes', 'ts.returns'],
    requires: ['ts.basics'],
    level: 'core',
    tags: ['apps'],
    unit: 'Making types work',
  },
  {
    id: 'ts.generics',
    title: 'Generics',
    blurb: 'Write it once, keep the type information.',
    concepts: ['ts.generics', 'ts.utility'],
    requires: ['ts.unions', 'ts.functions'],
    level: 'advanced',
    tags: ['apps', 'interviews'],
    unit: 'Going further',
  },
  {
    id: 'ts.strict',
    title: 'Strict mode',
    blurb: 'null, undefined, unknown, and the any that eats your safety net.',
    concepts: ['ts.strictnull', 'ts.unknown'],
    requires: ['ts.unions'],
    level: 'applied',
    tags: ['apps'],
    unit: 'Going further',
  },
];

export const typescriptTrack: Track = {
  id: 'typescript',
  name: 'TypeScript',
  kind: 'language',
  tagline: 'JavaScript that tells you when you are wrong',
  blurb:
    'A type layer over JavaScript that catches whole classes of bug before you run anything. Now the default for serious front-end and Node work.',
  lang: 'typescript',
  runLang: 'typescript',
  mark: 'TS',
  tags: ['web', 'apps', 'interviews'],
  goals: ['web', 'apps', 'interviews'],
  slope: 3,
  transfersFrom: ['javascript'],
  skills,
};

export const typescriptExercises = forTrack('typescript', [
  /* ----------------------------------------------------------- ts.basics */
  {
    id: 'ts.ann.1',
    concepts: ['ts.annotations', 'ts.primitives'],
    difficulty: 2,
    kind: 'blank',
    prompt: 'Annotate count as a number.',
    template: 'let count{{0}} number = 0;',
    blanks: [{ accept: [':'], width: 3 }],
    explain: 'The type goes after a colon, following the name. It is erased entirely at runtime.',
  },
  {
    id: 'ts.ann.2',
    concepts: ['ts.primitives'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each value to its TypeScript type.',
    pairs: [
      ['42', 'number'],
      ['"hi"', 'string'],
      ['true', 'boolean'],
      ['[1, 2]', 'number[]'],
    ],
    explain: 'There is no int or float — every JavaScript number is just `number`.',
  },
  {
    id: 'ts.infer.1',
    concepts: ['ts.inference'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What type does TypeScript infer for `const x = "hello"`?',
    options: ['string', '"hello"', 'any', 'String'],
    answer: [1],
    explain: 'const cannot be reassigned, so TypeScript narrows it to the literal type. With let it would be string.',
  },
  {
    id: 'ts.infer.2',
    concepts: ['ts.inference', 'ts.annotations'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'When is an explicit annotation worth writing?',
    options: [
      'Always, on every variable',
      'On function parameters and public APIs, where inference has nothing to go on',
      'Never, inference is enough',
      'Only on numbers',
    ],
    answer: [1],
    explain: 'Annotate the boundaries, infer the middle. Annotating everything is noise nobody reads.',
  },
  {
    id: 'ts.ann.3',
    concepts: ['ts.annotations'],
    difficulty: 3,
    kind: 'bug',
    prompt: 'This will not compile. Which line is the problem?',
    code: 'let total: number = 0;\ntotal = "ten";\nconsole.log(total);',
    buggyLine: 2,
    why: {
      options: ['A string cannot be assigned to a number', 'total should be const', 'The semicolon is missing'],
      answer: 0,
    },
    explain: 'This is the whole pitch: the mistake is caught while you type, not at three in the morning.',
  },

  /* ----------------------------------------------------------- ts.shapes */
  {
    id: 'ts.iface.1',
    concepts: ['ts.interfaces'],
    difficulty: 3,
    kind: 'order',
    prompt: 'Order the lines of an interface for a user.',
    lines: ['interface User {', '  name: string;', '  age: number;', '}'],
    explain: 'Properties are separated by semicolons or newlines, and there is no equals sign after the name.',
  },
  {
    id: 'ts.alias.1',
    concepts: ['ts.aliases', 'ts.interfaces'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'When must you use `type` rather than `interface`?',
    options: [
      'For objects',
      'For unions, tuples and mapped types, which interfaces cannot express',
      'For classes',
      'They are completely interchangeable',
    ],
    answer: [1],
    explain: 'Interfaces describe object shapes and can merge; type aliases can name anything at all.',
  },
  {
    id: 'ts.opt.1',
    concepts: ['ts.optional'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Make nickname optional.',
    template: 'interface User {\n  name: string;\n  nickname{{0}}: string;\n}',
    blanks: [{ accept: ['?'], width: 2 }],
    explain: 'An optional property may be missing entirely, so its type becomes string | undefined.',
  },
  {
    id: 'ts.opt.2',
    concepts: ['ts.optional'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'What does TypeScript report here?',
    code: 'interface U { nickname?: string }\nconst u: U = {};\nconsole.log(u.nickname.length);',
    options: [
      'Nothing, it compiles',
      "Object is possibly 'undefined'",
      'Property nickname does not exist',
      'Cannot find name u',
    ],
    answer: 1,
    explain: 'Optional means it might not be there. Use u.nickname?.length, or check it first.',
  },
  {
    id: 'ts.shapes.write.1',
    concepts: ['ts.interfaces', 'ts.annotations'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Give Point its x and y number properties, then make sum(p) return their total.',
    runLang: 'typescript',
    starter:
      'interface Point {\n}\n\nfunction sum(p: Point): number {\n  return 0;\n}\n\nconsole.log(sum({ x: 3, y: 4 }));',
    solution:
      'interface Point {\n  x: number;\n  y: number;\n}\n\nfunction sum(p: Point): number {\n  return p.x + p.y;\n}\n\nconsole.log(sum({ x: 3, y: 4 }));',
    tests: [{ name: 'sums the coordinates', expect: '7' }],
    mustContain: [
      { pattern: 'x: number', label: 'declare x as a number' },
      { pattern: 'y: number', label: 'declare y as a number' },
    ],
    explain:
      'The interface vanishes when compiled - it exists only so the compiler can check that p really has an x and a y.',
  },

  /* ----------------------------------------------------------- ts.unions */
  {
    id: 'ts.union.1',
    concepts: ['ts.unions'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Let id be either a string or a number.',
    template: 'let id: string {{0}} number;',
    blanks: [{ accept: ['|'], width: 2 }],
    explain: 'The vertical bar reads as "or". You can only use members both sides agree on until you narrow it.',
  },
  {
    id: 'ts.lit.1',
    concepts: ['ts.literal'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What does `type Status = "idle" | "busy"` give you?',
    options: [
      'Two string variables',
      'A type that allows only those two exact strings',
      'An enum',
      'A runtime check',
    ],
    answer: [1],
    explain: 'Literal unions are the lightest way to model a state machine, and they autocomplete.',
  },
  {
    id: 'ts.narrow.1',
    concepts: ['ts.narrowing'],
    difficulty: 4,
    kind: 'order',
    prompt: 'Order the lines that narrow a union before using it.',
    lines: [
      'function show(id: string | number) {',
      '  if (typeof id === "string") {',
      '    return id.toUpperCase();',
      '  }',
      '  return id.toFixed(0);',
      '}',
    ],
    explain: 'Inside the if, TypeScript knows id is a string. After it, only number is left.',
  },
  {
    id: 'ts.narrow.2',
    concepts: ['ts.narrowing', 'ts.unions'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'This does not compile. Which line does TypeScript reject?',
    code: 'function len(x: string | number) {\n  return x.length;\n}',
    buggyLine: 2,
    why: {
      options: [
        'number has no length, so the union does not either',
        'x should be x()',
        'The function needs a return type',
      ],
      answer: 0,
    },
    explain: 'A union only offers what every member has. Narrow with typeof before reaching for .length.',
  },
  {
    id: 'ts.union.2',
    concepts: ['ts.unions', 'ts.literal'],
    difficulty: 4,
    kind: 'assemble',
    prompt: 'Build a type that is exactly one of the three traffic-light colours.',
    answer: ['type', 'Light', '=', '"red"', '|', '"amber"', '|', '"green"'],
    distractors: ['interface', '&', 'enum'],
    explain: 'Reach for a literal union before an enum: it is simpler and compiles away to nothing.',
  },

  /* -------------------------------------------------------- ts.functions */
  {
    id: 'ts.fn.1',
    concepts: ['ts.fnTypes'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Type both the parameter and the return value.',
    template: 'function double(n{{0}} number){{1}} number {\n  return n * 2;\n}',
    blanks: [
      { accept: [':'], width: 3 },
      { accept: [':'], width: 3 },
    ],
    explain: 'The return type goes after the parameter list. TypeScript can infer it, but writing it documents intent.',
  },
  {
    id: 'ts.ret.1',
    concepts: ['ts.returns'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What does a return type of `void` mean?',
    options: [
      'The function returns undefined and callers should ignore whatever comes back',
      'The function returns null',
      'The function never finishes',
      'The function throws',
    ],
    answer: [0],
    explain: '`never` is the one that means "never finishes" — for functions that always throw or loop forever.',
  },
  {
    id: 'ts.fn.2',
    concepts: ['ts.fnTypes'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each signature to what it describes.',
    pairs: [
      ['(n: number) => string', 'takes a number, returns a string'],
      ['() => void', 'takes nothing, returns nothing useful'],
      ['(a: string, b?: string) => string', 'second argument is optional'],
    ],
    explain: 'A function type uses => even when the function itself is written with the function keyword.',
  },
  {
    id: 'ts.fn.write.1',
    concepts: ['ts.fnTypes', 'ts.returns'],
    difficulty: 4,
    kind: 'write',
    prompt: 'Write a typed function initials(first, last) returning e.g. "A.L." for Ada Lovelace, and log it.',
    runLang: 'typescript',
    starter: 'function initials(first: string, last: string): string {\n  \n}\nconsole.log(initials("Ada", "Lovelace"));',
    solution:
      'function initials(first: string, last: string): string {\n  return first[0] + "." + last[0] + ".";\n}\nconsole.log(initials("Ada", "Lovelace"));',
    tests: [{ name: 'Ada Lovelace', expect: 'A.L.' }],
    explain: 'Indexing a string gives a string, so the annotated return type checks out.',
  },

  /* --------------------------------------------------------- ts.generics */
  {
    id: 'ts.gen.1',
    concepts: ['ts.generics'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'Why write `function first<T>(xs: T[]): T` instead of using any?',
    options: [
      'It is shorter',
      'It keeps the caller type: first(["a"]) is a string, not any',
      'It runs faster',
      'any is not allowed in TypeScript',
    ],
    answer: [1],
    explain: 'Generics carry the type through the function. any drops it and silences every check downstream.',
  },
  {
    id: 'ts.gen.2',
    concepts: ['ts.generics'],
    difficulty: 5,
    kind: 'blank',
    prompt: 'Make this identity function generic.',
    template: 'function identity{{0}}(value: T): T {\n  return value;\n}',
    blanks: [{ accept: ['<T>'], width: 5 }],
    explain: 'The type parameter is declared in angle brackets before the arguments, like a parameter for types.',
  },
  {
    id: 'ts.util.1',
    concepts: ['ts.utility'],
    difficulty: 5,
    kind: 'match',
    prompt: 'Match each utility type to what it produces.',
    pairs: [
      ['Partial<User>', 'every property optional'],
      ['Pick<User, "name">', 'only the named properties'],
      ['Omit<User, "id">', 'everything except the named properties'],
      ['Readonly<User>', 'nothing can be reassigned'],
    ],
    explain: 'These four cover most day-to-day type surgery without writing a mapped type by hand.',
  },
  {
    id: 'ts.gen.3',
    concepts: ['ts.generics', 'ts.utility'],
    difficulty: 5,
    kind: 'predict',
    prompt: 'What is the type of `result` here?',
    code: 'function wrap<T>(v: T): T[] {\n  return [v];\n}\nconst result = wrap("hi");',
    options: ['any[]', 'string[]', 'T[]', 'unknown[]'],
    answer: 1,
    explain: 'T is filled in from the argument at the call site — no annotation needed.',
  },

  /* ----------------------------------------------------------- ts.strict */
  {
    id: 'ts.null.1',
    concepts: ['ts.strictnull'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What does strictNullChecks change?',
    options: [
      'null and undefined stop being assignable to every type',
      'It bans null entirely',
      'It only affects arrays',
      'It makes compilation faster',
    ],
    answer: [0],
    explain: 'Without it, every type silently includes null. With it, you have to say so and then handle it.',
  },
  {
    id: 'ts.null.2',
    concepts: ['ts.strictnull'],
    difficulty: 5,
    kind: 'assemble',
    prompt: 'Safely read the length of a possibly-missing name.',
    answer: ['user', '?.', 'name', '?.', 'length'],
    distractors: ['!', '.', '||'],
    explain: 'Optional chaining short-circuits to undefined rather than throwing on a missing link.',
  },
  {
    id: 'ts.unknown.1',
    concepts: ['ts.unknown'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'Why prefer unknown over any for a parsed JSON payload?',
    options: [
      'unknown is faster',
      'unknown forces you to check the shape before using it; any lets every mistake through',
      'any does not exist in strict mode',
      'They behave the same',
    ],
    answer: [1],
    explain: 'any is a hole in the type system. unknown is honest: "something arrived, prove what it is".',
  },
  {
    id: 'ts.unknown.2',
    concepts: ['ts.unknown', 'ts.narrowing'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'Which line does the compiler reject?',
    code: 'function handle(data: unknown) {\n  return data.name;\n}',
    buggyLine: 2,
    why: {
      options: [
        "You must narrow unknown before reading properties from it",
        'data should be optional',
        'The function needs a return type',
      ],
      answer: 0,
    },
    explain: 'Check with typeof data === "object" && data !== null && "name" in data, then read it.',
  },
]);
