import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'ue5.editor',
    title: 'Around the editor',
    blurb: 'Viewport, Outliner, Content Browser, and where everything actually lives.',
    concepts: ['ue5.viewport', 'ue5.outliner', 'ue5.assets'],
    requires: [],
    level: 'intro',
    tags: ['games', 'graphics'],
    unit: 'The editor',
  },
  {
    id: 'ue5.actors',
    title: 'Actors and components',
    blurb: 'The thing in the world, and the parts bolted onto it.',
    concepts: ['ue5.actors', 'ue5.components', 'ue5.transform'],
    requires: ['ue5.editor'],
    level: 'core',
    tags: ['games'],
    unit: 'The editor',
  },
  {
    id: 'ue5.blueprints',
    title: 'Blueprint basics',
    blurb: 'Execution wires, data wires, events and variables.',
    concepts: ['ue5.bpbasics', 'ue5.exec', 'ue5.bpvars'],
    requires: ['ue5.actors'],
    level: 'core',
    tags: ['games'],
    unit: 'Blueprints',
  },
  {
    id: 'ue5.logic',
    title: 'Blueprint logic',
    blurb: 'Branches, loops, functions, and keeping a graph readable.',
    concepts: ['ue5.branch', 'ue5.bploops', 'ue5.bpfunctions'],
    requires: ['ue5.blueprints'],
    level: 'core',
    tags: ['games'],
    unit: 'Blueprints',
  },
  {
    id: 'ue5.gameplay',
    title: 'Making it a game',
    blurb: 'Input, collision, spawning, and the framework classes.',
    concepts: ['ue5.input', 'ue5.collision', 'ue5.spawn', 'ue5.framework'],
    requires: ['ue5.logic'],
    level: 'applied',
    tags: ['games'],
    unit: 'Gameplay',
  },
  {
    id: 'ue5.render',
    title: 'Look and performance',
    blurb: 'Materials, Lumen, Nanite, and what actually costs you frames.',
    concepts: ['ue5.materials', 'ue5.lighting', 'ue5.perf'],
    requires: ['ue5.actors'],
    level: 'applied',
    tags: ['games', 'graphics'],
    unit: 'Rendering',
  },
];

export const ue5Track: Track = {
  id: 'ue5',
  name: 'Unreal Engine 5',
  kind: 'engine',
  tagline: 'Ship a game without writing C++ first',
  blurb:
    'Blueprints let you build real gameplay by wiring nodes together, and Lumen and Nanite give you film-grade lighting and geometry out of the box.',
  lang: 'blueprint',
  mark: 'UE',
  tags: ['games', 'graphics'],
  goals: ['games', 'curious'],
  slope: 4,
  transfersFrom: ['cpp', 'unity'],
  skills,
};

export const ue5Exercises = forTrack('ue5', [
  /* --------------------------------------------------------- ue5.editor */
  {
    id: 'ue5.view.1',
    concepts: ['ue5.viewport'],
    difficulty: 1,
    kind: 'match',
    prompt: 'Match each viewport control to what it does.',
    pairs: [
      ['Right mouse + WASD', 'fly the camera through the level'],
      ['F', 'frame the selected actor'],
      ['Alt + left drag', 'orbit around the selection'],
      ['End', 'drop the selected actor onto the floor'],
    ],
    explain: 'Right-mouse-and-WASD is the one that turns the editor from confusing into comfortable.',
  },
  {
    id: 'ue5.view.2',
    concepts: ['ue5.viewport'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each transform gizmo shortcut to its mode.',
    pairs: [
      ['W', 'move'],
      ['E', 'rotate'],
      ['R', 'scale'],
    ],
    explain: 'The same three keys as most 3D tools. Spacebar cycles between them.',
  },
  {
    id: 'ue5.out.1',
    concepts: ['ue5.outliner'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'What does the World Outliner show you?',
    options: [
      'Every asset in the project',
      'Every actor currently placed in the open level',
      'The Blueprint graph',
      'Build errors',
    ],
    answer: [1],
    explain: 'The Content Browser holds assets on disk; the Outliner holds instances in this level.',
  },
  {
    id: 'ue5.asset.1',
    concepts: ['ue5.assets'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'Why should you never move or rename Unreal assets in Windows Explorer?',
    options: [
      'It is slower',
      'References are stored by path, so moving outside the editor breaks them',
      'Windows locks the files',
      'You can, it is fine',
    ],
    answer: [1],
    explain: 'Rename inside the Content Browser and Unreal fixes up every reference for you.',
  },
  {
    id: 'ue5.asset.2',
    concepts: ['ue5.assets'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each asset type to what it is.',
    pairs: [
      ['Static Mesh', 'geometry that does not deform'],
      ['Material', 'how a surface responds to light'],
      ['Blueprint Class', 'an actor with behaviour attached'],
      ['Level', 'a scene holding placed actors'],
    ],
    explain: 'A Material Instance is the cheap variant: change parameters without recompiling the shader.',
  },

  /* --------------------------------------------------------- ue5.actors */
  {
    id: 'ue5.actor.1',
    concepts: ['ue5.actors'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'What is an Actor?',
    options: [
      'Anything that can be placed in a level',
      'Only a character',
      'A material',
      'A camera',
    ],
    answer: [0],
    explain: 'Lights, meshes, triggers, cameras — all Actors. A Pawn is an Actor that can be possessed.',
  },
  {
    id: 'ue5.comp.1',
    concepts: ['ue5.components'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each component to what it adds to an Actor.',
    pairs: [
      ['Static Mesh Component', 'something visible'],
      ['Box Collision', 'a volume that detects overlaps'],
      ['Spring Arm', 'a camera boom that avoids walls'],
      ['Audio Component', 'a sound source in the world'],
    ],
    explain: 'An Actor is a bag of components. Composition, rather than a deep inheritance tree.',
  },
  {
    id: 'ue5.comp.2',
    concepts: ['ue5.components'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What is the Root Component?',
    options: [
      'The first component in the list, which every other component moves relative to',
      'The Actor itself',
      'The level',
      'The physics body',
    ],
    answer: [0],
    explain: 'Move the root and everything attached follows. Replace it carelessly and things detach.',
  },
  {
    id: 'ue5.tr.1',
    concepts: ['ue5.transform'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'One Unreal unit is one what?',
    options: ['Metre', 'Centimetre', 'Inch', 'Foot'],
    answer: [1],
    explain: 'A default human is about 180 units tall. Import a model at metre scale and it arrives tiny.',
  },
  {
    id: 'ue5.tr.2',
    concepts: ['ue5.transform'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each transform field to what it controls.',
    pairs: [
      ['Location', 'where it is'],
      ['Rotation', 'which way it faces'],
      ['Scale', 'how large it is'],
    ],
    explain: 'Non-uniform scale on a physics body causes strange collisions. Scale the mesh in your modelling tool instead.',
  },

  /* ----------------------------------------------------- ue5.blueprints */
  {
    id: 'ue5.bp.1',
    concepts: ['ue5.bpbasics', 'ue5.exec'],
    difficulty: 2,
    kind: 'wire',
    prompt: 'Wire Event BeginPlay so it prints a message when the game starts.',
    nodes: [
      { id: 'begin', title: 'Event BeginPlay', tone: 'event', x: 30, y: 60, outputs: ['exec'] },
      { id: 'print', title: 'Print String', subtitle: 'In String: Hello', tone: 'action', x: 300, y: 60, inputs: ['exec'], outputs: ['exec'] },
    ],
    links: [['begin:exec', 'print:exec']],
    explain: 'The white execution wire is the order things happen in. Without it the node never fires.',
  },
  {
    id: 'ue5.bp.2',
    concepts: ['ue5.exec'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What is the difference between the white wires and the coloured ones?',
    options: [
      'White carries execution order; coloured wires carry data of that type',
      'White is for events only',
      'Coloured wires are deprecated',
      'They are interchangeable',
    ],
    answer: [0],
    explain: 'Blue is object, green is float, red is bool, magenta is string. The colour is the type.',
  },
  {
    id: 'ue5.bp.3',
    concepts: ['ue5.bpbasics'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each event node to when it fires.',
    pairs: [
      ['Event BeginPlay', 'once, when play starts'],
      ['Event Tick', 'every single frame'],
      ['Event ActorBeginOverlap', 'when something enters a collision volume'],
      ['Event EndPlay', 'when the actor is destroyed or play stops'],
    ],
    explain: 'Tick runs sixty times a second or more. Putting heavy work there is the most common performance mistake.',
  },
  {
    id: 'ue5.bpvar.1',
    concepts: ['ue5.bpvars'],
    difficulty: 3,
    kind: 'wire',
    prompt: 'Wire the Health variable into Print String so it prints the current value.',
    nodes: [
      { id: 'begin', title: 'Event BeginPlay', tone: 'event', x: 20, y: 40, outputs: ['exec'] },
      { id: 'health', title: 'Health', subtitle: 'Float', tone: 'data', x: 20, y: 150, outputs: ['value'] },
      { id: 'print', title: 'Print String', tone: 'action', x: 300, y: 60, inputs: ['exec', 'In String'], outputs: ['exec'] },
    ],
    links: [
      ['begin:exec', 'print:exec'],
      ['health:value', 'print:In String'],
    ],
    explain: 'Dragging a float into a string pin auto-inserts a conversion node. Unreal does that silently and correctly.',
  },
  {
    id: 'ue5.bpvar.2',
    concepts: ['ue5.bpvars'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does the eye icon next to a Blueprint variable do?',
    options: [
      'Makes it public, so it can be set per-instance in the level',
      'Shows it in the viewport',
      'Makes it replicate over the network',
      'Marks it as read-only',
    ],
    answer: [0],
    explain: 'Instance Editable is how one Blueprint gives you a dozen differently-tuned copies in a level.',
  },

  /* ---------------------------------------------------------- ue5.logic */
  {
    id: 'ue5.branch.1',
    concepts: ['ue5.branch'],
    difficulty: 3,
    kind: 'wire',
    prompt: 'Wire a Branch so the door only opens when Is Locked is false.',
    nodes: [
      { id: 'begin', title: 'Event ActorBeginOverlap', tone: 'event', x: 20, y: 30, outputs: ['exec'] },
      { id: 'locked', title: 'Is Locked', subtitle: 'Boolean', tone: 'data', x: 20, y: 150, outputs: ['value'] },
      { id: 'not', title: 'NOT', tone: 'data', x: 200, y: 150, inputs: ['A'], outputs: ['result'] },
      { id: 'branch', title: 'Branch', tone: 'flow', x: 330, y: 40, inputs: ['exec', 'Condition'], outputs: ['True', 'False'] },
      { id: 'open', title: 'Open Door', tone: 'action', x: 500, y: 30, inputs: ['exec'] },
    ],
    links: [
      ['begin:exec', 'branch:exec'],
      ['locked:value', 'not:A'],
      ['not:result', 'branch:Condition'],
      ['branch:True', 'open:exec'],
    ],
    explain: 'Branch is the Blueprint if. NOT inverts the boolean so True means "not locked".',
  },
  {
    id: 'ue5.branch.2',
    concepts: ['ue5.branch'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'Which node is the Blueprint equivalent of an if statement?',
    options: ['Sequence', 'Branch', 'Gate', 'Select'],
    answer: [1],
    explain: 'Select picks a *value* without branching execution — different tool, often the tidier one.',
  },
  {
    id: 'ue5.loop.1',
    concepts: ['ue5.bploops'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each flow-control node to what it does.',
    pairs: [
      ['ForEachLoop', 'runs the body once per array element'],
      ['Sequence', 'runs several outputs in order, top to bottom'],
      ['DoOnce', 'lets execution through a single time'],
      ['Gate', 'opens and closes a path under your control'],
    ],
    explain: 'Sequence is how you keep a graph from turning into one enormous horizontal wire.',
  },
  {
    id: 'ue5.loop.2',
    concepts: ['ue5.bploops'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Where does a ForEachLoop continue after the last element?',
    options: ['The Loop Body pin', 'The Completed pin', 'It stops', 'Back to Loop Body'],
    answer: [1],
    explain: 'Wiring what comes next to Loop Body instead of Completed makes it run once per element by mistake.',
  },
  {
    id: 'ue5.fn.1',
    concepts: ['ue5.bpfunctions'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'When should you turn part of a graph into a Function?',
    options: [
      'When the same wiring appears more than once, or a graph no longer fits on screen',
      'Never, functions are slower',
      'Only for maths',
      'Only in C++',
    ],
    answer: [0],
    explain: 'Collapse to Function keeps the wiring but names it. A named graph is a documented graph.',
  },
  {
    id: 'ue5.fn.2',
    concepts: ['ue5.bpfunctions'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What can a Macro do that a Function cannot?',
    options: [
      'Have multiple execution outputs, and contain latent nodes like Delay',
      'Return a value',
      'Take parameters',
      'Be called from another Blueprint',
    ],
    answer: [0],
    explain: 'Macros are pasted in at compile time; functions are real calls. That is why Delay only works in one of them.',
  },

  /* ------------------------------------------------------- ue5.gameplay */
  {
    id: 'ue5.input.1',
    concepts: ['ue5.input'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What replaced the old Action and Axis Mappings in UE5?',
    options: ['Enhanced Input, with Input Actions and Mapping Contexts', 'Blueprints', 'The Input Component', 'Nothing'],
    answer: [0],
    explain: 'Contexts can be swapped at runtime, so driving a car and walking can use the same keys for different actions.',
  },
  {
    id: 'ue5.input.2',
    concepts: ['ue5.input', 'ue5.framework'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why does input often go to the Player Controller rather than the Pawn?',
    options: [
      'The controller persists when the pawn is destroyed or swapped',
      'Pawns cannot receive input',
      'It is faster',
      'To save memory',
    ],
    answer: [0],
    explain: 'Controller is the player; Pawn is the body they are currently wearing.',
  },
  {
    id: 'ue5.coll.1',
    concepts: ['ue5.collision'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each collision response to what happens.',
    pairs: [
      ['Ignore', 'nothing at all'],
      ['Overlap', 'passes through but fires overlap events'],
      ['Block', 'physically stops the other object'],
    ],
    explain: 'For an Overlap event both actors need Generate Overlap Events ticked. Forgetting that is the usual culprit.',
  },
  {
    id: 'ue5.coll.2',
    concepts: ['ue5.collision'],
    difficulty: 5,
    kind: 'wire',
    prompt: 'Wire a pickup: on overlap, add score and destroy the actor.',
    nodes: [
      { id: 'overlap', title: 'Event ActorBeginOverlap', tone: 'event', x: 20, y: 40, outputs: ['exec'] },
      { id: 'add', title: 'Add Score', subtitle: '+10', tone: 'action', x: 250, y: 40, inputs: ['exec'], outputs: ['exec'] },
      { id: 'destroy', title: 'Destroy Actor', tone: 'action', x: 460, y: 40, inputs: ['exec'] },
    ],
    links: [
      ['overlap:exec', 'add:exec'],
      ['add:exec', 'destroy:exec'],
    ],
    explain: 'Destroy Actor last. Anything wired after it on the same actor may never run.',
  },
  {
    id: 'ue5.spawn.1',
    concepts: ['ue5.spawn'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What does Spawn Actor From Class need that Print String does not?',
    options: [
      'A class to spawn and a transform saying where',
      'A material',
      'A delay',
      'A player controller',
    ],
    answer: [0],
    explain: 'Leave the transform at zero and everything piles up at the world origin — a classic first-hour puzzle.',
  },
  {
    id: 'ue5.fw.1',
    concepts: ['ue5.framework'],
    difficulty: 5,
    kind: 'match',
    prompt: 'Match each framework class to its job.',
    pairs: [
      ['GameMode', 'the rules of the match, server only'],
      ['PlayerController', 'one human player and their input'],
      ['Pawn', 'the body being controlled'],
      ['GameInstance', 'state that survives level changes'],
    ],
    explain: 'Putting the score in the Pawn loses it on death. GameInstance or GameState is where it belongs.',
  },

  /* --------------------------------------------------------- ue5.render */
  {
    id: 'ue5.mat.1',
    concepts: ['ue5.materials'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each material input to what it controls.',
    pairs: [
      ['Base Color', 'the surface colour'],
      ['Metallic', 'whether it behaves like metal'],
      ['Roughness', 'how sharp or blurred reflections are'],
      ['Normal', 'fine surface detail without extra geometry'],
    ],
    explain: 'Physically based rendering: metallic is nearly always 0 or 1, and roughness does most of the work.',
  },
  {
    id: 'ue5.mat.2',
    concepts: ['ue5.materials'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why use a Material Instance instead of editing the Material?',
    options: [
      'Parameters change with no shader recompile, and one master serves many variants',
      'Instances render faster',
      'Materials cannot have textures',
      'It uses less disk space',
    ],
    answer: [0],
    explain: 'Editing a master material recompiles every shader that uses it, which on a big project costs minutes.',
  },
  {
    id: 'ue5.light.1',
    concepts: ['ue5.lighting'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What does Lumen give you?',
    options: [
      'Real-time global illumination and reflections, with no lightmap baking',
      'Higher polygon counts',
      'Faster loading',
      'Better textures',
    ],
    answer: [0],
    explain: 'Move a light and the bounce lighting updates immediately. That used to be an overnight bake.',
  },
  {
    id: 'ue5.perf.1',
    concepts: ['ue5.perf'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'What is Nanite for?',
    options: [
      'Rendering very dense static meshes without hand-authored LODs',
      'Faster physics',
      'Compressing textures',
      'Streaming audio',
    ],
    answer: [0],
    explain: 'It handles opaque static geometry. Skeletal meshes, foliage and translucency still need the old approach.',
  },
  {
    id: 'ue5.perf.2',
    concepts: ['ue5.perf', 'ue5.bpbasics'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'A Blueprint runs a distance check on Event Tick and the frame rate drops. What is the usual fix?',
    options: [
      'Run the check on a timer a few times a second instead of every frame',
      'Move it to Event BeginPlay',
      'Delete the actor',
      'Increase the tick rate',
    ],
    answer: [0],
    explain: 'Almost nothing a player notices needs to happen sixty times a second. Timers and events beat Tick.',
  },
]);
