import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const ue5ExtraSkills: Skill[] = [
  {
    id: 'ue5.ui',
    title: 'UMG and HUDs',
    blurb: 'Widgets, bindings and getting a health bar on the screen.',
    concepts: ['ue5.umg', 'ue5.widgets', 'ue5.hud'],
    requires: ['ue5.logic'],
    level: 'applied',
    tags: ['games'],
    unit: 'Presentation',
  },
  {
    id: 'ue5.data',
    title: 'Data and saving',
    blurb: 'Data tables, structs and keeping progress between runs.',
    concepts: ['ue5.datatables', 'ue5.structs', 'ue5.saving'],
    requires: ['ue5.logic'],
    level: 'advanced',
    tags: ['games'],
    unit: 'Systems',
  },
];

export const ue5Extra = forTrack('ue5', [
  {
    id: 'ue5.vp.x1',
    concepts: ['ue5.viewport'],
    difficulty: 1,
    level: 1,
    kind: 'match',
    prompt: 'Match each viewport control to what it does.',
    pairs: [
      ['Right mouse + WASD', 'Fly the camera'],
      ['F', 'Focus the selected actor'],
      ['G', 'Toggle game view'],
      ['Alt + drag', 'Orbit around the selection'],
    ],
    explain: 'Flying with right mouse held is the one to build muscle memory for first.',
  },
  {
    id: 'ue5.out.x1',
    concepts: ['ue5.outliner'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'What does the Outliner list?',
    options: [
      'Every actor placed in the current level',
      'Every asset in the project',
      'The components of the selected actor',
      'Open Blueprints',
    ],
    answer: [0],
    explain: 'Outliner is the level; Content Browser is the project. Actors versus assets, again.',
  },
  {
    id: 'ue5.as.x1',
    concepts: ['ue5.assets'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What is the difference between an asset and an actor?',
    options: [
      'An asset is a file in the project; an actor is a thing placed in a level',
      'They are the same',
      'Assets only exist at runtime',
      'Actors cannot be saved',
    ],
    answer: [0],
    explain: 'Dragging an asset into the level creates an actor from it. Editing the asset changes them all.',
  },
  {
    id: 'ue5.act.x1',
    concepts: ['ue5.actors'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What must every Actor have?',
    options: ['A transform, via its root component', 'A mesh', 'A collision volume', 'A Blueprint'],
    answer: [0],
    explain: 'No root component means no position. Everything else is optional.',
  },
  {
    id: 'ue5.comp.x1',
    concepts: ['ue5.components'],
    difficulty: 2,
    level: 3,
    kind: 'match',
    prompt: 'Match each component to what it adds.',
    pairs: [
      ['StaticMeshComponent', 'Something to look at'],
      ['BoxComponent', 'A shape to overlap or block'],
      ['SpringArmComponent', 'A camera boom that avoids walls'],
      ['AudioComponent', 'A sound source'],
    ],
    explain: 'A spring arm plus a camera is the third-person setup, and it is two components, not a class.',
  },
  {
    id: 'ue5.tr.x1',
    concepts: ['ue5.transform'],
    difficulty: 2,
    level: 3,
    kind: 'choice',
    prompt: 'Which is Unreal’s up axis, and what unit is one grid square?',
    options: ['Z is up, and one unit is a centimetre', 'Y is up, metres', 'Z is up, metres', 'Y is up, centimetres'],
    answer: [0],
    explain: 'Z-up and centimetres. Importing from a Y-up, metres tool is why models arrive tiny and on their side.',
  },
  {
    id: 'ue5.bp.x1',
    concepts: ['ue5.bpbasics'],
    difficulty: 2,
    level: 3,
    kind: 'choice',
    prompt: 'What is a Blueprint?',
    options: [
      'A visual script that is also a class you can place in the world',
      'A material',
      'A level',
      'A packaging setting',
    ],
    answer: [0],
    explain: 'Blueprint classes inherit, hold variables and can be extended in C++ later.',
  },
  {
    id: 'ue5.exec.x1',
    concepts: ['ue5.exec'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'What do the white pins and wires carry?',
    options: [
      'Execution order — which node runs next',
      'Numbers',
      'References to actors',
      'Nothing; they are decoration',
    ],
    answer: [0],
    explain: 'Coloured pins are data. The white line is the program counter, drawn out where you can see it.',
  },
  {
    id: 'ue5.exec.x2',
    concepts: ['ue5.exec', 'ue5.bpbasics'],
    difficulty: 3,
    level: 4,
    kind: 'wire',
    prompt: 'Print a message when the game starts.',
    nodes: [
      { id: 'begin', title: 'Event BeginPlay', x: 20, y: 40, outputs: ['exec'], tone: 'event' },
      { id: 'print', title: 'Print String', subtitle: 'In String: "Ready"', x: 250, y: 40, inputs: ['exec'], outputs: ['exec'], tone: 'action' },
    ],
    links: [['begin:exec', 'print:exec']],
    explain: 'BeginPlay fires once when play starts. Print String is the fastest debugging tool in the engine.',
  },
  {
    id: 'ue5.var.x1',
    concepts: ['ue5.bpvars'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'What does the eye icon next to a Blueprint variable do?',
    options: [
      'Makes it public, so it can be set per-instance in the Details panel',
      'Shows it in the viewport',
      'Marks it for replication',
      'Makes it constant',
    ],
    answer: [0],
    explain: 'Instance-editable variables are how one Blueprint becomes ten different placed actors.',
  },

  /* ------------------------------------------------------------- ue5.ui */
  {
    id: 'ue5.ui.1',
    concepts: ['ue5.umg'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'What is UMG?',
    options: [
      'Unreal’s UI system — widget Blueprints laid out in a designer',
      'A material editor',
      'The animation system',
      'A packaging tool',
    ],
    answer: [0],
    explain: 'A Widget Blueprint has a Designer tab and a Graph tab: layout on one, logic on the other.',
  },
  {
    id: 'ue5.ui.2',
    concepts: ['ue5.widgets'],
    difficulty: 4,
    level: 6,
    kind: 'match',
    prompt: 'Match each widget to its job.',
    pairs: [
      ['Canvas Panel', 'Free positioning with anchors'],
      ['Vertical Box', 'Stack children top to bottom'],
      ['Size Box', 'Force a fixed size'],
      ['Progress Bar', 'A health or loading bar'],
    ],
    explain: 'Canvas Panels are flexible and slow to reason about. Boxes are usually the better default.',
  },
  {
    id: 'ue5.ui.3',
    concepts: ['ue5.hud'],
    difficulty: 4,
    level: 6,
    kind: 'order',
    prompt: 'Put a HUD on screen from the player controller.',
    lines: ['Event BeginPlay', 'Create Widget (Class: WBP_HUD)', 'Promote return value to variable', 'Add to Viewport'],
    explain: 'Create Widget makes it; Add to Viewport shows it. Forgetting the second is a classic five minutes lost.',
  },
  {
    id: 'ue5.ui.4',
    concepts: ['ue5.widgets'],
    difficulty: 5,
    level: 7,
    kind: 'choice',
    prompt: 'Why prefer an event-driven update over a binding on a health bar?',
    options: [
      'Bindings are evaluated every frame, whether or not the value changed',
      'Bindings cannot read variables',
      'Events are easier to type',
      'Bindings do not work in packaged builds',
    ],
    answer: [0],
    explain: 'A dozen bindings is a dozen function calls per frame, forever. Push the change instead.',
  },

  /* ----------------------------------------------------------- ue5.data */
  {
    id: 'ue5.data.1',
    concepts: ['ue5.datatables'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What is a Data Table for?',
    options: [
      'Rows of a struct you can edit as a spreadsheet and look up by name',
      'Storing save games',
      'Replicating variables',
      'Baking lighting',
    ],
    answer: [0],
    explain: 'Weapon stats, dialogue lines, item costs — all the tuning you do not want hard-coded in Blueprints.',
  },
  {
    id: 'ue5.data.2',
    concepts: ['ue5.structs'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'When should you make a Blueprint struct?',
    options: [
      'When several values always travel together — damage, type and source, say',
      'Whenever you have two variables',
      'Only for replication',
      'Never; use separate variables',
    ],
    answer: [0],
    explain: 'One pin instead of five keeps graphs readable, and adding a field later changes one place.',
  },
  {
    id: 'ue5.data.3',
    concepts: ['ue5.saving'],
    difficulty: 5,
    level: 7,
    kind: 'order',
    prompt: 'Save the player’s progress.',
    lines: [
      'Create Save Game Object (Class: SG_Progress)',
      'Set its variables from the current state',
      'Save Game to Slot (Slot: "player", User: 0)',
      'Later: Does Save Game Exist -> Load Game from Slot',
    ],
    explain: 'A SaveGame object is just a UObject with variables. The slot name is the file name.',
  },
  {
    id: 'ue5.data.4',
    concepts: ['ue5.saving', 'ue5.perf'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'Why should saving not happen every frame?',
    options: [
      'It writes to disk, which stalls the game thread',
      'Save files can only be written once',
      'The engine forbids it',
      'It corrupts the slot',
    ],
    answer: [0],
    explain: 'Save at checkpoints, or asynchronously. A hitch every frame is worse than losing a minute of progress.',
  },
]);
