import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const ue5ExtraSkills: Skill[] = [
  {
    id: 'ue5.bpgraph',
    title: 'Reading a Blueprint',
    blurb: 'Pin colours, get and set, and which nodes need an execution wire at all.',
    concepts: ['ue5.pintypes', 'ue5.getset', 'ue5.purefn'],
    requires: ['ue5.blueprints'],
    level: 'core',
    tags: ['games'],
    unit: 'Blueprints',
  },
  {
    id: 'ue5.bpbuild',
    title: 'Building Blueprints',
    blurb: 'Casting, loops, delays and timelines — the graphs a real actor is made of.',
    concepts: ['ue5.cast', 'ue5.macros', 'ue5.timeline', 'ue5.delay'],
    requires: ['ue5.logic', 'ue5.bpgraph'],
    level: 'applied',
    tags: ['games'],
    unit: 'Blueprints',
  },
  {
    id: 'ue5.ui',
    title: 'UMG and HUDs',
    blurb: 'Widgets, bindings and getting a health bar on the screen.',
    concepts: ['ue5.umg', 'ue5.widgets', 'ue5.hud'],
    requires: ['ue5.logic'],
    level: 'applied',
    tags: ['games'],
    unit: 'Presentation',
  },
  {
    id: 'ue5.data',
    title: 'Data and saving',
    blurb: 'Data tables, structs and keeping progress between runs.',
    concepts: ['ue5.datatables', 'ue5.structs', 'ue5.saving'],
    requires: ['ue5.logic'],
    level: 'advanced',
    tags: ['games'],
    unit: 'Systems',
  },
];

export const ue5Extra = forTrack('ue5', [
  /* ================================================== reading a Blueprint */
  {
    id: 'ue5.pin.1',
    concepts: ['ue5.pintypes'],
    difficulty: 2,
    level: 3,
    kind: 'match',
    prompt: 'Match each Blueprint pin colour to what it carries.',
    pairs: [
      ['White arrow', 'Execution — the order things happen in'],
      ['Red', 'A boolean'],
      ['Green', 'A float'],
      ['Blue', 'An object reference'],
    ],
    explain: 'Pin colour is type. Once you read the colours, a graph you have never seen is still legible.',
  },
  {
    id: 'ue5.pin.2',
    concepts: ['ue5.pintypes'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'Why will the editor not let you drag an execution pin onto a float pin?',
    options: [
      'They are different kinds of thing: one is when, the other is what',
      'It would be slow',
      'Only Blueprints in C++ can do that',
      'It would work, but it is bad style',
    ],
    answer: [0],
    explain: 'Execution wires say "then do this". Data wires say "here is a value". Nothing converts between them.',
  },
  {
    id: 'ue5.pin.3',
    concepts: ['ue5.pintypes'],
    difficulty: 3,
    level: 4,
    kind: 'wire',
    prompt: 'Print the player’s Health. Join the execution first, then the value.',
    nodes: [
      { id: 'begin', title: 'Event BeginPlay', tone: 'event', x: 20, y: 40, outputs: [{ name: 'exec', type: 'exec' }] },
      { id: 'health', title: 'Health', subtitle: 'Float · variable', tone: 'data', x: 20, y: 160, outputs: [{ name: 'value', type: 'float' }] },
      {
        id: 'print',
        title: 'Print String',
        tone: 'action',
        x: 300,
        y: 40,
        inputs: [{ name: 'exec', type: 'exec' }, { name: 'In String', type: 'string' }],
        outputs: [{ name: 'exec', type: 'exec' }],
      },
    ],
    links: [
      ['begin:exec', 'print:exec'],
      ['health:value', 'print:In String'],
    ],
    explain: 'Dropping a float on a string pin makes Unreal insert a conversion node for you, silently and correctly.',
  },
  {
    id: 'ue5.getset.1',
    concepts: ['ue5.getset'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'What is the difference between a Get and a Set node for the same variable?',
    options: [
      'Get is pure and has no execution pins; Set changes the value and must be wired into the flow',
      'Get is faster',
      'Set only works on integers',
      'There is none; they are the same node',
    ],
    answer: [0],
    explain: 'If a node changes state it needs a place in the execution order. That is why Set has the white pins.',
  },
  {
    id: 'ue5.getset.2',
    concepts: ['ue5.getset', 'ue5.pintypes'],
    difficulty: 4,
    level: 5,
    kind: 'wire',
    prompt: 'Take Damage away from Health and store the result back in Health.',
    nodes: [
      { id: 'event', title: 'Event AnyDamage', tone: 'event', x: 10, y: 20, outputs: [{ name: 'exec', type: 'exec' }, { name: 'Damage', type: 'float' }] },
      { id: 'health', title: 'Get Health', subtitle: 'Float', tone: 'data', x: 10, y: 150, outputs: [{ name: 'value', type: 'float' }] },
      {
        id: 'sub',
        title: 'Subtract',
        subtitle: 'float - float',
        tone: 'data',
        x: 230,
        y: 130,
        inputs: [{ name: 'A', type: 'float' }, { name: 'B', type: 'float' }],
        outputs: [{ name: 'Result', type: 'float' }],
      },
      {
        id: 'set',
        title: 'Set Health',
        tone: 'action',
        x: 450,
        y: 30,
        inputs: [{ name: 'exec', type: 'exec' }, { name: 'Value', type: 'float' }],
        outputs: [{ name: 'exec', type: 'exec' }],
      },
    ],
    links: [
      ['event:exec', 'set:exec'],
      ['health:value', 'sub:A'],
      ['event:Damage', 'sub:B'],
      ['sub:Result', 'set:Value'],
    ],
    explain: 'Data flows right into the node that needs it; execution flows along the top. Every real graph is those two layers.',
  },
  {
    id: 'ue5.pure.1',
    concepts: ['ue5.purefn'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'A pure function has no execution pins. When does it run?',
    options: [
      'Every time something asks for its output — once per consumer, not once per graph',
      'Once when the game starts',
      'Only when wired into the execution chain',
      'Never; it is documentation',
    ],
    answer: [0],
    explain: 'Two nodes reading the same pure node call it twice. For anything expensive, cache it into a variable first.',
  },
  {
    id: 'ue5.pure.2',
    concepts: ['ue5.purefn'],
    difficulty: 4,
    level: 6,
    kind: 'wire',
    prompt: 'Print how far the actor is from the origin, using the pure nodes provided.',
    nodes: [
      { id: 'begin', title: 'Event BeginPlay', tone: 'event', x: 10, y: 30, outputs: [{ name: 'exec', type: 'exec' }] },
      { id: 'loc', title: 'Get Actor Location', subtitle: 'pure', tone: 'data', x: 10, y: 150, outputs: [{ name: 'Return', type: 'vector' }] },
      {
        id: 'len',
        title: 'Vector Length',
        subtitle: 'pure',
        tone: 'data',
        x: 240,
        y: 150,
        inputs: [{ name: 'A', type: 'vector' }],
        outputs: [{ name: 'Return', type: 'float' }],
      },
      {
        id: 'print',
        title: 'Print String',
        tone: 'action',
        x: 460,
        y: 30,
        inputs: [{ name: 'exec', type: 'exec' }, { name: 'In String', type: 'string' }],
      },
    ],
    links: [
      ['begin:exec', 'print:exec'],
      ['loc:Return', 'len:A'],
      ['len:Return', 'print:In String'],
    ],
    explain: 'Pure nodes chain freely and never join the white line. Only Print String needed telling when to happen.',
  },
  {
    id: 'ue5.getset.3',
    concepts: ['ue5.getset'],
    difficulty: 4,
    level: 6,
    kind: 'bug',
    prompt: 'Health never changes in play. Which line of this description is the mistake?',
    code: 'Event AnyDamage -> Print String\nGet Health -> Subtract -> (nothing)\nSet Health is on the graph\nSet Health has no execution wire',
    buggyLine: 4,
    why: {
      options: [
        'A Set node with no execution wire is never run',
        'Get Health should be a Set',
        'Print String breaks the chain',
        'Subtract needs an execution pin',
      ],
      answer: 0,
    },
    explain: 'An unwired impure node sits there looking correct and does nothing. Follow the white line to find out what actually happens.',
  },

  /* ================================================= building Blueprints */
  {
    id: 'ue5.cast.1',
    concepts: ['ue5.cast'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What does Cast To BP_Player do?',
    options: [
      'Asks whether this actor is a BP_Player, and gives you it as that type if so',
      'Converts any actor into a player',
      'Spawns a player',
      'Changes the actor’s class permanently',
    ],
    answer: [0],
    explain: 'It is a question with two answers, which is why it has two execution outputs.',
  },
  {
    id: 'ue5.cast.2',
    concepts: ['ue5.cast'],
    difficulty: 4,
    level: 6,
    kind: 'wire',
    prompt: 'On overlap, check whether the other actor is the player before opening the door.',
    nodes: [
      {
        id: 'overlap',
        title: 'Event ActorBeginOverlap',
        tone: 'event',
        x: 10,
        y: 20,
        outputs: [{ name: 'exec', type: 'exec' }, { name: 'Other Actor', type: 'object' }],
      },
      {
        id: 'cast',
        title: 'Cast To BP_Player',
        tone: 'flow',
        x: 250,
        y: 20,
        inputs: [{ name: 'exec', type: 'exec' }, { name: 'Object', type: 'object' }],
        outputs: [{ name: 'exec', type: 'exec' }, { name: 'Cast Failed', type: 'exec' }],
      },
      { id: 'open', title: 'Open Door', tone: 'action', x: 500, y: 20, inputs: [{ name: 'exec', type: 'exec' }] },
    ],
    links: [
      ['overlap:exec', 'cast:exec'],
      ['overlap:Other Actor', 'cast:Object'],
      ['cast:exec', 'open:exec'],
    ],
    explain: 'The top output is the success pin. Leaving Cast Failed unwired is fine — nothing happens on a miss.',
  },
  {
    id: 'ue5.macro.1',
    concepts: ['ue5.macros'],
    difficulty: 4,
    level: 7,
    kind: 'wire',
    prompt: 'Print every actor in the array using ForEachLoop.',
    nodes: [
      { id: 'begin', title: 'Event BeginPlay', tone: 'event', x: 10, y: 20, outputs: [{ name: 'exec', type: 'exec' }] },
      { id: 'actors', title: 'Get Enemies', subtitle: 'Array of Actor', tone: 'data', x: 10, y: 150, outputs: [{ name: 'Array', type: 'object' }] },
      {
        id: 'loop',
        title: 'ForEachLoop',
        tone: 'flow',
        x: 240,
        y: 20,
        inputs: [{ name: 'exec', type: 'exec' }, { name: 'Array', type: 'object' }],
        outputs: [{ name: 'Loop Body', type: 'exec' }, { name: 'Array Element', type: 'object' }, { name: 'Completed', type: 'exec' }],
      },
      {
        id: 'print',
        title: 'Print String',
        tone: 'action',
        x: 500,
        y: 20,
        inputs: [{ name: 'exec', type: 'exec' }, { name: 'In String', type: 'object' }],
      },
    ],
    links: [
      ['begin:exec', 'loop:exec'],
      ['actors:Array', 'loop:Array'],
      ['loop:Loop Body', 'print:exec'],
      ['loop:Array Element', 'print:In String'],
    ],
    explain: 'Loop Body fires once per element with that element on the data pin; Completed fires once, at the end.',
  },
  {
    id: 'ue5.macro.2',
    concepts: ['ue5.macros'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What is the practical difference between a Blueprint macro and a function?',
    options: [
      'A macro is pasted into the graph and can have several execution outputs; a function is a real call and cannot',
      'A macro is faster',
      'A function cannot take inputs',
      'They are the same, with a different icon',
    ],
    answer: [0],
    explain: 'That is why ForEachLoop, with its Loop Body and Completed pins, has to be a macro.',
  },
  {
    id: 'ue5.delay.1',
    concepts: ['ue5.delay'],
    difficulty: 3,
    level: 6,
    kind: 'wire',
    prompt: 'Wait two seconds after the overlap before opening the door.',
    nodes: [
      { id: 'overlap', title: 'Event ActorBeginOverlap', tone: 'event', x: 10, y: 30, outputs: [{ name: 'exec', type: 'exec' }] },
      { id: 'time', title: '2.0', subtitle: 'Float', tone: 'data', x: 10, y: 150, outputs: [{ name: 'value', type: 'float' }] },
      {
        id: 'delay',
        title: 'Delay',
        tone: 'flow',
        x: 250,
        y: 30,
        inputs: [{ name: 'exec', type: 'exec' }, { name: 'Duration', type: 'float' }],
        outputs: [{ name: 'exec', type: 'exec' }],
      },
      { id: 'open', title: 'Open Door', tone: 'action', x: 480, y: 30, inputs: [{ name: 'exec', type: 'exec' }] },
    ],
    links: [
      ['overlap:exec', 'delay:exec'],
      ['time:value', 'delay:Duration'],
      ['delay:exec', 'open:exec'],
    ],
    explain: 'Delay is latent: the graph pauses and resumes later. Retriggering it while it is waiting does nothing.',
  },
  {
    id: 'ue5.delay.2',
    concepts: ['ue5.delay'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'Why can a Delay node not be used inside a function?',
    options: [
      'Functions must finish in one frame; latent nodes need to resume later',
      'Delay is deprecated',
      'Functions cannot have execution pins',
      'It works, but the delay is ignored',
    ],
    answer: [0],
    explain: 'Put it in an event, a custom event or a macro in an event graph — that is what those are for.',
  },
  {
    id: 'ue5.timeline.1',
    concepts: ['ue5.timeline'],
    difficulty: 5,
    level: 8,
    kind: 'wire',
    prompt: 'Drive the light’s brightness from a Timeline’s Alpha track.',
    nodes: [
      { id: 'event', title: 'Event Turn On', tone: 'event', x: 10, y: 20, outputs: [{ name: 'exec', type: 'exec' }] },
      {
        id: 'tl',
        title: 'Timeline · Fade',
        tone: 'flow',
        x: 230,
        y: 20,
        inputs: [{ name: 'Play', type: 'exec' }],
        outputs: [{ name: 'Update', type: 'exec' }, { name: 'Alpha', type: 'float' }, { name: 'Finished', type: 'exec' }],
      },
      {
        id: 'set',
        title: 'Set Intensity',
        tone: 'action',
        x: 500,
        y: 20,
        inputs: [{ name: 'exec', type: 'exec' }, { name: 'Value', type: 'float' }],
      },
    ],
    links: [
      ['event:exec', 'tl:Play'],
      ['tl:Update', 'set:exec'],
      ['tl:Alpha', 'set:Value'],
    ],
    explain: 'Update fires every frame while the timeline plays, with the curve’s current value on Alpha. That is the whole pattern for smooth movement.',
  },
  {
    id: 'ue5.timeline.2',
    concepts: ['ue5.timeline'],
    difficulty: 5,
    level: 9,
    kind: 'choice',
    prompt: 'Why prefer a Timeline over doing the same interpolation on Tick?',
    options: [
      'It is authored as a curve, it starts and stops itself, and it costs nothing when it is not playing',
      'It runs on a background thread',
      'Tick cannot change values',
      'Timelines are replicated automatically',
    ],
    answer: [0],
    explain: 'A Tick that runs all game long to animate a two-second door is the classic Blueprint performance leak.',
  },
  {
    id: 'ue5.bpflow.1',
    concepts: ['ue5.macros', 'ue5.exec'],
    difficulty: 4,
    level: 7,
    kind: 'wire',
    prompt: 'Do two things in a known order from one event, using Sequence.',
    nodes: [
      { id: 'event', title: 'Event BeginPlay', tone: 'event', x: 10, y: 40, outputs: [{ name: 'exec', type: 'exec' }] },
      {
        id: 'seq',
        title: 'Sequence',
        tone: 'flow',
        x: 220,
        y: 40,
        inputs: [{ name: 'exec', type: 'exec' }],
        outputs: [{ name: 'Then 0', type: 'exec' }, { name: 'Then 1', type: 'exec' }],
      },
      { id: 'setup', title: 'Set Up UI', tone: 'action', x: 450, y: 10, inputs: [{ name: 'exec', type: 'exec' }] },
      { id: 'spawn', title: 'Spawn Enemies', tone: 'action', x: 450, y: 120, inputs: [{ name: 'exec', type: 'exec' }] },
    ],
    links: [
      ['event:exec', 'seq:exec'],
      ['seq:Then 0', 'setup:exec'],
      ['seq:Then 1', 'spawn:exec'],
    ],
    explain: 'Sequence runs each output to completion in order — not in parallel. It is the tidy alternative to a chain of nodes wandering off the screen.',
  },
  {
    id: 'ue5.bpflow.2',
    concepts: ['ue5.exec'],
    difficulty: 4,
    level: 7,
    kind: 'order',
    prompt: 'Put this graph in the order it executes.',
    lines: [
      'Event BeginPlay',
      'Branch (Condition: Is Day)',
      'True: Set Light Intensity 0',
      'False: Set Light Intensity 5000',
    ],
    explain: 'Branch is an if: one input, two execution outputs, and only one of them ever fires per call.',
  },
  {
    id: 'ue5.vp.x1',
    concepts: ['ue5.viewport'],
    difficulty: 1,
    level: 1,
    kind: 'match',
    prompt: 'Match each viewport control to what it does.',
    pairs: [
      ['Right mouse + WASD', 'Fly the camera'],
      ['F', 'Focus the selected actor'],
      ['G', 'Toggle game view'],
      ['Alt + drag', 'Orbit around the selection'],
    ],
    explain: 'Flying with right mouse held is the one to build muscle memory for first.',
  },
  {
    id: 'ue5.out.x1',
    concepts: ['ue5.outliner'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'What does the Outliner list?',
    options: [
      'Every actor placed in the current level',
      'Every asset in the project',
      'The components of the selected actor',
      'Open Blueprints',
    ],
    answer: [0],
    explain: 'Outliner is the level; Content Browser is the project. Actors versus assets, again.',
  },
  {
    id: 'ue5.as.x1',
    concepts: ['ue5.assets'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What is the difference between an asset and an actor?',
    options: [
      'An asset is a file in the project; an actor is a thing placed in a level',
      'They are the same',
      'Assets only exist at runtime',
      'Actors cannot be saved',
    ],
    answer: [0],
    explain: 'Dragging an asset into the level creates an actor from it. Editing the asset changes them all.',
  },
  {
    id: 'ue5.act.x1',
    concepts: ['ue5.actors'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What must every Actor have?',
    options: ['A transform, via its root component', 'A mesh', 'A collision volume', 'A Blueprint'],
    answer: [0],
    explain: 'No root component means no position. Everything else is optional.',
  },
  {
    id: 'ue5.comp.x1',
    concepts: ['ue5.components'],
    difficulty: 2,
    level: 3,
    kind: 'match',
    prompt: 'Match each component to what it adds.',
    pairs: [
      ['StaticMeshComponent', 'Something to look at'],
      ['BoxComponent', 'A shape to overlap or block'],
      ['SpringArmComponent', 'A camera boom that avoids walls'],
      ['AudioComponent', 'A sound source'],
    ],
    explain: 'A spring arm plus a camera is the third-person setup, and it is two components, not a class.',
  },
  {
    id: 'ue5.tr.x1',
    concepts: ['ue5.transform'],
    difficulty: 2,
    level: 3,
    kind: 'choice',
    prompt: 'Which is Unreal’s up axis, and what unit is one grid square?',
    options: ['Z is up, and one unit is a centimetre', 'Y is up, metres', 'Z is up, metres', 'Y is up, centimetres'],
    answer: [0],
    explain: 'Z-up and centimetres. Importing from a Y-up, metres tool is why models arrive tiny and on their side.',
  },
  {
    id: 'ue5.bp.x1',
    concepts: ['ue5.bpbasics'],
    difficulty: 2,
    level: 3,
    kind: 'choice',
    prompt: 'What is a Blueprint?',
    options: [
      'A visual script that is also a class you can place in the world',
      'A material',
      'A level',
      'A packaging setting',
    ],
    answer: [0],
    explain: 'Blueprint classes inherit, hold variables and can be extended in C++ later.',
  },
  {
    id: 'ue5.exec.x1',
    concepts: ['ue5.exec'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'What do the white pins and wires carry?',
    options: [
      'Execution order — which node runs next',
      'Numbers',
      'References to actors',
      'Nothing; they are decoration',
    ],
    answer: [0],
    explain: 'Coloured pins are data. The white line is the program counter, drawn out where you can see it.',
  },
  {
    id: 'ue5.exec.x2',
    concepts: ['ue5.exec', 'ue5.bpbasics'],
    difficulty: 3,
    level: 4,
    kind: 'wire',
    prompt: 'Print a message when the game starts.',
    nodes: [
      { id: 'begin', title: 'Event BeginPlay', x: 20, y: 40, outputs: ['exec'], tone: 'event' },
      { id: 'print', title: 'Print String', subtitle: 'In String: "Ready"', x: 250, y: 40, inputs: ['exec'], outputs: ['exec'], tone: 'action' },
    ],
    links: [['begin:exec', 'print:exec']],
    explain: 'BeginPlay fires once when play starts. Print String is the fastest debugging tool in the engine.',
  },
  {
    id: 'ue5.var.x1',
    concepts: ['ue5.bpvars'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'What does the eye icon next to a Blueprint variable do?',
    options: [
      'Makes it public, so it can be set per-instance in the Details panel',
      'Shows it in the viewport',
      'Marks it for replication',
      'Makes it constant',
    ],
    answer: [0],
    explain: 'Instance-editable variables are how one Blueprint becomes ten different placed actors.',
  },

  /* ------------------------------------------------------------- ue5.ui */
  {
    id: 'ue5.ui.1',
    concepts: ['ue5.umg'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'What is UMG?',
    options: [
      'Unreal’s UI system — widget Blueprints laid out in a designer',
      'A material editor',
      'The animation system',
      'A packaging tool',
    ],
    answer: [0],
    explain: 'A Widget Blueprint has a Designer tab and a Graph tab: layout on one, logic on the other.',
  },
  {
    id: 'ue5.ui.2',
    concepts: ['ue5.widgets'],
    difficulty: 4,
    level: 6,
    kind: 'match',
    prompt: 'Match each widget to its job.',
    pairs: [
      ['Canvas Panel', 'Free positioning with anchors'],
      ['Vertical Box', 'Stack children top to bottom'],
      ['Size Box', 'Force a fixed size'],
      ['Progress Bar', 'A health or loading bar'],
    ],
    explain: 'Canvas Panels are flexible and slow to reason about. Boxes are usually the better default.',
  },
  {
    id: 'ue5.ui.3',
    concepts: ['ue5.hud'],
    difficulty: 4,
    level: 6,
    kind: 'order',
    prompt: 'Put a HUD on screen from the player controller.',
    lines: ['Event BeginPlay', 'Create Widget (Class: WBP_HUD)', 'Promote return value to variable', 'Add to Viewport'],
    explain: 'Create Widget makes it; Add to Viewport shows it. Forgetting the second is a classic five minutes lost.',
  },
  {
    id: 'ue5.ui.4',
    concepts: ['ue5.widgets'],
    difficulty: 5,
    level: 7,
    kind: 'choice',
    prompt: 'Why prefer an event-driven update over a binding on a health bar?',
    options: [
      'Bindings are evaluated every frame, whether or not the value changed',
      'Bindings cannot read variables',
      'Events are easier to type',
      'Bindings do not work in packaged builds',
    ],
    answer: [0],
    explain: 'A dozen bindings is a dozen function calls per frame, forever. Push the change instead.',
  },

  /* ----------------------------------------------------------- ue5.data */
  {
    id: 'ue5.data.1',
    concepts: ['ue5.datatables'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'What is a Data Table for?',
    options: [
      'Rows of a struct you can edit as a spreadsheet and look up by name',
      'Storing save games',
      'Replicating variables',
      'Baking lighting',
    ],
    answer: [0],
    explain: 'Weapon stats, dialogue lines, item costs — all the tuning you do not want hard-coded in Blueprints.',
  },
  {
    id: 'ue5.data.2',
    concepts: ['ue5.structs'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'When should you make a Blueprint struct?',
    options: [
      'When several values always travel together — damage, type and source, say',
      'Whenever you have two variables',
      'Only for replication',
      'Never; use separate variables',
    ],
    answer: [0],
    explain: 'One pin instead of five keeps graphs readable, and adding a field later changes one place.',
  },
  {
    id: 'ue5.data.3',
    concepts: ['ue5.saving'],
    difficulty: 5,
    level: 7,
    kind: 'order',
    prompt: 'Save the player’s progress.',
    lines: [
      'Create Save Game Object (Class: SG_Progress)',
      'Set its variables from the current state',
      'Save Game to Slot (Slot: "player", User: 0)',
      'Later: Does Save Game Exist -> Load Game from Slot',
    ],
    explain: 'A SaveGame object is just a UObject with variables. The slot name is the file name.',
  },
  {
    id: 'ue5.data.4',
    concepts: ['ue5.saving', 'ue5.perf'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'Why should saving not happen every frame?',
    options: [
      'It writes to disk, which stalls the game thread',
      'Save files can only be written once',
      'The engine forbids it',
      'It corrupts the slot',
    ],
    answer: [0],
    explain: 'Save at checkpoints, or asynchronously. A hitch every frame is worse than losing a minute of progress.',
  },
]);
