import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const unityExtraSkills: Skill[] = [
  {
    id: 'un.ui',
    title: 'UI and events',
    blurb: 'Canvases, anchors and buttons that call your code.',
    concepts: ['un.canvas', 'un.anchors', 'un.uievents'],
    requires: ['un.scripting'],
    level: 'applied',
    tags: ['games'],
    unit: 'Presentation',
  },
  {
    id: 'un.look',
    title: 'Materials, animation and audio',
    blurb: 'Making it look and sound like a game rather than a physics demo.',
    concepts: ['un.materials', 'un.animator', 'un.audio'],
    requires: ['un.objects'],
    level: 'applied',
    tags: ['games', 'graphics'],
    unit: 'Presentation',
  },
];

export const unityExtra = forTrack('unity', [
  {
    id: 'un.scene.x1',
    concepts: ['un.scene'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'What is a Scene?',
    options: [
      'A saved arrangement of GameObjects — a level, a menu, a loading screen',
      'A single 3D model',
      'A script attached to the camera',
      'A build target',
    ],
    answer: [0],
    explain: 'Menus, levels and loading screens are all Scenes. You can even load several at once.',
  },
  {
    id: 'un.scene.x2',
    concepts: ['un.scene'],
    difficulty: 2,
    level: 2,
    kind: 'match',
    prompt: 'Match each editor window to what it shows.',
    pairs: [
      ['Hierarchy', 'Everything in the open Scene'],
      ['Inspector', 'The selected object’s components'],
      ['Project', 'The files on disk'],
      ['Console', 'Logs, warnings and errors'],
    ],
    explain: 'Hierarchy is the Scene right now; Project is what is saved. Confusing them costs an afternoon.',
  },
  {
    id: 'un.hier.x1',
    concepts: ['un.hierarchy'],
    difficulty: 2,
    level: 2,
    kind: 'predict',
    prompt: 'A parent object is moved 5 units right. What happens to its child?',
    code: 'Parent (0,0,0) -> moved to (5,0,0)\n  Child localPosition (0,1,0)',
    options: ['It ends up at world (5,1,0)', 'It stays at (0,1,0)', 'It moves to (5,0,0)', 'It is unparented'],
    answer: 0,
    explain: 'Children keep their local offset. Parenting is the cheapest way to move a group together.',
  },
  {
    id: 'un.prefab.x1',
    concepts: ['un.prefab'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'Why use a Prefab rather than copying an object?',
    options: [
      'Edit the Prefab once and every instance in every Scene updates',
      'Prefabs render faster',
      'Copies cannot have scripts',
      'Prefabs are required for physics',
    ],
    answer: [0],
    explain: 'A Prefab is the definition; the things in your Scene are instances of it.',
  },
  {
    id: 'un.go.x1',
    concepts: ['un.gameobject'],
    difficulty: 2,
    level: 2,
    kind: 'choice',
    prompt: 'What does a GameObject do on its own?',
    options: [
      'Nothing — it is a container; the Components give it behaviour',
      'Renders a mesh',
      'Runs physics',
      'Plays audio',
    ],
    answer: [0],
    explain: 'Every GameObject has a Transform and nothing else by default. Everything you see is a Component.',
  },
  {
    id: 'un.comp.x1',
    concepts: ['un.components'],
    difficulty: 2,
    level: 3,
    kind: 'match',
    prompt: 'Match each component to what it provides.',
    pairs: [
      ['Rigidbody', 'Physics simulation'],
      ['Collider', 'A shape physics can hit'],
      ['MeshRenderer', 'Drawing the mesh'],
      ['AudioSource', 'Playing a sound'],
    ],
    explain: 'Composition rather than inheritance: an object is whatever components you bolt to it.',
  },
  {
    id: 'un.tr.x1',
    concepts: ['un.transform'],
    difficulty: 2,
    level: 3,
    kind: 'blank',
    prompt: 'Move this object up by one unit every frame, framerate independent.',
    template: 'transform.{{0}}(Vector3.up * speed * Time.{{1}});',
    blanks: [{ accept: ['Translate'], width: 10 }, { accept: ['deltaTime'], width: 10 }],
    explain: 'Without deltaTime the speed depends on the framerate, and the game plays differently on every machine.',
  },
  {
    id: 'un.tr.x2',
    concepts: ['un.transform'],
    difficulty: 3,
    level: 4,
    kind: 'bug',
    prompt: 'The object jitters when it collides. Which line is the cause?',
    code: 'void Update()\n{\n    transform.position += velocity * Time.deltaTime;\n}',
    buggyLine: 3,
    why: {
      options: [
        'Moving the Transform directly bypasses physics; a Rigidbody should be moved with MovePosition in FixedUpdate',
        'Update runs too rarely',
        'velocity must be a Vector2',
        'position is read-only',
      ],
      answer: 0,
    },
    explain: 'Teleporting a physics body every frame fights the solver. That fight is what you see as jitter.',
  },
  {
    id: 'un.life.x1',
    concepts: ['un.lifecycle'],
    difficulty: 3,
    level: 4,
    kind: 'order',
    prompt: 'Put these MonoBehaviour callbacks in the order Unity calls them.',
    lines: ['Awake()', 'OnEnable()', 'Start()', 'Update()', 'LateUpdate()'],
    explain: 'Awake is for wiring up yourself, Start for reaching out to others — by then everything exists.',
  },
  {
    id: 'un.get.x1',
    concepts: ['un.getcomponent'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'Where should GetComponent go?',
    options: [
      'In Awake or Start, cached in a field',
      'In Update, every frame',
      'In OnGUI',
      'It does not matter',
    ],
    answer: [0],
    explain: 'GetComponent is a search. Doing it 60 times a second for something that never changes is pure waste.',
  },

  /* ---------------------------------------------------------------- un.ui */
  {
    id: 'un.ui.1',
    concepts: ['un.canvas'],
    difficulty: 3,
    level: 5,
    kind: 'match',
    prompt: 'Match each Canvas render mode to what it is for.',
    pairs: [
      ['Screen Space - Overlay', 'HUD drawn on top of everything'],
      ['Screen Space - Camera', 'UI that a camera can apply effects to'],
      ['World Space', 'A health bar floating above a character'],
      ['Canvas Scaler', 'Keeping the UI the same size on every screen'],
    ],
    explain: 'Overlay ignores the camera entirely, which is why post-processing never touches it.',
  },
  {
    id: 'un.ui.2',
    concepts: ['un.anchors'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'The UI looks right on your monitor and wrong on a phone. What is usually wrong?',
    options: [
      'The anchors are set to the centre instead of the edge the element should stick to',
      'The Canvas is disabled',
      'The images are too large',
      'The camera is orthographic',
    ],
    answer: [0],
    explain: 'Anchors say what an element is measured from. Get them right and resizing stops being a fight.',
  },
  {
    id: 'un.ui.3',
    concepts: ['un.uievents'],
    difficulty: 4,
    level: 6,
    kind: 'order',
    prompt: 'Wire a button to your code from a script.',
    lines: ['public Button playButton;', 'void Start()', '{', '    playButton.onClick.AddListener(StartGame);', '}'],
    explain: 'Adding the listener in code keeps the wiring visible in the file rather than only in the Inspector.',
  },
  {
    id: 'un.ui.4',
    concepts: ['un.uievents'],
    difficulty: 4,
    level: 7,
    kind: 'bug',
    prompt: 'Clicks pass straight through the panel. What is missing?',
    code: 'Panel (Image, alpha 0)\n  Button\nEventSystem present\nRaycast Target: off',
    buggyLine: 4,
    why: {
      options: [
        'Raycast Target must be on for the graphic to receive pointer events',
        'The panel needs a Rigidbody',
        'Alpha 0 objects cannot be clicked at all',
        'The EventSystem must be a child of the Canvas',
      ],
      answer: 0,
    },
    explain: 'An invisible graphic can still take clicks — but only while Raycast Target is ticked.',
  },

  /* -------------------------------------------------------------- un.look */
  {
    id: 'un.look.1',
    concepts: ['un.materials'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'What is the difference between a Material and a Shader?',
    options: [
      'The shader is the program; the material is a set of values fed into it',
      'They are the same thing',
      'A material is 2D, a shader is 3D',
      'A shader belongs to a camera',
    ],
    answer: [0],
    explain: 'One shader, many materials. That is why changing a colour does not mean writing shader code.',
  },
  {
    id: 'un.look.2',
    concepts: ['un.materials'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'Why does editing renderer.material at runtime leak?',
    options: [
      'It clones the material for that renderer, and the clone is never freed automatically',
      'Materials cannot be edited at runtime',
      'It recompiles the shader',
      'It disables batching permanently',
    ],
    answer: [0],
    explain: 'Use sharedMaterial to change all of them, or a MaterialPropertyBlock to change one cheaply.',
  },
  {
    id: 'un.look.3',
    concepts: ['un.animator'],
    difficulty: 4,
    level: 6,
    kind: 'match',
    prompt: 'Match each Animator piece to its job.',
    pairs: [
      ['State', 'One clip that can play'],
      ['Transition', 'The rule for moving between states'],
      ['Parameter', 'A value your script sets'],
      ['Layer', 'Animating parts of the body separately'],
    ],
    explain: 'Scripts should set parameters, never force states. The state machine owns the transitions.',
  },
  {
    id: 'un.look.4',
    concepts: ['un.audio'],
    difficulty: 3,
    level: 5,
    kind: 'choice',
    prompt: 'What does an AudioListener do?',
    options: [
      'It is the ear — usually one, on the main camera',
      'It plays a clip',
      'It mixes tracks',
      'It loads audio files',
    ],
    answer: [0],
    explain: 'Two listeners in a scene is a warning you will see once and then never forget.',
  },
  {
    id: 'un.look.5',
    concepts: ['un.audio'],
    difficulty: 4,
    level: 7,
    kind: 'blank',
    prompt: 'Play a one-off sound effect without cutting off whatever is already playing.',
    template: 'audioSource.{{0}}(hitClip);',
    blanks: [{ accept: ['PlayOneShot'], width: 12 }],
    explain: 'Play replaces the current clip; PlayOneShot layers on top, which is what a hit sound wants.',
  },
]);
