import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'un.editor',
    title: 'The Unity editor',
    blurb: 'Scenes, the Hierarchy, the Inspector, and prefabs.',
    concepts: ['un.scene', 'un.hierarchy', 'un.prefab'],
    requires: [],
    level: 'intro',
    tags: ['games'],
    unit: 'The editor',
  },
  {
    id: 'un.objects',
    title: 'GameObjects and components',
    blurb: 'Everything is a GameObject; behaviour comes from what you attach.',
    concepts: ['un.gameobject', 'un.components', 'un.transform'],
    requires: ['un.editor'],
    level: 'core',
    tags: ['games'],
    unit: 'The editor',
  },
  {
    id: 'un.scripting',
    title: 'MonoBehaviour scripting',
    blurb: 'Start, Update, serialized fields, and finding things at runtime.',
    concepts: ['un.lifecycle', 'un.serialize', 'un.getcomponent'],
    requires: ['un.objects'],
    level: 'core',
    tags: ['games', 'apps'],
    unit: 'Scripting',
  },
  {
    id: 'un.physics',
    title: 'Physics and input',
    blurb: 'Rigidbodies, colliders, triggers, and reading the controls.',
    concepts: ['un.rigidbody', 'un.collider', 'un.input'],
    requires: ['un.scripting'],
    level: 'applied',
    tags: ['games'],
    unit: 'Gameplay',
  },
  {
    id: 'un.build',
    title: 'Making a game of it',
    blurb: 'Instantiating, destroying, coroutines, and shipping a build.',
    concepts: ['un.instantiate', 'un.coroutine', 'un.build'],
    requires: ['un.physics'],
    level: 'applied',
    tags: ['games'],
    unit: 'Gameplay',
  },
];

export const unityTrack: Track = {
  id: 'unity',
  name: 'Unity',
  kind: 'engine',
  tagline: 'The engine most indie games are built in',
  blurb:
    'C# scripting, a component system that is easy to reason about, and builds for desktop, mobile and console from one project.',
  lang: 'csharp',
  mark: 'Un',
  tags: ['games', 'graphics', 'apps'],
  goals: ['games', 'apps', 'curious'],
  slope: 3,
  transfersFrom: ['csharp', 'ue5'],
  skills,
};

export const unityExercises = forTrack('unity', [
  /* ---------------------------------------------------------- un.editor */
  {
    id: 'un.scene.1',
    concepts: ['un.scene'],
    difficulty: 1,
    kind: 'choice',
    prompt: 'What is a Scene in Unity?',
    options: [
      'A container of GameObjects that makes up a level or screen',
      'A single 3D model',
      'A C# file',
      'A build target',
    ],
    answer: [0],
    explain: 'Menus, levels and loading screens are all just Scenes. You can also load several at once.',
  },
  {
    id: 'un.hier.1',
    concepts: ['un.hierarchy'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each editor window to what it shows.',
    pairs: [
      ['Hierarchy', 'the GameObjects in the open scene'],
      ['Project', 'the asset files on disk'],
      ['Inspector', 'the components on what you selected'],
      ['Console', 'logs, warnings and errors'],
    ],
    explain: 'Hierarchy is what is in the scene right now; Project is everything the game could use.',
  },
  {
    id: 'un.hier.2',
    concepts: ['un.hierarchy', 'un.transform'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What happens when you make one GameObject a child of another?',
    options: [
      'Its transform becomes relative to the parent, so moving the parent moves it too',
      'It is destroyed with the parent only',
      'It copies the parent components',
      'Nothing, it is only visual tidying',
    ],
    answer: [0],
    explain: 'Parenting is how a weapon stays in a hand. It also does destroy children with the parent.',
  },
  {
    id: 'un.prefab.1',
    concepts: ['un.prefab'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What is a Prefab?',
    options: [
      'A saved GameObject template you can spawn many copies of, with edits flowing to every instance',
      'A compiled script',
      'A lighting setting',
      'A build configuration',
    ],
    answer: [0],
    explain: 'Change the prefab once and every enemy in every scene updates. Not using prefabs is the beginner trap.',
  },
  {
    id: 'un.prefab.2',
    concepts: ['un.prefab'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'You changed an instance in the scene but the prefab did not update. Why?',
    options: [
      'Instance edits are local overrides until you Apply them to the prefab',
      'Prefabs are read-only',
      'The scene was not saved',
      'You must restart Unity',
    ],
    answer: [0],
    explain: 'Overrides show in the Inspector with a blue line, and can be applied or reverted individually.',
  },

  /* --------------------------------------------------------- un.objects */
  {
    id: 'un.go.1',
    concepts: ['un.gameobject', 'un.components'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'What does an empty GameObject actually have?',
    options: ['Only a Transform', 'Nothing at all', 'A Renderer', 'A Collider'],
    answer: [0],
    explain: 'Every GameObject has a Transform, always. Everything else you add.',
  },
  {
    id: 'un.comp.1',
    concepts: ['un.components'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each component to what it provides.',
    pairs: [
      ['Mesh Renderer', 'draws the object'],
      ['Rigidbody', 'physics simulation'],
      ['Box Collider', 'a shape for collisions'],
      ['Audio Source', 'plays a sound'],
    ],
    explain: 'Composition over inheritance: an object is defined by what is attached, not by a class hierarchy.',
  },
  {
    id: 'un.tr.1',
    concepts: ['un.transform'],
    difficulty: 3,
    kind: 'predict',
    prompt: 'What does this line do?',
    lang: 'csharp',
    code: 'transform.position += Vector3.forward * Time.deltaTime;',
    options: [
      'Moves one unit per frame',
      'Moves one unit per second, regardless of frame rate',
      'Teleports to z = 1',
      'Nothing',
    ],
    answer: 1,
    explain: 'Time.deltaTime is the seconds since last frame. Multiplying by it makes movement frame-rate independent.',
  },
  {
    id: 'un.tr.2',
    concepts: ['un.transform'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What is the difference between transform.position and transform.localPosition?',
    options: [
      'position is in world space; localPosition is relative to the parent',
      'localPosition is read-only',
      'They are identical',
      'position is only for 2D',
    ],
    answer: [0],
    explain: 'With no parent they are the same, which is why the difference only bites later.',
  },

  /* ------------------------------------------------------- un.scripting */
  {
    id: 'un.life.1',
    concepts: ['un.lifecycle'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each MonoBehaviour method to when Unity calls it.',
    pairs: [
      ['Awake', 'once, before anything else, even if disabled'],
      ['Start', 'once, before the first frame this object is enabled'],
      ['Update', 'every frame'],
      ['FixedUpdate', 'on the fixed physics timestep'],
    ],
    explain: 'Set up your own references in Awake, reach for other objects in Start — by then everything exists.',
  },
  {
    id: 'un.life.2',
    concepts: ['un.lifecycle'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Where should Rigidbody forces be applied?',
    options: ['FixedUpdate', 'Update', 'LateUpdate', 'OnGUI'],
    answer: [0],
    explain: 'Physics runs on its own clock. Applying force in Update makes behaviour depend on frame rate.',
  },
  {
    id: 'un.ser.1',
    concepts: ['un.serialize'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Expose this private field in the Inspector.',
    lang: 'csharp',
    template: '[{{0}}]\nprivate float speed = 5f;',
    blanks: [{ accept: ['SerializeField'], width: 15 }],
    explain: 'Better than making it public: designers can tune it, but other scripts still cannot reach in and set it.',
  },
  {
    id: 'un.ser.2',
    concepts: ['un.serialize'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'You changed a default value in code but the Inspector still shows the old one. Why?',
    options: [
      'Serialized values are stored on the instance and override the code default',
      'Unity needs a restart',
      'The script failed to compile',
      'Defaults are ignored',
    ],
    answer: [0],
    explain: 'Right-click the component and Reset, or edit the value in the Inspector directly.',
  },
  {
    id: 'un.gc.1',
    concepts: ['un.getcomponent'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This tanks the frame rate. Which line?',
    lang: 'csharp',
    code: 'void Update()\n{\n    GetComponent<Rigidbody>().AddForce(Vector3.up);\n}',
    buggyLine: 3,
    why: {
      options: [
        'GetComponent searches every frame; cache it in Awake instead',
        'AddForce needs a mode',
        'Vector3.up should be Vector3.forward',
      ],
      answer: 0,
    },
    explain: 'Store it once in a field. This single change fixes more Unity performance problems than any other.',
  },

  /* --------------------------------------------------------- un.physics */
  {
    id: 'un.rb.1',
    concepts: ['un.rigidbody'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does adding a Rigidbody do?',
    options: [
      'Hands control of the object to the physics engine',
      'Makes it visible',
      'Adds a collider',
      'Makes it a prefab',
    ],
    answer: [0],
    explain: 'Setting transform.position on a Rigidbody fights the simulation. Use MovePosition or forces instead.',
  },
  {
    id: 'un.coll.1',
    concepts: ['un.collider'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each callback to what triggers it.',
    pairs: [
      ['OnCollisionEnter', 'two solid colliders touch'],
      ['OnTriggerEnter', 'something enters a collider marked Is Trigger'],
      ['OnTriggerExit', 'something leaves that trigger volume'],
    ],
    explain: 'At least one of the two objects needs a Rigidbody, or neither callback ever fires.',
  },
  {
    id: 'un.coll.2',
    concepts: ['un.collider'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'A trigger never fires. What is the most likely cause?',
    options: [
      'Neither object has a Rigidbody',
      'The collider is too large',
      'The script is in the wrong folder',
      'Triggers only work in 2D',
    ],
    answer: [0],
    explain: 'A kinematic Rigidbody on the moving object is the usual fix, and costs nothing.',
  },
  {
    id: 'un.input.1',
    concepts: ['un.input'],
    difficulty: 4,
    kind: 'match',
    prompt: 'Match each input call to what it returns.',
    lang: 'csharp',
    pairs: [
      ['Input.GetKeyDown', 'true on the single frame the key went down'],
      ['Input.GetKey', 'true every frame the key is held'],
      ['Input.GetAxis', 'a smoothed value from -1 to 1'],
    ],
    explain: 'GetKeyDown for a jump, GetKey for a held sprint. Swapping them makes controls feel broken.',
  },
  {
    id: 'un.input.2',
    concepts: ['un.input', 'un.lifecycle'],
    difficulty: 5,
    kind: 'bug',
    prompt: 'The jump sometimes does not register. Which line is at fault?',
    lang: 'csharp',
    code: 'void FixedUpdate()\n{\n    if (Input.GetKeyDown(KeyCode.Space))\n        rb.AddForce(Vector3.up * 5f, ForceMode.Impulse);\n}',
    buggyLine: 3,
    why: {
      options: [
        'GetKeyDown should be polled in Update; FixedUpdate can miss the frame it was true',
        'The force is too small',
        'ForceMode.Impulse is wrong',
      ],
      answer: 0,
    },
    explain: 'Read input in Update, set a flag, and apply the force in FixedUpdate.',
  },

  /* ----------------------------------------------------------- un.build */
  {
    id: 'un.inst.1',
    concepts: ['un.instantiate'],
    difficulty: 4,
    kind: 'assemble',
    prompt: 'Build the call that spawns the bullet prefab at the muzzle.',
    lang: 'csharp',
    answer: ['Instantiate', '(', 'bulletPrefab', ',', 'muzzle.position', ',', 'muzzle.rotation', ')'],
    distractors: ['new', 'Spawn', 'Create'],
    explain: 'Never use new on a MonoBehaviour. Instantiate is how Unity makes a copy of a prefab.',
  },
  {
    id: 'un.inst.2',
    concepts: ['un.instantiate'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Spawning hundreds of bullets a second causes stutter. What is the standard fix?',
    options: [
      'Object pooling: reuse a fixed set of objects instead of creating and destroying them',
      'Lower the resolution',
      'Use a bigger prefab',
      'Disable physics',
    ],
    answer: [0],
    explain: 'Instantiate and Destroy allocate, and allocation eventually means a garbage collection spike.',
  },
  {
    id: 'un.cor.1',
    concepts: ['un.coroutine'],
    difficulty: 5,
    kind: 'order',
    prompt: 'Order a coroutine that waits two seconds and then acts.',
    lang: 'csharp',
    lines: [
      'IEnumerator Explode()',
      '{',
      '    yield return new WaitForSeconds(2f);',
      '    Destroy(gameObject);',
      '}',
    ],
    explain: 'A coroutine must return IEnumerator and be started with StartCoroutine, not called directly.',
  },
  {
    id: 'un.cor.2',
    concepts: ['un.coroutine'],
    difficulty: 5,
    kind: 'choice',
    prompt: 'What happens to a running coroutine if its GameObject is disabled?',
    options: [
      'It stops immediately',
      'It keeps running',
      'It restarts',
      'It moves to another object',
    ],
    answer: [0],
    explain: 'Coroutines are tied to the behaviour that started them. Disabling the object silently cancels them.',
  },
  {
    id: 'un.build.1',
    concepts: ['un.build'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'A scene works in the editor but is missing from the build. What did you forget?',
    options: [
      'Adding it to Scenes In Build in Build Settings',
      'Saving the project',
      'A camera',
      'Lighting data',
    ],
    answer: [0],
    explain: 'Only scenes listed there get compiled in, and only those can be loaded by name at runtime.',
  },
]);
