import type { Skill, Track } from '@/engine/types';
import { forTrack } from '../build';

const skills: Skill[] = [
  {
    id: 'web.html',
    title: 'The shape of a page',
    blurb: 'Tags, attributes, and the skeleton every document shares.',
    concepts: ['web.tags', 'web.attributes', 'web.structure'],
    requires: [],
    level: 'intro',
    tags: ['web'],
    unit: 'HTML',
  },
  {
    id: 'web.semantics',
    title: 'Meaningful markup',
    blurb: 'Elements that say what they are, and the accessibility that comes free with them.',
    concepts: ['web.semantic', 'web.a11y', 'web.forms'],
    requires: ['web.html'],
    level: 'core',
    tags: ['web'],
    unit: 'HTML',
  },
  {
    id: 'web.css',
    title: 'Styling',
    blurb: 'Selectors, the box model, and units that behave.',
    concepts: ['web.selectors', 'web.boxmodel', 'web.units'],
    requires: ['web.html'],
    level: 'core',
    tags: ['web', 'graphics'],
    unit: 'CSS',
  },
  {
    id: 'web.layout',
    title: 'Layout',
    blurb: 'Flexbox for a row, grid for a page.',
    concepts: ['web.flex', 'web.grid'],
    requires: ['web.css'],
    level: 'core',
    tags: ['web', 'graphics'],
    unit: 'CSS',
  },
  {
    id: 'web.responsive',
    title: 'Every screen',
    blurb: 'Media queries, fluid sizing, and designing from small upwards.',
    concepts: ['web.media', 'web.fluid'],
    requires: ['web.layout'],
    level: 'applied',
    tags: ['web'],
    unit: 'CSS',
  },
];

export const webTrack: Track = {
  id: 'web',
  name: 'HTML & CSS',
  kind: 'language',
  tagline: 'Make something people can actually look at',
  blurb:
    'The fastest route from nothing to a thing on a screen. No build step, no install, and every browser is already a preview window.',
  lang: 'html',
  mark: '<>',
  tags: ['web', 'graphics'],
  goals: ['web', 'curious'],
  slope: 1,
  transfersFrom: [],
  skills,
};

export const webExercises = forTrack('web', [
  /* ------------------------------------------------------------ web.html */
  {
    id: 'web.tags.1',
    concepts: ['web.tags'],
    difficulty: 1,
    kind: 'assemble',
    prompt: 'Build a paragraph containing the word Hello.',
    lang: 'html',
    answer: ['<p>', 'Hello', '</p>'],
    distractors: ['<paragraph>', '</br>', '<text>'],
    explain: 'Most elements come in pairs: an opening tag, the content, and a closing tag with a slash.',
  },
  {
    id: 'web.tags.2',
    concepts: ['web.tags'],
    difficulty: 2,
    kind: 'choice',
    prompt: 'Which of these is a void element that needs no closing tag?',
    options: ['<div>', '<img>', '<span>', '<section>'],
    answer: [1],
    explain: 'img, br, hr, input and meta have no content, so they have nothing to close around.',
  },
  {
    id: 'web.attr.1',
    concepts: ['web.attributes'],
    difficulty: 2,
    kind: 'blank',
    prompt: 'Point this link at example.com.',
    lang: 'html',
    template: '<a {{0}}="https://example.com">Visit</a>',
    blanks: [{ accept: ['href'], width: 6 }],
    explain: 'Attributes live in the opening tag as name="value" pairs.',
  },
  {
    id: 'web.attr.2',
    concepts: ['web.attributes', 'web.a11y'],
    difficulty: 3,
    kind: 'bug',
    prompt: 'A screen reader cannot describe this image. Which line is wrong?',
    lang: 'html',
    code: '<figure>\n  <img src="cat.png">\n  <figcaption>Our office cat</figcaption>\n</figure>',
    buggyLine: 2,
    why: {
      options: ['The alt attribute is missing', 'src should be href', 'img needs a closing tag'],
      answer: 0,
    },
    explain: 'Every img needs alt. Use alt="" only when the image is purely decorative.',
  },
  {
    id: 'web.struct.1',
    concepts: ['web.structure'],
    difficulty: 2,
    kind: 'order',
    prompt: 'Order the skeleton of an HTML document.',
    lang: 'html',
    lines: ['<!doctype html>', '<html lang="en">', '  <head>', '    <title>Page</title>', '  </head>', '  <body>', '    <h1>Hi</h1>', '  </body>', '</html>'],
    explain: 'head holds information about the page; body holds what people see.',
  },
  {
    id: 'web.struct.2',
    concepts: ['web.structure'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'What does <!doctype html> do?',
    options: [
      'Imports HTML5',
      'Tells the browser to use standards mode rather than a legacy quirks mode',
      'Declares the character encoding',
      'Nothing, it is optional decoration',
    ],
    answer: [1],
    explain: 'Leave it out and browsers emulate 1990s bugs, which makes CSS behave strangely.',
  },

  /* ------------------------------------------------------- web.semantics */
  {
    id: 'web.sem.1',
    concepts: ['web.semantic'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each element to what it is for.',
    lang: 'html',
    pairs: [
      ['<nav>', 'a block of navigation links'],
      ['<main>', 'the one central content area'],
      ['<article>', 'a self-contained piece that would make sense alone'],
      ['<aside>', 'content tangential to the main flow'],
    ],
    explain: 'A page of divs works, but semantic elements give assistive tech and search engines a map.',
  },
  {
    id: 'web.sem.2',
    concepts: ['web.semantic'],
    difficulty: 3,
    kind: 'choice',
    prompt: 'Why use <button> instead of a <div> with a click handler?',
    options: [
      'It is shorter to type',
      'It is focusable, works with Enter and Space, and announces itself as a button',
      'div cannot have click handlers',
      'It renders faster',
    ],
    answer: [1],
    explain: 'Recreating all that behaviour on a div takes a dozen lines you will get subtly wrong.',
  },
  {
    id: 'web.a11y.1',
    concepts: ['web.a11y'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Which heading structure is correct for a page?',
    options: [
      'Several h1s, one per section',
      'One h1, then h2s for sections, h3s inside those',
      'Whatever looks the right size',
      'Start at h3 so text is smaller',
    ],
    answer: [1],
    explain: 'Headings are an outline, not a font-size picker. Style the size with CSS instead.',
  },
  {
    id: 'web.forms.1',
    concepts: ['web.forms', 'web.a11y'],
    difficulty: 4,
    kind: 'blank',
    prompt: 'Connect the label to the input.',
    lang: 'html',
    template: '<label {{0}}="email">Email</label>\n<input id="email" type="email">',
    blanks: [{ accept: ['for'], width: 5 }],
    explain: 'for matches the input id, which makes the label clickable and readable by screen readers.',
  },
  {
    id: 'web.forms.2',
    concepts: ['web.forms'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each input type to what it gives you on a phone.',
    pairs: [
      ['type="email"', 'a keyboard with @ on it'],
      ['type="number"', 'a numeric keypad'],
      ['type="date"', 'a native date picker'],
    ],
    explain: 'Choosing the right type is free usability on mobile, and free validation in the browser.',
  },

  /* ------------------------------------------------------------- web.css */
  {
    id: 'web.sel.1',
    concepts: ['web.selectors'],
    difficulty: 2,
    kind: 'match',
    prompt: 'Match each CSS selector to what it targets.',
    lang: 'css',
    pairs: [
      ['.card', 'every element with class card'],
      ['#total', 'the element with id total'],
      ['a:hover', 'links under the pointer'],
      ['ul li', 'list items anywhere inside a ul'],
    ],
    explain: 'A dot is a class, a hash is an id, a space means "descendant of".',
  },
  {
    id: 'web.sel.2',
    concepts: ['web.selectors'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Two rules set the same colour. Which wins?',
    options: [
      'The one written last',
      'The one with higher specificity; only on a tie does the later one win',
      'The one with !important, always',
      'The shorter selector',
    ],
    answer: [1],
    explain: 'Specificity first, source order second. Reaching for !important is usually a sign to simplify.',
  },
  {
    id: 'web.box.1',
    concepts: ['web.boxmodel'],
    difficulty: 3,
    kind: 'order',
    prompt: 'Order the box model from the content outwards.',
    lines: ['content', 'padding', 'border', 'margin'],
    explain: 'Padding is inside the border, margin is outside it. Backgrounds reach the border, not the margin.',
  },
  {
    id: 'web.box.2',
    concepts: ['web.boxmodel'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'With the default box-sizing, how wide is this element in total?',
    lang: 'css',
    code: '.box {\n  width: 200px;\n  padding: 20px;\n  border: 5px solid;\n}',
    options: ['200px', '240px', '250px', '230px'],
    answer: 2,
    explain: '200 + 20 + 20 + 5 + 5 = 250. Setting box-sizing: border-box makes width mean the total instead.',
  },
  {
    id: 'web.units.1',
    concepts: ['web.units'],
    difficulty: 3,
    kind: 'match',
    prompt: 'Match each unit to what it is relative to.',
    pairs: [
      ['rem', 'the root font size'],
      ['em', 'the font size of this element'],
      ['%', 'the parent'],
      ['vh', 'the viewport height'],
    ],
    explain: 'rem for spacing and type keeps a page scalable when someone enlarges their default font.',
  },
  {
    id: 'web.css.1',
    concepts: ['web.selectors', 'web.boxmodel'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'The heading is not turning red. Which line is wrong?',
    lang: 'css',
    code: '.title {\n  colour: red;\n  font-size: 2rem;\n}',
    buggyLine: 2,
    why: {
      options: ['CSS spells it "color"', 'red is not a valid colour', 'The selector should be #title'],
      answer: 0,
    },
    explain: 'CSS uses American spelling throughout: color, center, gray. An unknown property is silently ignored.',
  },

  /* ---------------------------------------------------------- web.layout */
  {
    id: 'web.flex.1',
    concepts: ['web.flex'],
    difficulty: 3,
    kind: 'blank',
    prompt: 'Lay these children out in a row, spaced apart.',
    lang: 'css',
    template: '.bar {\n  display: {{0}};\n  justify-content: space-between;\n}',
    blanks: [{ accept: ['flex'], width: 6 }],
    explain: 'justify-content works along the main axis; align-items works across it.',
  },
  {
    id: 'web.flex.2',
    concepts: ['web.flex'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'How do you centre a single child both ways with flexbox?',
    options: [
      'text-align: center',
      'display: flex; justify-content: center; align-items: center',
      'margin: auto only',
      'position: absolute; top: 50%',
    ],
    answer: [1],
    explain: 'Three lines that solved a problem which used to take hacks and a table.',
  },
  {
    id: 'web.grid.1',
    concepts: ['web.grid'],
    difficulty: 4,
    kind: 'predict',
    prompt: 'How many equal columns does this create?',
    lang: 'css',
    code: '.page {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n}',
    options: ['1', '2', '3', 'As many as fit'],
    answer: 2,
    explain: 'fr is a fraction of the free space, so three 1fr columns split it evenly.',
  },
  {
    id: 'web.grid.2',
    concepts: ['web.grid', 'web.flex'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Grid or flexbox?',
    options: [
      'Grid for two-dimensional layout; flexbox for one row or column of content',
      'Grid is newer, so always grid',
      'Flexbox for pages, grid for buttons',
      'They do the same thing',
    ],
    answer: [0],
    explain: 'Rows *and* columns at once means grid. A single line of things that should space themselves means flex.',
  },
  {
    id: 'web.grid.3',
    concepts: ['web.grid'],
    difficulty: 5,
    kind: 'assemble',
    prompt: 'Build the declaration for a responsive card grid with a 240px minimum.',
    answer: ['grid-template-columns', ':', 'repeat(auto-fit, minmax(240px, 1fr))', ';'],
    distractors: ['flex-wrap', 'columns', 'repeat(3, 1fr)'],
    explain: 'auto-fit with minmax is a whole responsive grid without a single media query.',
  },

  /* ------------------------------------------------------ web.responsive */
  {
    id: 'web.media.1',
    concepts: ['web.media'],
    difficulty: 4,
    kind: 'blank',
    prompt: 'Apply these styles only on screens 600px and wider.',
    lang: 'css',
    template: '@{{0}} (min-width: 600px) {\n  .grid { grid-template-columns: 1fr 1fr; }\n}',
    blanks: [{ accept: ['media'], width: 7 }],
    explain: 'min-width queries build up from small screens, which is the order that produces less CSS.',
  },
  {
    id: 'web.media.2',
    concepts: ['web.media'],
    difficulty: 4,
    kind: 'choice',
    prompt: 'Why write mobile styles first and add media queries for larger screens?',
    options: [
      'Phones are more popular',
      'The base case stays simple, and each query only adds what the extra room allows',
      'max-width queries do not work',
      'It downloads faster',
    ],
    answer: [1],
    explain: 'Starting wide and stripping away means every query has to undo something.',
  },
  {
    id: 'web.fluid.1',
    concepts: ['web.fluid'],
    difficulty: 5,
    kind: 'predict',
    prompt: 'What does this font size do?',
    lang: 'css',
    code: 'h1 {\n  font-size: clamp(1.5rem, 5vw, 3rem);\n}',
    options: [
      'Always 5% of the viewport width',
      'Scales with the viewport but never below 1.5rem or above 3rem',
      'Alternates between the three values',
      'Is invalid CSS',
    ],
    answer: 1,
    explain: 'clamp(min, preferred, max) replaces a stack of breakpoints for type sizing.',
  },
  {
    id: 'web.fluid.2',
    concepts: ['web.fluid', 'web.units'],
    difficulty: 4,
    kind: 'bug',
    prompt: 'This container overflows on phones. Which line causes it?',
    lang: 'css',
    code: '.card {\n  width: 400px;\n  padding: 16px;\n  margin: 0 auto;\n}',
    buggyLine: 2,
    why: {
      options: [
        'A fixed width cannot shrink; use max-width instead',
        'The padding is too large',
        'margin auto does not work',
      ],
      answer: 0,
    },
    explain: 'max-width: 400px gives you the same look on desktop and lets it shrink on a phone.',
  },
]);
