import type { Skill } from '@/engine/types';
import { forTrack } from '../build';

export const webExtraSkills: Skill[] = [
  {
    id: 'web.polish',
    title: 'Colour, type and motion',
    blurb: 'Custom properties, transitions, and the settings you have to honour.',
    concepts: ['web.customprops', 'web.transitions', 'web.reducedmotion'],
    requires: ['web.css'],
    level: 'applied',
    tags: ['web', 'graphics'],
    unit: 'CSS',
  },
  {
    id: 'web.perf',
    title: 'Loading fast',
    blurb: 'What makes a page feel slow, and the handful of fixes that matter.',
    concepts: ['web.images', 'web.render', 'web.caching'],
    requires: ['web.responsive'],
    level: 'advanced',
    tags: ['web'],
    unit: 'Shipping',
  },
];

export const webExtra = forTrack('web', [
  {
    id: 'web.tag.x1',
    concepts: ['web.tags'],
    difficulty: 1,
    level: 1,
    kind: 'choice',
    prompt: 'Which one is a paragraph?',
    options: ['<p>Hello</p>', '<para>Hello</para>', '<text>Hello</text>', '<pg>Hello</pg>'],
    answer: [0],
    explain: 'HTML has a fixed vocabulary. Made-up tags render, but mean nothing to anyone.',
  },
  {
    id: 'web.tag.x2',
    concepts: ['web.tags'],
    difficulty: 1,
    level: 1,
    kind: 'blank',
    prompt: 'Close the heading properly.',
    template: '<h1>Title{{0}}',
    blanks: [{ accept: ['</h1>'], width: 6 }],
    explain: 'Most elements come in pairs. img, br and input are among the few that do not.',
  },
  {
    id: 'web.attr.x1',
    concepts: ['web.attributes'],
    difficulty: 2,
    level: 2,
    kind: 'blank',
    prompt: 'Link to example.com.',
    template: '<a {{0}}="https://example.com">Visit</a>',
    blanks: [{ accept: ['href'], width: 5 }],
    explain: 'href on a link, src on an image or script. Mixing them up is a rite of passage.',
  },
  {
    id: 'web.attr.x2',
    concepts: ['web.attributes'],
    difficulty: 2,
    level: 2,
    kind: 'bug',
    prompt: 'Screen readers announce nothing useful here. Which line is the problem?',
    code: '<figure>\n  <img src="chart.png">\n  <figcaption>Sales by quarter</figcaption>\n</figure>',
    buggyLine: 2,
    why: {
      options: [
        'The image has no alt attribute',
        'figure cannot contain img',
        'The caption must come first',
        'src should be href',
      ],
      answer: 0,
    },
    explain: 'alt="" is correct for decoration. A missing alt is the browser guessing on your behalf.',
  },
  {
    id: 'web.struct.x1',
    concepts: ['web.structure'],
    difficulty: 2,
    level: 2,
    kind: 'order',
    prompt: 'Put a minimal page in order.',
    lines: ['<!doctype html>', '<html lang="en">', '<head>', '  <title>Page</title>', '</head>', '<body>', '  <h1>Hi</h1>', '</body>', '</html>'],
    explain: 'The doctype is what keeps browsers out of quirks mode, and lang is what tells a screen reader how to pronounce it.',
  },
  {
    id: 'web.sem.x1',
    concepts: ['web.semantic'],
    difficulty: 2,
    level: 3,
    kind: 'match',
    prompt: 'Match each element to what it is for.',
    pairs: [
      ['<nav>', 'A block of navigation links'],
      ['<main>', 'The unique content of this page'],
      ['<article>', 'Something that stands alone'],
      ['<aside>', 'Tangential content'],
    ],
    explain: 'A div with a class says nothing to assistive tech. These elements do.',
  },
  {
    id: 'web.a11y.x1',
    concepts: ['web.a11y'],
    difficulty: 3,
    level: 3,
    kind: 'choice',
    prompt: 'What is wrong with <div onclick="save()">Save</div>?',
    options: [
      'It is not focusable, not announced as a button, and does not respond to Enter or Space',
      'onclick is deprecated',
      'div cannot have handlers',
      'Nothing',
    ],
    answer: [0],
    explain: 'A <button> gives you all of it for free. Rebuilding that with ARIA is work you do not need.',
  },
  {
    id: 'web.sel.x1',
    concepts: ['web.selectors'],
    difficulty: 2,
    level: 2,
    kind: 'match',
    prompt: 'Match each selector to what it targets.',
    pairs: [
      ['.card', 'Elements with class card'],
      ['#main', 'The element with id main'],
      ['a:hover', 'Links under the pointer'],
      ['ul > li', 'Direct children only'],
    ],
    explain: 'A space means any descendant; > means a direct child. That one character changes everything.',
  },
  {
    id: 'web.box.x1',
    concepts: ['web.boxmodel'],
    difficulty: 3,
    level: 3,
    kind: 'predict',
    prompt: 'How wide is this box on screen?',
    code: '.box {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid;\n  box-sizing: border-box;\n}',
    options: ['200px', '240px', '244px', '204px'],
    answer: 0,
    explain: 'border-box means width includes padding and border. Without it you would get 244px.',
  },
  {
    id: 'web.unit.x1',
    concepts: ['web.units'],
    difficulty: 3,
    level: 4,
    kind: 'choice',
    prompt: 'A reader has set their browser font size to 20px. Which padding grows with it?',
    options: ['padding: 1rem', 'padding: 16px', 'padding: 1vw', 'padding: 5%'],
    answer: [0],
    explain: 'That is the whole argument for rem: a person who needs bigger text gets a bigger layout rather than a cramped one.',
  },
  {
    id: 'web.flex.x1',
    concepts: ['web.flex'],
    difficulty: 3,
    level: 4,
    kind: 'blank',
    prompt: 'Centre a child both ways with flexbox.',
    template: '.wrap {\n  display: flex;\n  {{0}}: center;\n  {{1}}: center;\n}',
    blanks: [{ accept: ['justify-content'], width: 16 }, { accept: ['align-items'], width: 12 }],
    explain: 'justify-content runs along the main axis, align-items across it. Swapping the row to a column swaps them.',
  },

  /* ---------------------------------------------------------- web.polish */
  {
    id: 'web.pol.1',
    concepts: ['web.customprops'],
    difficulty: 3,
    level: 5,
    kind: 'blank',
    prompt: 'Define a colour once and use it.',
    template: ':root {\n  {{0}}accent: #7ef0b2;\n}\n.button {\n  background: {{1}}(--accent);\n}',
    blanks: [{ accept: ['--'], width: 3 }, { accept: ['var'], width: 4 }],
    explain: 'Custom properties cascade and can be changed at runtime, which is how themes are done without a build step.',
  },
  {
    id: 'web.pol.2',
    concepts: ['web.transitions'],
    difficulty: 4,
    level: 6,
    kind: 'choice',
    prompt: 'Which properties are cheap to animate?',
    options: [
      'transform and opacity — they can skip layout and paint',
      'width and height',
      'top and left',
      'margin',
    ],
    answer: [0],
    explain: 'Anything that changes layout forces a reflow of everything around it, every frame.',
  },
  {
    id: 'web.pol.3',
    concepts: ['web.reducedmotion'],
    difficulty: 4,
    level: 6,
    kind: 'blank',
    prompt: 'Respect the reader who asked for less movement.',
    template: '@media (prefers-reduced-motion: {{0}}) {\n  * { animation: none !important; }\n}',
    blanks: [{ accept: ['reduce'], width: 7 }],
    explain: 'For some people motion causes nausea, not delight. The setting is a request, not a preference.',
  },
  {
    id: 'web.pol.4',
    concepts: ['web.transitions'],
    difficulty: 4,
    level: 7,
    kind: 'predict',
    prompt: 'Why does this transition never run?',
    code: '.panel { display: none; transition: opacity 200ms; }\n.panel.open { display: block; opacity: 1; }',
    options: [
      'display cannot be transitioned, so the element appears instantly',
      'The duration is too short',
      'opacity has no starting value',
      'The class name is wrong',
    ],
    answer: 0,
    explain: 'Animate opacity and visibility instead, or the element pops into existence fully formed.',
  },

  /* ------------------------------------------------------------ web.perf */
  {
    id: 'web.perf.1',
    concepts: ['web.images'],
    difficulty: 4,
    level: 7,
    kind: 'choice',
    prompt: 'What is the single biggest win on most pages?',
    options: [
      'Serving images at the size they are displayed, in a modern format',
      'Minifying CSS',
      'Removing comments',
      'Using a CDN for fonts',
    ],
    answer: [0],
    explain: 'A 4000px photo shown at 400px wastes 99% of its bytes. Nothing else is close.',
  },
  {
    id: 'web.perf.2',
    concepts: ['web.images'],
    difficulty: 4,
    level: 7,
    kind: 'blank',
    prompt: 'Let the browser skip images that are far below the fold.',
    template: '<img src="hero.jpg" alt="" {{0}}="lazy">',
    blanks: [{ accept: ['loading'], width: 8 }],
    explain: 'Never lazy-load the image at the top: that one is the thing the reader is waiting for.',
  },
  {
    id: 'web.perf.3',
    concepts: ['web.render'],
    difficulty: 5,
    level: 8,
    kind: 'choice',
    prompt: 'Why does a <script> in <head> without defer slow the page down?',
    options: [
      'Parsing stops while it downloads and runs',
      'It runs twice',
      'It blocks images only',
      'It disables caching',
    ],
    answer: [0],
    explain: 'defer keeps document order and runs after parsing; async runs whenever it lands.',
  },
  {
    id: 'web.perf.4',
    concepts: ['web.caching'],
    difficulty: 5,
    level: 9,
    kind: 'choice',
    prompt: 'How do you cache a bundle for a year and still ship updates?',
    options: [
      'Put a content hash in the filename and cache that immutably',
      'Set a short max-age',
      'Disable caching for JavaScript',
      'Version with a query string and no-cache',
    ],
    answer: [0],
    explain: 'The name changes when the bytes change, so there is never a stale file to invalidate.',
  },
]);
