#!/usr/bin/env node
/**
 * Builds the phone app and generates its service worker.
 *
 * The worker is written here rather than kept in `public/` because it has to
 * name every file of the build it belongs to. That is the difference between
 * an app that opens on a plane and one that opens to a blank screen: the
 * precache list is the actual output of the actual build, hashed filenames
 * and all, so "installed" means installed.
 *
 *   node scripts/build-mobile.mjs   ->   dist-mobile/
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, posix, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'dist-mobile');

execFileSync('npx', ['vite', 'build', '--config', 'vite.mobile.config.ts'], {
  cwd: root,
  stdio: 'inherit',
});

function walk(dir) {
  const found = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...walk(full));
    else found.push(full);
  }
  return found;
}

const files = walk(outDir)
  .map((file) => relative(outDir, file).split(sep).join(posix.sep))
  .filter((file) => file !== 'sw.js')
  .sort();

// The cache name changes whenever any byte of the build changes, which is
// what makes the old cache get thrown away on activate.
const digest = createHash('sha256');
for (const file of files) {
  digest.update(file);
  digest.update(readFileSync(join(outDir, file)));
}
const version = digest.digest('hex').slice(0, 12);

const bytes = files.reduce((n, file) => n + statSync(join(outDir, file)).size, 0);

const sw = `/* Generated by scripts/build-mobile.mjs — do not edit. */
const VERSION = '${version}';
const CACHE = 'codeling-' + VERSION;

/* Every file of this build: the app, the exercise library, the Python
   interpreter, the typefaces, the icons. ${files.length} files, ${(bytes / 1024 / 1024).toFixed(2)} MB. */
const ASSETS = ${JSON.stringify(['./', ...files], null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

// A reminder, when the platform is willing to wake us for one. Chrome grants
// this to installed apps it sees you using; everything else falls back to the
// in-page timer, and neither is allowed to nag you on a day you have practised.
self.addEventListener('periodicsync', (event) => {
  if (event.tag !== 'codeling-reminder') return;
  event.waitUntil(
    self.registration.showNotification('Your streak is waiting', {
      body: 'One short lesson keeps it alive.',
      icon: './pwa/icon-192.png',
      badge: './pwa/icon-192.png',
      tag: 'codeling-reminder',
    }),
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      const open = clients.find((client) => 'focus' in client);
      if (open) return open.focus();
      return self.clients.openWindow('./');
    }),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  // Navigations always resolve to the app shell. There is no server here to
  // ask, and every route the app has is inside that one document.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches
        .match('./index.html', { ignoreSearch: true })
        .then((cached) => cached || fetch(request))
        .catch(() => caches.match('./index.html')),
    );
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            void caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => cached);
    }),
  );
});
`;

writeFileSync(join(outDir, 'sw.js'), sw);
console.log(`\nservice worker: ${files.length} files, ${(bytes / 1024 / 1024).toFixed(2)} MB, version ${version}`);
